// WS0 — Nutrition Knowledge Registry: Foods seed data.
//
// Editorial, human-curated, deterministic. Covers the eight launch categories:
// Healthy fats, Seeds, Legumes, Fermented foods, Herbs, Mushrooms, Vegetables,
// Fruit. Edit freely; every row is upserted by slug.
import type { InsertKnowledgeFood } from "../schema";

export const FOOD_SEED: InsertKnowledgeFood[] = [
  // ── Healthy fats ───────────────────────────────────────────────────────────
  { slug: "extra-virgin-olive-oil", name: "Extra Virgin Olive Oil", category: "Healthy fats",
    subcategory: "Oils", aliases: ["EVOO", "olive oil"],
    description: "A cold-pressed oil rich in unsaturated fats and polyphenols, central to the Mediterranean way of eating.",
    commonForms: ["bottle", "drizzle", "dressing"], storageGuidance: "Keep in a cool, dark cupboard away from heat.", seasonality: "Year-round" },
  { slug: "avocado", name: "Avocado", category: "Healthy fats",
    subcategory: "Fruit fats", aliases: ["avocados"],
    description: "A creamy fruit rich in unsaturated fats, fibre and potassium.",
    commonForms: ["whole", "sliced", "mashed"], storageGuidance: "Ripen at room temperature, then refrigerate.", seasonality: "Year-round (imported)" },
  { slug: "walnuts", name: "Walnuts", category: "Healthy fats",
    subcategory: "Nuts", aliases: ["walnut"],
    description: "A tree nut and one of the few plant sources of omega-3 fats.",
    commonForms: ["whole", "halves", "chopped"], storageGuidance: "Store airtight; refrigerate or freeze to keep fresh.", seasonality: "Autumn (dried year-round)" },
  { slug: "almonds", name: "Almonds", category: "Healthy fats",
    subcategory: "Nuts", aliases: ["almond"],
    description: "A versatile nut supplying vitamin E, magnesium and plant protein.",
    commonForms: ["whole", "flaked", "ground", "butter"], storageGuidance: "Store airtight in a cool place.", seasonality: "Year-round" },
  { slug: "salmon", name: "Salmon", category: "Healthy fats",
    subcategory: "Oily fish", aliases: ["fresh salmon", "salmon fillet"],
    description: "An oily fish rich in omega-3 fats and vitamin D.",
    commonForms: ["fillet", "tinned", "smoked"], storageGuidance: "Keep chilled and use within use-by date; freeze for longer.", seasonality: "Year-round (farmed)" },
  { slug: "sardines", name: "Sardines", category: "Healthy fats",
    subcategory: "Oily fish", aliases: ["pilchards"],
    description: "Small oily fish, often tinned, rich in omega-3, calcium and vitamin D.",
    commonForms: ["tinned", "fresh"], storageGuidance: "Tins keep in the cupboard; chill once opened.", seasonality: "Year-round (tinned)" },

  // ── Seeds ──────────────────────────────────────────────────────────────────
  { slug: "pumpkin-seeds", name: "Pumpkin Seeds", category: "Seeds",
    subcategory: "Whole seeds", aliases: ["pepitas"],
    description: "Green seeds rich in magnesium, zinc and plant protein.",
    commonForms: ["raw", "toasted", "in trail mix"], storageGuidance: "Store airtight in a cool, dry place.", seasonality: "Year-round" },
  { slug: "sunflower-seeds", name: "Sunflower Seeds", category: "Seeds",
    subcategory: "Whole seeds", aliases: ["sunflower kernels"],
    description: "Small seeds supplying vitamin E, selenium and healthy fats.",
    commonForms: ["raw", "toasted"], storageGuidance: "Store airtight away from heat.", seasonality: "Year-round" },
  { slug: "chia-seeds", name: "Chia Seeds", category: "Seeds",
    subcategory: "Whole seeds", aliases: ["chia"],
    description: "Tiny seeds high in fibre and plant omega-3 that swell into a gel in liquid.",
    commonForms: ["dry", "soaked", "pudding"], storageGuidance: "Store airtight in a cool cupboard.", seasonality: "Year-round" },
  { slug: "flaxseed", name: "Flaxseed", category: "Seeds",
    subcategory: "Whole seeds", aliases: ["linseed", "ground flax"],
    description: "Seeds rich in fibre and plant omega-3; best ground so the body can use them.",
    commonForms: ["whole", "ground", "oil"], storageGuidance: "Keep ground flax refrigerated.", seasonality: "Year-round" },
  { slug: "sesame-seeds", name: "Sesame Seeds", category: "Seeds",
    subcategory: "Whole seeds", aliases: ["sesame", "tahini"],
    description: "Small seeds supplying calcium and healthy fats, also pressed into tahini.",
    commonForms: ["whole", "toasted", "tahini"], storageGuidance: "Store airtight away from light.", seasonality: "Year-round" },
  { slug: "hemp-seeds", name: "Hemp Seeds", category: "Seeds",
    subcategory: "Whole seeds", aliases: ["hemp hearts"],
    description: "Soft seeds offering complete plant protein and a balance of healthy fats.",
    commonForms: ["hulled", "in smoothies"], storageGuidance: "Refrigerate after opening.", seasonality: "Year-round" },

  // ── Legumes ──────────────────────────────────────────────────────────────────
  { slug: "butter-beans", name: "Butter Beans", category: "Legumes",
    subcategory: "Beans", aliases: ["lima beans"],
    description: "Large, creamy beans rich in fibre and plant protein.",
    commonForms: ["tinned", "dried"], storageGuidance: "Tins keep in the cupboard; chill leftovers.", seasonality: "Year-round" },
  { slug: "chickpeas", name: "Chickpeas", category: "Legumes",
    subcategory: "Beans", aliases: ["garbanzo beans", "chana"],
    description: "Versatile legumes high in fibre and plant protein, the base of hummus.",
    commonForms: ["tinned", "dried", "hummus", "roasted"], storageGuidance: "Tins keep in the cupboard; chill leftovers.", seasonality: "Year-round" },
  { slug: "red-lentils", name: "Red Lentils", category: "Legumes",
    subcategory: "Lentils", aliases: ["lentils", "split red lentils"],
    description: "Quick-cooking lentils rich in fibre, plant protein and iron.",
    commonForms: ["dried", "cooked", "dhal"], storageGuidance: "Store dried in an airtight jar.", seasonality: "Year-round" },
  { slug: "black-beans", name: "Black Beans", category: "Legumes",
    subcategory: "Beans", aliases: ["turtle beans"],
    description: "Dark beans rich in fibre, plant protein and anthocyanins.",
    commonForms: ["tinned", "dried"], storageGuidance: "Tins keep in the cupboard; chill leftovers.", seasonality: "Year-round" },
  { slug: "kidney-beans", name: "Kidney Beans", category: "Legumes",
    subcategory: "Beans", aliases: ["red kidney beans"],
    description: "Hearty beans high in fibre and plant protein; always cook thoroughly.",
    commonForms: ["tinned", "dried"], storageGuidance: "Tins keep in the cupboard; chill leftovers.", seasonality: "Year-round" },
  { slug: "edamame", name: "Edamame", category: "Legumes",
    subcategory: "Soya", aliases: ["soya beans", "soybeans"],
    description: "Young green soya beans offering complete plant protein and fibre.",
    commonForms: ["frozen", "podded"], storageGuidance: "Keep frozen until needed.", seasonality: "Year-round (frozen)" },
  { slug: "garden-peas", name: "Garden Peas", category: "Legumes",
    subcategory: "Peas", aliases: ["peas", "frozen peas"],
    description: "Sweet green peas supplying fibre, plant protein and vitamin C.",
    commonForms: ["frozen", "fresh"], storageGuidance: "Keep frozen; refrigerate fresh pods.", seasonality: "Summer (frozen year-round)" },

  // ── Fermented foods ────────────────────────────────────────────────────────
  { slug: "kimchi", name: "Kimchi", category: "Fermented foods",
    subcategory: "Fermented vegetables", aliases: ["kimchee"],
    description: "A Korean ferment of cabbage and spices, rich in live cultures and fibre.",
    commonForms: ["jarred", "fresh"], storageGuidance: "Keep refrigerated; flavour deepens over time.", seasonality: "Year-round" },
  { slug: "sauerkraut", name: "Sauerkraut", category: "Fermented foods",
    subcategory: "Fermented vegetables", aliases: ["fermented cabbage"],
    description: "Fermented cabbage providing live cultures and fibre — choose unpasteurised for live cultures.",
    commonForms: ["jarred", "fresh"], storageGuidance: "Keep refrigerated once opened.", seasonality: "Year-round" },
  { slug: "kefir", name: "Kefir", category: "Fermented foods",
    subcategory: "Fermented dairy", aliases: ["milk kefir"],
    description: "A cultured, drinkable ferment rich in live cultures and calcium.",
    commonForms: ["plain", "in smoothies"], storageGuidance: "Keep refrigerated.", seasonality: "Year-round" },
  { slug: "live-yogurt", name: "Live Yogurt", category: "Fermented foods",
    subcategory: "Fermented dairy", aliases: ["natural yogurt", "plain yogurt"],
    description: "Natural yogurt with live cultures, supplying calcium and protein.",
    commonForms: ["plain", "Greek-style"], storageGuidance: "Keep refrigerated.", seasonality: "Year-round" },
  { slug: "miso", name: "Miso", category: "Fermented foods",
    subcategory: "Fermented soya", aliases: ["miso paste"],
    description: "A savoury fermented soya bean paste used to add depth and live cultures.",
    commonForms: ["paste", "soup"], storageGuidance: "Keep refrigerated.", seasonality: "Year-round" },
  { slug: "tempeh", name: "Tempeh", category: "Fermented foods",
    subcategory: "Fermented soya", aliases: ["fermented soya"],
    description: "A firm fermented soya cake offering complete plant protein and fibre.",
    commonForms: ["block", "sliced", "marinated"], storageGuidance: "Keep refrigerated or frozen.", seasonality: "Year-round" },

  // ── Herbs ──────────────────────────────────────────────────────────────────
  { slug: "parsley", name: "Parsley", category: "Herbs",
    subcategory: "Soft herbs", aliases: ["flat-leaf parsley", "curly parsley"],
    description: "A fresh herb rich in vitamin C and vitamin K, great for finishing dishes.",
    commonForms: ["fresh", "dried"], storageGuidance: "Keep fresh stems in water or wrapped in the fridge.", seasonality: "Year-round" },
  { slug: "basil", name: "Basil", category: "Herbs",
    subcategory: "Soft herbs", aliases: ["sweet basil"],
    description: "A fragrant herb full of aromatic polyphenols, central to pesto.",
    commonForms: ["fresh", "dried"], storageGuidance: "Keep at room temperature; refrigeration can blacken leaves.", seasonality: "Summer" },
  { slug: "coriander", name: "Coriander", category: "Herbs",
    subcategory: "Soft herbs", aliases: ["cilantro", "fresh coriander"],
    description: "A bright herb used across many cuisines, rich in plant compounds.",
    commonForms: ["fresh", "seeds", "ground"], storageGuidance: "Wrap and refrigerate fresh leaves.", seasonality: "Year-round" },
  { slug: "mint", name: "Mint", category: "Herbs",
    subcategory: "Soft herbs", aliases: ["spearmint", "fresh mint"],
    description: "A cooling herb that lifts both sweet and savoury dishes.",
    commonForms: ["fresh", "dried", "tea"], storageGuidance: "Keep stems in water or wrapped in the fridge.", seasonality: "Spring to autumn" },
  { slug: "rosemary", name: "Rosemary", category: "Herbs",
    subcategory: "Woody herbs", aliases: ["fresh rosemary"],
    description: "An aromatic woody herb rich in protective plant compounds.",
    commonForms: ["fresh", "dried"], storageGuidance: "Refrigerate fresh sprigs; dried keeps in the cupboard.", seasonality: "Year-round" },
  { slug: "thyme", name: "Thyme", category: "Herbs",
    subcategory: "Woody herbs", aliases: ["fresh thyme"],
    description: "A small-leaved woody herb full of aromatic polyphenols.",
    commonForms: ["fresh", "dried"], storageGuidance: "Refrigerate fresh; dried keeps in the cupboard.", seasonality: "Year-round" },

  // ── Mushrooms ────────────────────────────────────────────────────────────────
  { slug: "white-mushrooms", name: "White Mushrooms", category: "Mushrooms",
    subcategory: "Cultivated", aliases: ["button mushrooms", "closed cup"],
    description: "Everyday mushrooms supplying B vitamins and fibre, and vitamin D if grown in light.",
    commonForms: ["whole", "sliced"], storageGuidance: "Keep in a paper bag in the fridge.", seasonality: "Year-round" },
  { slug: "chestnut-mushrooms", name: "Chestnut Mushrooms", category: "Mushrooms",
    subcategory: "Cultivated", aliases: ["cremini", "brown mushrooms"],
    description: "A nuttier, firmer cousin of the white mushroom with B vitamins and fibre.",
    commonForms: ["whole", "sliced"], storageGuidance: "Keep in a paper bag in the fridge.", seasonality: "Year-round" },
  { slug: "shiitake-mushrooms", name: "Shiitake Mushrooms", category: "Mushrooms",
    subcategory: "Speciality", aliases: ["shiitake"],
    description: "Savoury, umami-rich mushrooms supplying fibre and protective plant compounds.",
    commonForms: ["fresh", "dried"], storageGuidance: "Refrigerate fresh; store dried airtight.", seasonality: "Year-round" },
  { slug: "oyster-mushrooms", name: "Oyster Mushrooms", category: "Mushrooms",
    subcategory: "Speciality", aliases: ["oyster mushroom"],
    description: "Delicate, fan-shaped mushrooms with B vitamins and fibre.",
    commonForms: ["fresh"], storageGuidance: "Keep in a paper bag in the fridge.", seasonality: "Year-round" },

  // ── Vegetables ─────────────────────────────────────────────────────────────
  { slug: "kale", name: "Kale", category: "Vegetables",
    subcategory: "Leafy greens", aliases: ["curly kale", "cavolo nero"],
    description: "A hardy leafy green rich in vitamin K, vitamin C and sulforaphane.",
    commonForms: ["fresh", "frozen", "crisps"], storageGuidance: "Refrigerate; use within a few days.", seasonality: "Autumn to spring" },
  { slug: "spinach", name: "Spinach", category: "Vegetables",
    subcategory: "Leafy greens", aliases: ["baby spinach"],
    description: "A tender green supplying folate, iron and vitamin K.",
    commonForms: ["fresh", "frozen"], storageGuidance: "Refrigerate fresh; keep frozen for longer.", seasonality: "Spring and autumn" },
  { slug: "broccoli", name: "Broccoli", category: "Vegetables",
    subcategory: "Brassicas", aliases: ["calabrese"],
    description: "A green brassica rich in vitamin C, folate and sulforaphane.",
    commonForms: ["fresh", "frozen"], storageGuidance: "Refrigerate; steam lightly to keep nutrients.", seasonality: "Summer to autumn" },
  { slug: "tomatoes", name: "Tomatoes", category: "Vegetables",
    subcategory: "Fruiting vegetables", aliases: ["tomato", "cherry tomatoes"],
    description: "Juicy fruits used as a vegetable, rich in lycopene and vitamin C.",
    commonForms: ["fresh", "tinned", "passata", "sun-dried"], storageGuidance: "Keep fresh at room temperature for best flavour.", seasonality: "Summer (tinned year-round)" },
  { slug: "sweet-potato", name: "Sweet Potato", category: "Vegetables",
    subcategory: "Root vegetables", aliases: ["sweet potatoes"],
    description: "A naturally sweet root rich in beta-carotene and fibre.",
    commonForms: ["whole", "mashed", "roasted"], storageGuidance: "Store in a cool, dark place, not the fridge.", seasonality: "Autumn to winter" },
  { slug: "red-pepper", name: "Red Pepper", category: "Vegetables",
    subcategory: "Fruiting vegetables", aliases: ["bell pepper", "capsicum"],
    description: "A sweet pepper exceptionally high in vitamin C and beta-carotene.",
    commonForms: ["fresh", "roasted"], storageGuidance: "Refrigerate in the salad drawer.", seasonality: "Summer to autumn" },
  { slug: "carrots", name: "Carrots", category: "Vegetables",
    subcategory: "Root vegetables", aliases: ["carrot"],
    description: "A crunchy root and a leading source of beta-carotene.",
    commonForms: ["whole", "grated", "batons"], storageGuidance: "Refrigerate; remove leafy tops first.", seasonality: "Year-round" },
  { slug: "beetroot", name: "Beetroot", category: "Vegetables",
    subcategory: "Root vegetables", aliases: ["beets", "beet"],
    description: "A deep-red root rich in dietary nitrates and anthocyanins.",
    commonForms: ["raw", "cooked", "juiced"], storageGuidance: "Refrigerate; cooked vacuum packs keep well.", seasonality: "Autumn to winter" },
  { slug: "garlic", name: "Garlic", category: "Vegetables",
    subcategory: "Alliums", aliases: ["garlic clove", "garlic bulb"],
    description: "An aromatic allium that releases allicin when crushed or chopped.",
    commonForms: ["fresh", "crushed", "roasted"], storageGuidance: "Store in a cool, dry, airy place.", seasonality: "Year-round" },
  { slug: "onion", name: "Onion", category: "Vegetables",
    subcategory: "Alliums", aliases: ["onions", "brown onion", "red onion"],
    description: "A kitchen staple allium supplying prebiotic fibre and flavonoids.",
    commonForms: ["fresh", "sliced", "diced"], storageGuidance: "Store in a cool, dry, dark place.", seasonality: "Year-round" },

  // ── Fruit ──────────────────────────────────────────────────────────────────
  { slug: "blueberries", name: "Blueberries", category: "Fruit",
    subcategory: "Berries", aliases: ["blueberry"],
    description: "Small blue berries famous for anthocyanins and other polyphenols.",
    commonForms: ["fresh", "frozen"], storageGuidance: "Refrigerate fresh; frozen works well in cooking.", seasonality: "Summer (frozen year-round)" },
  { slug: "strawberries", name: "Strawberries", category: "Fruit",
    subcategory: "Berries", aliases: ["strawberry"],
    description: "Sweet red berries rich in vitamin C and flavonoids.",
    commonForms: ["fresh", "frozen"], storageGuidance: "Refrigerate and eat within a few days.", seasonality: "Early summer" },
  { slug: "apples", name: "Apples", category: "Fruit",
    subcategory: "Top fruit", aliases: ["apple"],
    description: "A crunchy everyday fruit supplying fibre and flavonoids, especially in the skin.",
    commonForms: ["whole", "sliced", "stewed"], storageGuidance: "Keep cool; the fridge keeps them crisp.", seasonality: "Autumn (stored year-round)" },
  { slug: "bananas", name: "Bananas", category: "Fruit",
    subcategory: "Tropical fruit", aliases: ["banana"],
    description: "A portable fruit supplying potassium, vitamin B6 and steady energy.",
    commonForms: ["whole", "sliced", "frozen"], storageGuidance: "Ripen at room temperature.", seasonality: "Year-round" },
  { slug: "oranges", name: "Oranges", category: "Fruit",
    subcategory: "Citrus", aliases: ["orange"],
    description: "Juicy citrus fruit and a classic source of vitamin C and folate.",
    commonForms: ["whole", "segments", "juiced"], storageGuidance: "Keep at room temperature or chill.", seasonality: "Winter" },
  { slug: "kiwi", name: "Kiwi", category: "Fruit",
    subcategory: "Exotic fruit", aliases: ["kiwifruit", "kiwi fruit"],
    description: "A green fruit that is exceptionally rich in vitamin C and fibre.",
    commonForms: ["whole", "sliced"], storageGuidance: "Ripen at room temperature, then refrigerate.", seasonality: "Year-round (imported)" },
];
