// WS0 — Nutrition Knowledge Registry: Foods seed data.
//
// Editorial, human-curated, deterministic. Covers the eight launch categories:
// Healthy fats, Seeds, Legumes, Fermented foods, Herbs, Mushrooms, Vegetables,
// Fruit. Edit freely; every row is upserted by slug.
import type { InsertKnowledgeFood } from "../schema";

export const FOOD_SEED: InsertKnowledgeFood[] = [
  // ── Healthy fats ───────────────────────────────────────────────────────────
  { slug: "extra-virgin-olive-oil", name: "Extra Virgin Olive Oil", category: "Healthy fats",
    subcategory: "Oils", aliases: ["EVOO", "olive oil"],
    description: "A cold-pressed oil rich in unsaturated fats and polyphenols, central to the Mediterranean way of eating.",
    commonForms: ["bottle", "drizzle", "dressing"], storageGuidance: "Keep in a cool, dark cupboard away from heat.", seasonality: "Year-round" },
  { slug: "avocado", name: "Avocado", category: "Healthy fats",
    subcategory: "Fruit fats", aliases: ["avocados"],
    description: "A creamy fruit rich in unsaturated fats, fibre and potassium.",
    commonForms: ["whole", "sliced", "mashed"], storageGuidance: "Ripen at room temperature, then refrigerate.", seasonality: "Year-round (imported)" },
  { slug: "walnuts", name: "Walnuts", category: "Healthy fats",
    subcategory: "Nuts", aliases: ["walnut"],
    description: "A tree nut and one of the few plant sources of omega-3 fats.",
    commonForms: ["whole", "halves", "chopped"], storageGuidance: "Store airtight; refrigerate or freeze to keep fresh.", seasonality: "Autumn (dried year-round)" },
  { slug: "almonds", name: "Almonds", category: "Healthy fats",
    subcategory: "Nuts", aliases: ["almond"],
    description: "A versatile nut supplying vitamin E, magnesium and plant protein.",
    commonForms: ["whole", "flaked", "ground", "butter"], storageGuidance: "Store airtight in a cool place.", seasonality: "Year-round" },
  { slug: "salmon", name: "Salmon", category: "Healthy fats",
    subcategory: "Oily fish", aliases: ["fresh salmon", "salmon fillet"],
    description: "An oily fish rich in omega-3 fats and vitamin D.",
    commonForms: ["fillet", "tinned", "smoked"], storageGuidance: "Keep chilled and use within use-by date; freeze for longer.", seasonality: "Year-round (farmed)" },
  { slug: "sardines", name: "Sardines", category: "Healthy fats",
    subcategory: "Oily fish", aliases: ["pilchards"],
    description: "Small oily fish, often tinned, rich in omega-3, calcium and vitamin D.",
    commonForms: ["tinned", "fresh"], storageGuidance: "Tins keep in the cupboard; chill once opened.", seasonality: "Year-round (tinned)" },

  // ── Seeds ──────────────────────────────────────────────────────────────────
  { slug: "pumpkin-seeds", name: "Pumpkin Seeds", category: "Seeds",
    subcategory: "Whole seeds", aliases: ["pepitas"],
    description: "Green seeds rich in magnesium, zinc and plant protein.",
    commonForms: ["raw", "toasted", "in trail mix"], storageGuidance: "Store airtight in a cool, dry place.", seasonality: "Year-round" },
  { slug: "sunflower-seeds", name: "Sunflower Seeds", category: "Seeds",
    subcategory: "Whole seeds", aliases: ["sunflower kernels"],
    description: "Small seeds supplying vitamin E, selenium and healthy fats.",
    commonForms: ["raw", "toasted"], storageGuidance: "Store airtight away from heat.", seasonality: "Year-round" },
  { slug: "chia-seeds", name: "Chia Seeds", category: "Seeds",
    subcategory: "Whole seeds", aliases: ["chia"],
    description: "Tiny seeds high in fibre and plant omega-3 that swell into a gel in liquid.",
    commonForms: ["dry", "soaked", "pudding"], storageGuidance: "Store airtight in a cool cupboard.", seasonality: "Year-round" },
  { slug: "flaxseed", name: "Flaxseed", category: "Seeds",
    subcategory: "Whole seeds", aliases: ["linseed", "ground flax"],
    description: "Seeds rich in fibre and plant omega-3; best ground so the body can use them.",
    commonForms: ["whole", "ground", "oil"], storageGuidance: "Keep ground flax refrigerated.", seasonality: "Year-round" },
  { slug: "sesame-seeds", name: "Sesame Seeds", category: "Seeds",
    subcategory: "Whole seeds", aliases: ["sesame", "tahini"],
    description: "Small seeds supplying calcium and healthy fats, also pressed into tahini.",
    commonForms: ["whole", "toasted", "tahini"], storageGuidance: "Store airtight away from light.", seasonality: "Year-round" },
  { slug: "hemp-seeds", name: "Hemp Seeds", category: "Seeds",
    subcategory: "Whole seeds", aliases: ["hemp hearts"],
    description: "Soft seeds offering complete plant protein and a balance of healthy fats.",
    commonForms: ["hulled", "in smoothies"], storageGuidance: "Refrigerate after opening.", seasonality: "Year-round" },

  // ── Legumes ──────────────────────────────────────────────────────────────────
  { slug: "butter-beans", name: "Butter Beans", category: "Legumes",
    subcategory: "Beans", aliases: ["lima beans"],
    description: "Large, creamy beans rich in fibre and plant protein.",
    commonForms: ["tinned", "dried"], storageGuidance: "Tins keep in the cupboard; chill leftovers.", seasonality: "Year-round" },
  { slug: "chickpeas", name: "Chickpeas", category: "Legumes",
    subcategory: "Beans", aliases: ["garbanzo beans", "chana"],
    description: "Versatile legumes high in fibre and plant protein, the base of hummus.",
    commonForms: ["tinned", "dried", "hummus", "roasted"], storageGuidance: "Tins keep in the cupboard; chill leftovers.", seasonality: "Year-round" },
  { slug: "red-lentils", name: "Red Lentils", category: "Legumes",
    subcategory: "Lentils", aliases: ["lentils", "split red lentils"],
    description: "Quick-cooking lentils rich in fibre, plant protein and iron.",
    commonForms: ["dried", "cooked", "dhal"], storageGuidance: "Store dried in an airtight jar.", seasonality: "Year-round" },
  { slug: "black-beans", name: "Black Beans", category: "Legumes",
    subcategory: "Beans", aliases: ["turtle beans"],
    description: "Dark beans rich in fibre, plant protein and anthocyanins.",
    commonForms: ["tinned", "dried"], storageGuidance: "Tins keep in the cupboard; chill leftovers.", seasonality: "Year-round" },
  { slug: "kidney-beans", name: "Kidney Beans", category: "Legumes",
    subcategory: "Beans", aliases: ["red kidney beans"],
    description: "Hearty beans high in fibre and plant protein; always cook thoroughly.",
    commonForms: ["tinned", "dried"], storageGuidance: "Tins keep in the cupboard; chill leftovers.", seasonality: "Year-round" },
  { slug: "edamame", name: "Edamame", category: "Legumes",
    subcategory: "Soya", aliases: ["soya beans", "soybeans"],
    description: "Young green soya beans offering complete plant protein and fibre.",
    commonForms: ["frozen", "podded"], storageGuidance: "Keep frozen until needed.", seasonality: "Year-round (frozen)" },
  { slug: "garden-peas", name: "Garden Peas", category: "Legumes",
    subcategory: "Peas", aliases: ["peas", "frozen peas"],
    description: "Sweet green peas supplying fibre, plant protein and vitamin C.",
    commonForms: ["frozen", "fresh"], storageGuidance: "Keep frozen; refrigerate fresh pods.", seasonality: "Summer (frozen year-round)" },

  // ── Fermented foods ────────────────────────────────────────────────────────
  { slug: "kimchi", name: "Kimchi", category: "Fermented foods",
    subcategory: "Fermented vegetables", aliases: ["kimchee"],
    description: "A Korean ferment of cabbage and spices, rich in live cultures and fibre.",
    commonForms: ["jarred", "fresh"], storageGuidance: "Keep refrigerated; flavour deepens over time.", seasonality: "Year-round" },
  { slug: "sauerkraut", name: "Sauerkraut", category: "Fermented foods",
    subcategory: "Fermented vegetables", aliases: ["fermented cabbage"],
    description: "Fermented cabbage providing live cultures and fibre — choose unpasteurised for live cultures.",
    commonForms: ["jarred", "fresh"], storageGuidance: "Keep refrigerated once opened.", seasonality: "Year-round" },
  { slug: "kefir", name: "Kefir", category: "Fermented foods",
    subcategory: "Fermented dairy", aliases: ["milk kefir"],
    description: "A cultured, drinkable ferment rich in live cultures and calcium.",
    commonForms: ["plain", "in smoothies"], storageGuidance: "Keep refrigerated.", seasonality: "Year-round" },
  { slug: "live-yogurt", name: "Live Yogurt", category: "Fermented foods",
    subcategory: "Fermented dairy", aliases: ["natural yogurt", "plain yogurt"],
    description: "Natural yogurt with live cultures, supplying calcium and protein.",
    commonForms: ["plain", "Greek-style"], storageGuidance: "Keep refrigerated.", seasonality: "Year-round" },
  { slug: "miso", name: "Miso", category: "Fermented foods",
    subcategory: "Fermented soya", aliases: ["miso paste"],
    description: "A savoury fermented soya bean paste used to add depth and live cultures.",
    commonForms: ["paste", "soup"], storageGuidance: "Keep refrigerated.", seasonality: "Year-round" },
  { slug: "tempeh", name: "Tempeh", category: "Fermented foods",
    subcategory: "Fermented soya", aliases: ["fermented soya"],
    description: "A firm fermented soya cake offering complete plant protein and fibre.",
    commonForms: ["block", "sliced", "marinated"], storageGuidance: "Keep refrigerated or frozen.", seasonality: "Year-round" },

  // ── Herbs ──────────────────────────────────────────────────────────────────
  { slug: "parsley", name: "Parsley", category: "Herbs",
    subcategory: "Soft herbs", aliases: ["flat-leaf parsley", "curly parsley"],
    description: "A fresh herb rich in vitamin C and vitamin K, great for finishing dishes.",
    commonForms: ["fresh", "dried"], storageGuidance: "Keep fresh stems in water or wrapped in the fridge.", seasonality: "Year-round" },
  { slug: "basil", name: "Basil", category: "Herbs",
    subcategory: "Soft herbs", aliases: ["sweet basil"],
    description: "A fragrant herb full of aromatic polyphenols, central to pesto.",
    commonForms: ["fresh", "dried"], storageGuidance: "Keep at room temperature; refrigeration can blacken leaves.", seasonality: "Summer" },
  { slug: "coriander", name: "Coriander", category: "Herbs",
    subcategory: "Soft herbs", aliases: ["cilantro", "fresh coriander"],
    description: "A bright herb used across many cuisines, rich in plant compounds.",
    commonForms: ["fresh", "seeds", "ground"], storageGuidance: "Wrap and refrigerate fresh leaves.", seasonality: "Year-round" },
  { slug: "mint", name: "Mint", category: "Herbs",
    subcategory: "Soft herbs", aliases: ["spearmint", "fresh mint"],
    description: "A cooling herb that lifts both sweet and savoury dishes.",
    commonForms: ["fresh", "dried", "tea"], storageGuidance: "Keep stems in water or wrapped in the fridge.", seasonality: "Spring to autumn" },
  { slug: "rosemary", name: "Rosemary", category: "Herbs",
    subcategory: "Woody herbs", aliases: ["fresh rosemary"],
    description: "An aromatic woody herb rich in protective plant compounds.",
    commonForms: ["fresh", "dried"], storageGuidance: "Refrigerate fresh sprigs; dried keeps in the cupboard.", seasonality: "Year-round" },
  { slug: "thyme", name: "Thyme", category: "Herbs",
    subcategory: "Woody herbs", aliases: ["fresh thyme"],
    description: "A small-leaved woody herb full of aromatic polyphenols.",
    commonForms: ["fresh", "dried"], storageGuidance: "Refrigerate fresh; dried keeps in the cupboard.", seasonality: "Year-round" },

  // ── Mushrooms ────────────────────────────────────────────────────────────────
  { slug: "white-mushrooms", name: "White Mushrooms", category: "Mushrooms",
    subcategory: "Cultivated", aliases: ["button mushrooms", "closed cup"],
    description: "Everyday mushrooms supplying B vitamins and fibre, and vitamin D if grown in light.",
    commonForms: ["whole", "sliced"], storageGuidance: "Keep in a paper bag in the fridge.", seasonality: "Year-round" },
  { slug: "chestnut-mushrooms", name: "Chestnut Mushrooms", category: "Mushrooms",
    subcategory: "Cultivated", aliases: ["cremini", "brown mushrooms"],
    description: "A nuttier, firmer cousin of the white mushroom with B vitamins and fibre.",
    commonForms: ["whole", "sliced"], storageGuidance: "Keep in a paper bag in the fridge.", seasonality: "Year-round" },
  { slug: "shiitake-mushrooms", name: "Shiitake Mushrooms", category: "Mushrooms",
    subcategory: "Speciality", aliases: ["shiitake"],
    description: "Savoury, umami-rich mushrooms supplying fibre and protective plant compounds.",
    commonForms: ["fresh", "dried"], storageGuidance: "Refrigerate fresh; store dried airtight.", seasonality: "Year-round" },
  { slug: "oyster-mushrooms", name: "Oyster Mushrooms", category: "Mushrooms",
    subcategory: "Speciality", aliases: ["oyster mushroom"],
    description: "Delicate, fan-shaped mushrooms with B vitamins and fibre.",
    commonForms: ["fresh"], storageGuidance: "Keep in a paper bag in the fridge.", seasonality: "Year-round" },

  // ── Vegetables ─────────────────────────────────────────────────────────────
  { slug: "kale", name: "Kale", category: "Vegetables",
    subcategory: "Leafy greens", aliases: ["curly kale", "cavolo nero"],
    description: "A hardy leafy green rich in vitamin K, vitamin C and sulforaphane.",
    commonForms: ["fresh", "frozen", "crisps"], storageGuidance: "Refrigerate; use within a few days.", seasonality: "Autumn to spring" },
  { slug: "spinach", name: "Spinach", category: "Vegetables",
    subcategory: "Leafy greens", aliases: ["baby spinach"],
    description: "A tender green supplying folate, iron and vitamin K.",
    commonForms: ["fresh", "frozen"], storageGuidance: "Refrigerate fresh; keep frozen for longer.", seasonality: "Spring and autumn" },
  { slug: "broccoli", name: "Broccoli", category: "Vegetables",
    subcategory: "Brassicas", aliases: ["calabrese"],
    description: "A green brassica rich in vitamin C, folate and sulforaphane.",
    commonForms: ["fresh", "frozen"], storageGuidance: "Refrigerate; steam lightly to keep nutrients.", seasonality: "Summer to autumn" },
  { slug: "tomatoes", name: "Tomatoes", category: "Vegetables",
    subcategory: "Fruiting vegetables", aliases: ["tomato", "cherry tomatoes"],
    description: "Juicy fruits used as a vegetable, rich in lycopene and vitamin C.",
    commonForms: ["fresh", "tinned", "passata", "sun-dried"], storageGuidance: "Keep fresh at room temperature for best flavour.", seasonality: "Summer (tinned year-round)" },
  { slug: "sweet-potato", name: "Sweet Potato", category: "Vegetables",
    subcategory: "Root vegetables", aliases: ["sweet potatoes"],
    description: "A naturally sweet root rich in beta-carotene and fibre.",
    commonForms: ["whole", "mashed", "roasted"], storageGuidance: "Store in a cool, dark place, not the fridge.", seasonality: "Autumn to winter" },
  { slug: "red-pepper", name: "Red Pepper", category: "Vegetables",
    subcategory: "Fruiting vegetables", aliases: ["bell pepper", "capsicum"],
    description: "A sweet pepper exceptionally high in vitamin C and beta-carotene.",
    commonForms: ["fresh", "roasted"], storageGuidance: "Refrigerate in the salad drawer.", seasonality: "Summer to autumn" },
  { slug: "carrots", name: "Carrots", category: "Vegetables",
    subcategory: "Root vegetables", aliases: ["carrot"],
    description: "A crunchy root and a leading source of beta-carotene.",
    commonForms: ["whole", "grated", "batons"], storageGuidance: "Refrigerate; remove leafy tops first.", seasonality: "Year-round" },
  { slug: "beetroot", name: "Beetroot", category: "Vegetables",
    subcategory: "Root vegetables", aliases: ["beets", "beet"],
    description: "A deep-red root rich in dietary nitrates and anthocyanins.",
    commonForms: ["raw", "cooked", "juiced"], storageGuidance: "Refrigerate; cooked vacuum packs keep well.", seasonality: "Autumn to winter" },
  { slug: "garlic", name: "Garlic", category: "Vegetables",
    subcategory: "Alliums", aliases: ["garlic clove", "garlic bulb"],
    description: "An aromatic allium that releases allicin when crushed or chopped.",
    commonForms: ["fresh", "crushed", "roasted"], storageGuidance: "Store in a cool, dry, airy place.", seasonality: "Year-round" },
  { slug: "onion", name: "Onion", category: "Vegetables",
    subcategory: "Alliums", aliases: ["onions", "brown onion", "red onion"],
    description: "A kitchen staple allium supplying prebiotic fibre and flavonoids.",
    commonForms: ["fresh", "sliced", "diced"], storageGuidance: "Store in a cool, dry, dark place.", seasonality: "Year-round" },

  // ── Fruit ──────────────────────────────────────────────────────────────────
  { slug: "blueberries", name: "Blueberries", category: "Fruit",
    subcategory: "Berries", aliases: ["blueberry"],
    description: "Small blue berries famous for anthocyanins and other polyphenols.",
    commonForms: ["fresh", "frozen"], storageGuidance: "Refrigerate fresh; frozen works well in cooking.", seasonality: "Summer (frozen year-round)" },
  { slug: "strawberries", name: "Strawberries", category: "Fruit",
    subcategory: "Berries", aliases: ["strawberry"],
    description: "Sweet red berries rich in vitamin C and flavonoids.",
    commonForms: ["fresh", "frozen"], storageGuidance: "Refrigerate and eat within a few days.", seasonality: "Early summer" },
  { slug: "apples", name: "Apples", category: "Fruit",
    subcategory: "Top fruit", aliases: ["apple"],
    description: "A crunchy everyday fruit supplying fibre and flavonoids, especially in the skin.",
    commonForms: ["whole", "sliced", "stewed"], storageGuidance: "Keep cool; the fridge keeps them crisp.", seasonality: "Autumn (stored year-round)" },
  { slug: "bananas", name: "Bananas", category: "Fruit",
    subcategory: "Tropical fruit", aliases: ["banana"],
    description: "A portable fruit supplying potassium, vitamin B6 and steady energy.",
    commonForms: ["whole", "sliced", "frozen"], storageGuidance: "Ripen at room temperature.", seasonality: "Year-round" },
  { slug: "oranges", name: "Oranges", category: "Fruit",
    subcategory: "Citrus", aliases: ["orange"],
    description: "Juicy citrus fruit and a classic source of vitamin C and folate.",
    commonForms: ["whole", "segments", "juiced"], storageGuidance: "Keep at room temperature or chill.", seasonality: "Winter" },
  { slug: "kiwi", name: "Kiwi", category: "Fruit",
    subcategory: "Exotic fruit", aliases: ["kiwifruit", "kiwi fruit"],
    description: "A green fruit that is exceptionally rich in vitamin C and fibre.",
    commonForms: ["whole", "sliced"], storageGuidance: "Ripen at room temperature, then refrigerate.", seasonality: "Year-round (imported)" },

  // ── Mediterranean Vegetables (WS0.6 authoring trial) ───────────────────────
  // Leafy greens
  { slug: "watercress", name: "Watercress", category: "Vegetables",
    subcategory: "Leafy greens", aliases: ["water cress"],
    description: "A peppery aquatic leafy green rich in vitamin K, vitamin C and beta-carotene.",
    commonForms: ["fresh", "bagged", "in soups", "in salads"],
    storageGuidance: "Refrigerate in a sealed bag; use within a few days.",
    seasonality: "Year-round (peak: spring to autumn)" },
  { slug: "rocket", name: "Rocket", category: "Vegetables",
    subcategory: "Leafy greens", aliases: ["arugula", "roquette"],
    description: "A peppery salad leaf supplying vitamin K and folate, with a distinctive bittersweet flavour.",
    commonForms: ["fresh", "bagged", "in salads", "with pasta"],
    storageGuidance: "Refrigerate in the bag; best eaten within a day or two.",
    seasonality: "Year-round (peak: spring and autumn)" },
  // Root vegetables
  { slug: "parsnip", name: "Parsnip", category: "Vegetables",
    subcategory: "Root vegetables", aliases: ["parsnips"],
    description: "A sweet, cream-coloured root high in fibre and folate, traditionally roasted or used in warming soups.",
    commonForms: ["whole", "roasted", "mashed", "in soups"],
    storageGuidance: "Refrigerate; keeps well for up to two weeks.",
    seasonality: "Autumn to winter" },
  { slug: "turnip", name: "Turnip", category: "Vegetables",
    subcategory: "Root vegetables", aliases: ["turnips"],
    description: "A crisp brassica root with a mild, slightly peppery flavour, supplying vitamin C and fibre.",
    commonForms: ["whole", "diced", "roasted", "in stews"],
    storageGuidance: "Refrigerate; use within two weeks.",
    seasonality: "Autumn to winter" },
  { slug: "swede", name: "Swede", category: "Vegetables",
    subcategory: "Root vegetables", aliases: ["rutabaga", "yellow turnip"],
    description: "A mild, starchy brassica root with a sweet flavour when roasted, supplying vitamin C, fibre and potassium.",
    commonForms: ["whole", "diced", "mashed", "roasted"],
    storageGuidance: "Keep in a cool, dark place or refrigerate for longer storage.",
    seasonality: "Autumn to winter" },
  // Brassicas
  { slug: "red-cabbage", name: "Red Cabbage", category: "Vegetables",
    subcategory: "Brassicas", aliases: ["purple cabbage"],
    description: "A vivid purple brassica rich in anthocyanins, fibre and vitamin C, excellent eaten raw, pickled or slow-braised.",
    commonForms: ["raw", "shredded", "pickled", "braised"],
    storageGuidance: "Refrigerate; a cut head keeps well for up to a week.",
    seasonality: "Autumn to winter" },
  { slug: "pak-choi", name: "Pak Choi", category: "Vegetables",
    subcategory: "Brassicas", aliases: ["bok choy", "bok choi"],
    description: "A mild Chinese brassica with crisp stems and leafy tops, supplying vitamin K, vitamin C and calcium.",
    commonForms: ["whole", "halved", "in stir-fries", "steamed"],
    storageGuidance: "Refrigerate and use within a few days.",
    seasonality: "Year-round" },
  // Alliums
  { slug: "spring-onion", name: "Spring Onion", category: "Vegetables",
    subcategory: "Alliums", aliases: ["scallion", "green onion", "salad onion"],
    description: "A slender allium with a mild flavour, eaten whole and rich in vitamin K and vitamin C.",
    commonForms: ["whole", "sliced", "in salads", "in stir-fries"],
    storageGuidance: "Wrap in a damp cloth and refrigerate; use within a week.",
    seasonality: "Spring to autumn (available year-round in shops)" },
  // Fruiting vegetables
  { slug: "aubergine", name: "Aubergine", category: "Vegetables",
    subcategory: "Fruiting vegetables", aliases: ["eggplant", "brinjal"],
    description: "A deep-purple nightshade with a meaty texture when cooked, supplying fibre, polyphenols and manganese.",
    commonForms: ["whole", "sliced", "roasted", "in dips"],
    storageGuidance: "Keep at room temperature for short-term; refrigerate once cut.",
    seasonality: "Late summer to autumn" },
  { slug: "courgette", name: "Courgette", category: "Vegetables",
    subcategory: "Fruiting vegetables", aliases: ["zucchini"],
    description: "A tender summer squash supplying vitamin C, vitamin B6 and potassium, with a mild flavour suited to many styles of cooking.",
    commonForms: ["whole", "sliced", "grated", "spiralised"],
    storageGuidance: "Refrigerate and use within a few days.",
    seasonality: "Summer to early autumn" },
  { slug: "cucumber", name: "Cucumber", category: "Vegetables",
    subcategory: "Fruiting vegetables", aliases: ["cucumbers"],
    description: "A cool, crunchy vegetable with high water content, providing vitamin K and contributing to a hydrating diet.",
    commonForms: ["whole", "sliced", "pickled", "in salads"],
    storageGuidance: "Refrigerate; best used within a week.",
    seasonality: "Summer (imported year-round)" },
  // Bulb and stem vegetables
  { slug: "fennel", name: "Fennel", category: "Vegetables",
    subcategory: "Bulb vegetables", aliases: ["fennel bulb", "florence fennel"],
    description: "An aromatic bulb vegetable with a gentle aniseed flavour, rich in fibre and vitamin C; used raw, roasted or braised.",
    commonForms: ["raw", "braised", "roasted", "in salads"],
    storageGuidance: "Refrigerate and use within a few days; the fronds wilt quickly.",
    seasonality: "Autumn to winter" },
  { slug: "celery", name: "Celery", category: "Vegetables",
    subcategory: "Stem vegetables", aliases: ["celery stalks", "celery sticks"],
    description: "A crunchy stem vegetable rich in vitamin K and potassium, commonly used raw as a snack or as an aromatic base for cooking.",
    commonForms: ["raw", "diced", "in soups", "in stocks"],
    storageGuidance: "Refrigerate; wrapping in foil keeps it crisp longer.",
    seasonality: "Year-round" },
  { slug: "asparagus", name: "Asparagus", category: "Vegetables",
    subcategory: "Stem vegetables", aliases: ["asparagus spears"],
    description: "A seasonal spring vegetable rich in folate, vitamin K and fibre, associated with gut and bone health.",
    commonForms: ["whole", "steamed", "grilled", "roasted"],
    storageGuidance: "Stand upright in a little water in the fridge; use within a few days.",
    seasonality: "Spring (April to June in the UK)" },
  // Speciality
  { slug: "artichoke", name: "Artichoke", category: "Vegetables",
    subcategory: "Speciality vegetables", aliases: ["globe artichoke", "artichoke hearts"],
    description: "The globe artichoke is a thistle vegetable with exceptional fibre content, prized in Mediterranean cooking and associated with digestive health.",
    commonForms: ["whole", "tinned hearts", "jarred hearts", "steamed"],
    storageGuidance: "Refrigerate fresh; tinned hearts keep in the cupboard.",
    seasonality: "Spring to summer" },
  { slug: "broad-beans", name: "Broad Beans", category: "Vegetables",
    subcategory: "Pods and beans", aliases: ["fava beans", "broad bean", "fava"],
    description: "A hearty legume eaten as a vegetable, rich in plant protein, fibre and folate; a Mediterranean staple enjoyed fresh or frozen.",
    commonForms: ["fresh", "frozen", "dried", "podded"],
    storageGuidance: "Keep fresh pods in the fridge; frozen work well year-round.",
    seasonality: "Late spring to summer (frozen year-round)" },
  // Chicory family
  { slug: "radicchio", name: "Radicchio", category: "Vegetables",
    subcategory: "Chicory", aliases: ["red chicory"],
    description: "A vivid red Italian chicory, pleasantly bitter in flavour and rich in anthocyanins, fibre and vitamin K.",
    commonForms: ["whole", "in salads", "grilled", "braised"],
    storageGuidance: "Refrigerate; keeps for up to a week.",
    seasonality: "Autumn to winter" },
  { slug: "chicory", name: "Chicory", category: "Vegetables",
    subcategory: "Chicory", aliases: ["Belgian endive", "witloof"],
    description: "A pale, tightly furled endive with a mild bitter flavour, supplying fibre, vitamin K and folate.",
    commonForms: ["whole", "halved", "braised", "in salads"],
    storageGuidance: "Refrigerate in a dark bag to prevent greening.",
    seasonality: "Autumn to winter" },

  // ══════════════════════════════════════════════════════════════════════════════
  // WS0.8 — Launch Food Coverage Expansion
  // ══════════════════════════════════════════════════════════════════════════════

  // ── Wave 1: Pantry Essentials ────────────────────────────────────────────────
  { slug: "potato", name: "Potato", category: "Vegetables",
    subcategory: "Root vegetables", aliases: ["potatoes", "spud", "spuds"],
    description: "A starchy root vegetable and UK kitchen staple, supplying potassium, vitamin C and vitamin B6.",
    commonForms: ["whole", "mashed", "roasted", "boiled", "baked"],
    storageGuidance: "Store in a cool, dark, well-ventilated place — not the fridge.",
    seasonality: "Year-round (new potatoes: spring and early summer)" },
  { slug: "leek", name: "Leek", category: "Vegetables",
    subcategory: "Alliums", aliases: ["leeks"],
    description: "A mild, sweetly flavoured allium rich in folate, vitamin K and prebiotic fibre.",
    commonForms: ["whole", "sliced", "braised", "in soups"],
    storageGuidance: "Refrigerate and use within a week.",
    seasonality: "Autumn to spring" },
  { slug: "shallot", name: "Shallot", category: "Vegetables",
    subcategory: "Alliums", aliases: ["shallots", "banana shallot"],
    description: "A small, sweet allium closely related to onions, with a mild flavour and a good source of flavonoids.",
    commonForms: ["whole", "sliced", "pickled", "roasted"],
    storageGuidance: "Store in a cool, dry, airy place — the same as onions.",
    seasonality: "Year-round" },
  { slug: "cauliflower", name: "Cauliflower", category: "Vegetables",
    subcategory: "Brassicas", aliases: ["cauli", "cauliflowers"],
    description: "A white brassica rich in vitamin C and vitamin K, with a mild, nutty flavour when roasted.",
    commonForms: ["whole", "florets", "roasted", "riced", "in curries"],
    storageGuidance: "Refrigerate; best used within a few days.",
    seasonality: "Year-round (peak: autumn and winter)" },
  { slug: "cabbage", name: "Cabbage", category: "Vegetables",
    subcategory: "Brassicas", aliases: ["white cabbage", "green cabbage", "savoy cabbage", "hispi cabbage"],
    description: "A brassica rich in vitamin C and fibre; the savoy variety has a sweeter, more delicate flavour than white cabbage.",
    commonForms: ["whole", "shredded", "braised", "in coleslaw", "stuffed"],
    storageGuidance: "Refrigerate; a whole cabbage keeps for up to two weeks.",
    seasonality: "Year-round (savoy: autumn to spring)" },
  { slug: "butternut-squash", name: "Butternut Squash", category: "Vegetables",
    subcategory: "Squash", aliases: ["butternut"],
    description: "A sweet winter squash with vibrant orange flesh rich in beta-carotene, vitamin C and fibre.",
    commonForms: ["whole", "cubed", "roasted", "in soups", "mashed"],
    storageGuidance: "Keep whole in a cool, dry place for weeks; refrigerate once cut.",
    seasonality: "Autumn to winter" },
  { slug: "pumpkin", name: "Pumpkin", category: "Vegetables",
    subcategory: "Squash", aliases: ["pumpkins"],
    description: "A large orange squash high in beta-carotene and vitamin C, used in soups, pies and curries.",
    commonForms: ["whole", "cubed", "roasted", "purée", "in soups"],
    storageGuidance: "Store whole in a cool, dry place; refrigerate once cut and use within a week.",
    seasonality: "Autumn" },
  { slug: "brussels-sprouts", name: "Brussels Sprouts", category: "Vegetables",
    subcategory: "Brassicas", aliases: ["sprouts", "brussels sprout"],
    description: "Small brassica buds rich in vitamin C, vitamin K and sulforaphane; associated with a healthy, varied diet.",
    commonForms: ["whole", "halved", "roasted", "steamed", "shredded"],
    storageGuidance: "Refrigerate; ideally buy on the stalk for best freshness.",
    seasonality: "Autumn to winter" },
  { slug: "celeriac", name: "Celeriac", category: "Vegetables",
    subcategory: "Root vegetables", aliases: ["celery root", "turnip-rooted celery"],
    description: "A knobbly root vegetable with a mild celery flavour, supplying vitamin C, vitamin K and fibre.",
    commonForms: ["whole", "cubed", "grated", "roasted", "in soups", "remoulade"],
    storageGuidance: "Refrigerate; keeps for up to two weeks.",
    seasonality: "Autumn to spring" },
  { slug: "green-beans", name: "Green Beans", category: "Vegetables",
    subcategory: "Pods and beans", aliases: ["French beans", "fine beans", "haricot verts", "string beans"],
    description: "Slender pod vegetables rich in vitamin C, vitamin K and folate, eaten whole with the pod.",
    commonForms: ["whole", "trimmed", "steamed", "blanched", "stir-fried"],
    storageGuidance: "Refrigerate and use within a few days.",
    seasonality: "Summer to early autumn (imported year-round)" },
  { slug: "radish", name: "Radish", category: "Vegetables",
    subcategory: "Root vegetables", aliases: ["radishes"],
    description: "A crisp, peppery root vegetable in the brassica family, eaten raw in salads or pickled.",
    commonForms: ["whole", "sliced", "pickled", "in salads"],
    storageGuidance: "Refrigerate and use within a week; remove leafy tops to extend freshness.",
    seasonality: "Spring to autumn" },
  { slug: "kohlrabi", name: "Kohlrabi", category: "Vegetables",
    subcategory: "Brassicas", aliases: ["german turnip", "knol-kohl"],
    description: "A mild, crunchy brassica bulb with a flavour similar to broccoli stems, supplying vitamin C and fibre.",
    commonForms: ["raw", "sliced", "grated", "roasted", "in slaws"],
    storageGuidance: "Refrigerate; keeps for up to two weeks.",
    seasonality: "Summer to early autumn" },
  { slug: "corn", name: "Sweetcorn", category: "Vegetables",
    subcategory: "Grain vegetables", aliases: ["sweetcorn", "maize", "corn on the cob"],
    description: "A sweet grain vegetable rich in fibre, folate and vitamin C, enjoyed fresh, frozen or tinned.",
    commonForms: ["cob", "kernels", "frozen", "tinned", "grilled"],
    storageGuidance: "Refrigerate fresh cobs; frozen keeps well for months.",
    seasonality: "Summer (frozen and tinned year-round)" },
  { slug: "lettuce", name: "Lettuce", category: "Vegetables",
    subcategory: "Leafy greens", aliases: ["salad leaves", "romaine", "little gem", "iceberg"],
    description: "Leafy salad greens supplying vitamin K, folate and beta-carotene; romaine and little gem have the most nutrients.",
    commonForms: ["whole", "torn", "in salads", "in wraps"],
    storageGuidance: "Refrigerate; keep dry and use within a few days.",
    seasonality: "Year-round (peak: spring to autumn)" },
  { slug: "olives", name: "Olives", category: "Vegetables",
    subcategory: "Fruiting vegetables", aliases: ["black olives", "green olives", "kalamata olives"],
    description: "Small fruit drupes rich in unsaturated fats, vitamin E and polyphenols; a Mediterranean staple eaten whole or pressed into oil.",
    commonForms: ["whole", "pitted", "stuffed", "sliced", "in tapenade"],
    storageGuidance: "Keep jarred olives in brine in the fridge once opened.",
    seasonality: "Year-round (jarred)" },
  { slug: "chard", name: "Chard", category: "Vegetables",
    subcategory: "Leafy greens", aliases: ["Swiss chard", "rainbow chard", "silverbeet"],
    description: "A leafy green with colourful stems, rich in vitamin K, vitamin C, magnesium and beta-carotene.",
    commonForms: ["fresh", "wilted", "sautéed", "in soups"],
    storageGuidance: "Refrigerate; use within a few days.",
    seasonality: "Summer to autumn" },
  { slug: "jerusalem-artichoke", name: "Jerusalem Artichoke", category: "Vegetables",
    subcategory: "Root vegetables", aliases: ["sunchoke", "earth apple"],
    description: "A knobbly tuber from the sunflower family, exceptionally high in inulin fibre and associated with gut health.",
    commonForms: ["whole", "roasted", "in soups", "sliced raw"],
    storageGuidance: "Refrigerate; keeps for up to two weeks.",
    seasonality: "Autumn to winter" },

  // ── Wave 3: Beans, Pulses and Legumes ────────────────────────────────────────
  { slug: "cannellini-beans", name: "Cannellini Beans", category: "Legumes",
    subcategory: "Beans", aliases: ["white kidney beans", "white beans"],
    description: "Large, creamy white beans rich in fibre and plant protein, widely used in Italian cooking.",
    commonForms: ["tinned", "dried", "in soups", "in stews"],
    storageGuidance: "Tins keep in the cupboard; chill leftovers.",
    seasonality: "Year-round" },
  { slug: "borlotti-beans", name: "Borlotti Beans", category: "Legumes",
    subcategory: "Beans", aliases: ["romano beans", "cranberry beans"],
    description: "Speckled Italian beans with a creamy, nutty flavour, rich in fibre, plant protein and folate.",
    commonForms: ["tinned", "dried", "in soups", "in stews"],
    storageGuidance: "Tins keep in the cupboard; chill leftovers.",
    seasonality: "Year-round (fresh: late summer)" },
  { slug: "haricot-beans", name: "Haricot Beans", category: "Legumes",
    subcategory: "Beans", aliases: ["navy beans", "baked beans"],
    description: "Small, oval white beans high in fibre and plant protein; the classic bean in traditional baked beans.",
    commonForms: ["tinned", "dried", "baked beans"],
    storageGuidance: "Tins keep in the cupboard; chill leftovers.",
    seasonality: "Year-round" },
  { slug: "green-lentils", name: "Green Lentils", category: "Legumes",
    subcategory: "Lentils", aliases: ["green lentil", "continental lentils"],
    description: "Earthy, firm lentils that hold their shape well when cooked, rich in plant protein, fibre, iron and folate.",
    commonForms: ["dried", "cooked", "in soups", "in salads"],
    storageGuidance: "Store dried in an airtight jar.",
    seasonality: "Year-round" },
  { slug: "puy-lentils", name: "Puy Lentils", category: "Legumes",
    subcategory: "Lentils", aliases: ["Puy lentil", "French green lentils", "lentilles du Puy"],
    description: "Small, dark green lentils from France with a peppery flavour and firm texture, supplying plant protein, fibre and iron.",
    commonForms: ["dried", "cooked", "in salads", "with fish"],
    storageGuidance: "Store dried in an airtight jar.",
    seasonality: "Year-round" },
  { slug: "beluga-lentils", name: "Beluga Lentils", category: "Legumes",
    subcategory: "Lentils", aliases: ["black lentils", "beluga lentil"],
    description: "Tiny, jet-black lentils resembling caviar, rich in plant protein, fibre and anthocyanins from their dark pigment.",
    commonForms: ["dried", "cooked", "in salads", "in side dishes"],
    storageGuidance: "Store dried in an airtight jar.",
    seasonality: "Year-round" },

  // ── Wave 4: Fruit ────────────────────────────────────────────────────────────
  { slug: "raspberry", name: "Raspberries", category: "Fruit",
    subcategory: "Berries", aliases: ["raspberry"],
    description: "Soft red berries exceptionally high in fibre, vitamin C and protective flavonoids.",
    commonForms: ["fresh", "frozen", "in desserts", "in smoothies"],
    storageGuidance: "Refrigerate and eat within a couple of days; frozen works well year-round.",
    seasonality: "Summer (frozen year-round)" },
  { slug: "pear", name: "Pears", category: "Fruit",
    subcategory: "Top fruit", aliases: ["pear", "conference pear", "williams pear"],
    description: "A gently sweet fruit high in fibre and vitamin C, especially in the skin.",
    commonForms: ["whole", "sliced", "poached", "in crumbles"],
    storageGuidance: "Ripen at room temperature; refrigerate once ripe.",
    seasonality: "Autumn (stored year-round)" },
  { slug: "mango", name: "Mango", category: "Fruit",
    subcategory: "Tropical fruit", aliases: ["mangoes", "alphonso mango"],
    description: "A sweet tropical fruit exceptionally rich in beta-carotene, vitamin C and folate.",
    commonForms: ["whole", "sliced", "frozen", "dried", "in chutneys"],
    storageGuidance: "Ripen at room temperature; refrigerate once ripe.",
    seasonality: "Year-round (imported)" },
  { slug: "grape", name: "Grapes", category: "Fruit",
    subcategory: "Top fruit", aliases: ["grape", "red grapes", "green grapes", "white grapes", "seedless grapes"],
    description: "Small juicy fruits rich in flavonoids and polyphenols; red and black grapes also supply anthocyanins.",
    commonForms: ["fresh", "dried (as raisins)", "in fruit salads"],
    storageGuidance: "Refrigerate and eat within a week.",
    seasonality: "Autumn (imported year-round)" },
  { slug: "lemon", name: "Lemon", category: "Fruit",
    subcategory: "Citrus", aliases: ["lemons", "lemon juice", "lemon zest"],
    description: "A tart citrus fruit exceptionally rich in vitamin C, used for juice, zest and flavouring.",
    commonForms: ["whole", "juiced", "zested", "preserved"],
    storageGuidance: "Keep at room temperature for a week or refrigerate for longer.",
    seasonality: "Year-round (imported)" },
  { slug: "lime", name: "Lime", category: "Fruit",
    subcategory: "Citrus", aliases: ["limes", "lime juice", "lime zest"],
    description: "A bright citrus fruit rich in vitamin C and flavonoids, commonly juiced or zested.",
    commonForms: ["whole", "juiced", "zested"],
    storageGuidance: "Keep at room temperature for a week or refrigerate for longer.",
    seasonality: "Year-round (imported)" },
  { slug: "pomegranate", name: "Pomegranate", category: "Fruit",
    subcategory: "Exotic fruit", aliases: ["pomegranates", "pomegranate seeds", "pomegranate arils"],
    description: "A jewel-like fruit with seeds rich in anthocyanins, polyphenols and vitamin C.",
    commonForms: ["seeds (arils)", "juice", "in salads", "in yoghurt"],
    storageGuidance: "Keep whole at room temperature for up to a week; refrigerate seeds.",
    seasonality: "Autumn to winter" },
  { slug: "peach", name: "Peach", category: "Fruit",
    subcategory: "Stone fruit", aliases: ["peaches", "white peach", "yellow peach"],
    description: "A sweet stone fruit supplying beta-carotene, vitamin C and fibre, with higher nutrients in the skin.",
    commonForms: ["whole", "sliced", "grilled", "tinned", "in crumbles"],
    storageGuidance: "Ripen at room temperature; refrigerate once ripe.",
    seasonality: "Summer" },
  { slug: "plum", name: "Plum", category: "Fruit",
    subcategory: "Stone fruit", aliases: ["plums", "victoria plum", "damson"],
    description: "A sweet-tart stone fruit rich in fibre, vitamin C and potassium, with purple-red varieties also supplying anthocyanins.",
    commonForms: ["whole", "stewed", "in jams", "in crumbles"],
    storageGuidance: "Ripen at room temperature; refrigerate once ripe.",
    seasonality: "Summer to early autumn" },
  { slug: "cherry", name: "Cherries", category: "Fruit",
    subcategory: "Stone fruit", aliases: ["cherry", "sweet cherry", "morello cherry"],
    description: "Small stone fruits rich in anthocyanins, flavonoids and vitamin C; associated with a varied, plant-rich diet.",
    commonForms: ["fresh", "frozen", "tinned", "in desserts"],
    storageGuidance: "Refrigerate and eat within a few days.",
    seasonality: "Summer" },
  { slug: "nectarine", name: "Nectarine", category: "Fruit",
    subcategory: "Stone fruit", aliases: ["nectarines"],
    description: "A smooth-skinned stone fruit closely related to the peach, supplying beta-carotene, vitamin C and fibre.",
    commonForms: ["whole", "sliced", "grilled", "in fruit salads"],
    storageGuidance: "Ripen at room temperature; refrigerate once ripe.",
    seasonality: "Summer" },
  { slug: "watermelon", name: "Watermelon", category: "Fruit",
    subcategory: "Melon", aliases: ["water melon"],
    description: "A refreshing fruit with high water content, supplying lycopene, potassium and vitamin C.",
    commonForms: ["sliced", "cubed", "in salads", "juiced"],
    storageGuidance: "Keep whole at room temperature; refrigerate once cut.",
    seasonality: "Summer (imported year-round)" },
  { slug: "pineapple", name: "Pineapple", category: "Fruit",
    subcategory: "Tropical fruit", aliases: ["pineapples"],
    description: "A tropical fruit rich in vitamin C, manganese and fibre, with a naturally sweet and tangy flavour.",
    commonForms: ["fresh", "tinned", "in smoothies", "grilled"],
    storageGuidance: "Ripen at room temperature; refrigerate once cut.",
    seasonality: "Year-round (imported)" },
  { slug: "fig", name: "Figs", category: "Fruit",
    subcategory: "Exotic fruit", aliases: ["fig", "dried figs", "fresh figs"],
    description: "A soft, sweet fruit rich in fibre, calcium and potassium; enjoyed fresh in summer or dried year-round.",
    commonForms: ["fresh", "dried", "in salads", "with cheese"],
    storageGuidance: "Refrigerate fresh figs; dried figs keep in an airtight jar.",
    seasonality: "Summer to autumn (dried year-round)" },
  { slug: "apricot", name: "Apricot", category: "Fruit",
    subcategory: "Stone fruit", aliases: ["apricots", "dried apricots"],
    description: "A golden stone fruit rich in beta-carotene, vitamin C and fibre; dried apricots are especially concentrated in iron.",
    commonForms: ["fresh", "dried", "tinned", "in tagines"],
    storageGuidance: "Ripen at room temperature; refrigerate once ripe.",
    seasonality: "Summer (dried year-round)" },
  { slug: "passion-fruit", name: "Passion Fruit", category: "Fruit",
    subcategory: "Exotic fruit", aliases: ["passionfruit", "granadilla"],
    description: "A tropical fruit with aromatic, seedy pulp rich in fibre, vitamin C and potassium.",
    commonForms: ["halved and scooped", "in desserts", "in dressings"],
    storageGuidance: "Ripen at room temperature until wrinkled; refrigerate once ripe.",
    seasonality: "Year-round (imported)" },
  { slug: "blackberry", name: "Blackberries", category: "Fruit",
    subcategory: "Berries", aliases: ["blackberry", "bramble"],
    description: "Deep purple wild and cultivated berries rich in anthocyanins, fibre and vitamin C.",
    commonForms: ["fresh", "frozen", "in crumbles", "in smoothies"],
    storageGuidance: "Refrigerate and eat within a couple of days; frozen works well year-round.",
    seasonality: "Late summer to early autumn (frozen year-round)" },
  { slug: "melon", name: "Melon", category: "Fruit",
    subcategory: "Melon", aliases: ["honeydew melon", "cantaloupe", "galia melon", "charentais"],
    description: "A refreshing fruit with high water content; cantaloupe and galia are particularly rich in beta-carotene.",
    commonForms: ["sliced", "cubed", "in fruit salads"],
    storageGuidance: "Ripen at room temperature; refrigerate once cut.",
    seasonality: "Summer (imported year-round)" },
  { slug: "cranberry", name: "Cranberries", category: "Fruit",
    subcategory: "Berries", aliases: ["cranberry", "dried cranberries"],
    description: "Tart red berries rich in flavonoids, vitamin C and fibre; commonly dried or juiced for everyday use.",
    commonForms: ["dried", "juice", "sauce", "in baking"],
    storageGuidance: "Refrigerate fresh; dried cranberries keep in an airtight container.",
    seasonality: "Autumn (dried and juice year-round)" },
  { slug: "blackcurrant", name: "Blackcurrants", category: "Fruit",
    subcategory: "Berries", aliases: ["blackcurrant", "black currant"],
    description: "Small, intensely flavoured berries with one of the highest vitamin C contents of any commonly eaten fruit, plus anthocyanins.",
    commonForms: ["fresh", "frozen", "juice", "jam", "in desserts"],
    storageGuidance: "Refrigerate and use within a few days; freeze well.",
    seasonality: "Summer (frozen and juice year-round)" },
  { slug: "redcurrant", name: "Redcurrants", category: "Fruit",
    subcategory: "Berries", aliases: ["redcurrant", "red currant"],
    description: "Jewel-like tart berries rich in vitamin C and flavonoids, used in jams, jellies and as a cooking ingredient.",
    commonForms: ["fresh", "frozen", "jelly", "in desserts"],
    storageGuidance: "Refrigerate and use within a few days.",
    seasonality: "Summer" },
  { slug: "gooseberry", name: "Gooseberries", category: "Fruit",
    subcategory: "Berries", aliases: ["gooseberry"],
    description: "A tart British berry rich in vitamin C and fibre, traditionally used in crumbles, jams and fools.",
    commonForms: ["fresh", "stewed", "in crumbles", "in jams"],
    storageGuidance: "Refrigerate; best used within a few days.",
    seasonality: "Summer" },
  { slug: "raisins", name: "Raisins", category: "Fruit",
    subcategory: "Dried fruit", aliases: ["sultanas", "currants", "mixed dried fruit"],
    description: "Dried grapes concentrated in fibre, potassium and iron, useful as a portable, naturally sweet snack.",
    commonForms: ["as snack", "in baking", "in porridge", "in salads"],
    storageGuidance: "Keep in an airtight container at room temperature.",
    seasonality: "Year-round" },

  // ── Wave 5: Herbs ────────────────────────────────────────────────────────────
  { slug: "oregano", name: "Oregano", category: "Herbs",
    subcategory: "Woody herbs", aliases: ["dried oregano", "fresh oregano", "wild marjoram"],
    description: "An aromatic herb central to Mediterranean cooking, rich in protective polyphenols and a source of vitamin K.",
    commonForms: ["dried", "fresh"], storageGuidance: "Dried keeps well in a sealed jar; fresh refrigerate wrapped.", seasonality: "Year-round (fresh: summer)" },
  { slug: "dill", name: "Dill", category: "Herbs",
    subcategory: "Soft herbs", aliases: ["fresh dill", "dried dill", "dill weed"],
    description: "A feathery soft herb with a fresh, anise-like flavour, supplying vitamin C, manganese and folate.",
    commonForms: ["fresh", "dried"], storageGuidance: "Wrap fresh dill and refrigerate; use within a few days.", seasonality: "Year-round" },
  { slug: "chives", name: "Chives", category: "Herbs",
    subcategory: "Soft herbs", aliases: ["fresh chives", "garlic chives"],
    description: "A slender allium herb with a mild onion flavour, supplying vitamin K and vitamin C.",
    commonForms: ["fresh", "dried", "snipped", "in salads"], storageGuidance: "Wrap in damp paper and refrigerate; use within a few days.", seasonality: "Spring to autumn" },
  { slug: "sage", name: "Sage", category: "Herbs",
    subcategory: "Woody herbs", aliases: ["fresh sage", "dried sage"],
    description: "A robust, earthy woody herb rich in protective polyphenols and vitamin K, well suited to roasting and butter sauces.",
    commonForms: ["fresh", "dried"], storageGuidance: "Refrigerate fresh sprigs; dried keeps in a sealed jar.", seasonality: "Year-round" },
  { slug: "tarragon", name: "Tarragon", category: "Herbs",
    subcategory: "Soft herbs", aliases: ["French tarragon", "fresh tarragon"],
    description: "An aromatic herb with a distinctive anise-like flavour, widely used in French cooking and rich in polyphenols.",
    commonForms: ["fresh", "dried", "in vinegars", "in sauces"], storageGuidance: "Wrap in damp paper and refrigerate; use within a few days.", seasonality: "Spring to autumn" },
  { slug: "bay-leaf", name: "Bay Leaf", category: "Herbs",
    subcategory: "Woody herbs", aliases: ["bay leaves", "dried bay leaf", "bay laurel"],
    description: "The dried or fresh leaf of the bay laurel tree, used to add depth to stocks, soups and stews.",
    commonForms: ["dried", "fresh", "in stocks", "in slow-cooked dishes"], storageGuidance: "Dried bay leaves keep for months in a sealed jar.", seasonality: "Year-round" },
  { slug: "lemongrass", name: "Lemongrass", category: "Herbs",
    subcategory: "Stem herbs", aliases: ["lemon grass"],
    description: "A fragrant stem herb with a bright citrus flavour, rich in polyphenols and widely used in South East Asian and Thai cooking.",
    commonForms: ["fresh stalks", "paste", "dried", "in curries", "in soups"], storageGuidance: "Refrigerate fresh stalks; freeze for longer storage.", seasonality: "Year-round" },

  // ── Wave 5: Spices ───────────────────────────────────────────────────────────
  { slug: "ginger", name: "Ginger", category: "Spices",
    subcategory: "Root spices", aliases: ["fresh ginger", "ground ginger", "stem ginger"],
    description: "A pungent root spice rich in polyphenols, used fresh, dried or ground across many cuisines.",
    commonForms: ["fresh", "ground", "dried", "pickled", "stem in syrup"], storageGuidance: "Refrigerate fresh; ground and dried keep in a sealed jar.", seasonality: "Year-round" },
  { slug: "turmeric", name: "Turmeric", category: "Spices",
    subcategory: "Root spices", aliases: ["ground turmeric", "fresh turmeric"],
    description: "A golden root spice with a warm, earthy flavour, containing curcumin and other protective polyphenols.",
    commonForms: ["ground", "fresh root"], storageGuidance: "Keep ground turmeric in a sealed jar away from light.", seasonality: "Year-round" },
  { slug: "cumin", name: "Cumin", category: "Spices",
    subcategory: "Ground spices", aliases: ["ground cumin", "cumin seeds", "whole cumin"],
    description: "A warm, earthy spice used across South Asian, Middle Eastern and Mexican cooking, supplying iron and manganese.",
    commonForms: ["seeds", "ground"], storageGuidance: "Keep in a sealed jar away from heat and light.", seasonality: "Year-round" },
  { slug: "cinnamon", name: "Cinnamon", category: "Spices",
    subcategory: "Ground spices", aliases: ["ground cinnamon", "cinnamon sticks", "cassia"],
    description: "A warm, sweet spice from tree bark rich in manganese and protective polyphenols.",
    commonForms: ["ground", "sticks"], storageGuidance: "Keep in a sealed jar away from heat and light.", seasonality: "Year-round" },
  { slug: "paprika", name: "Paprika", category: "Spices",
    subcategory: "Ground spices", aliases: ["sweet paprika", "smoked paprika", "hot paprika"],
    description: "A ground red pepper spice supplying beta-carotene and vitamin A, with smoked varieties adding extra complexity.",
    commonForms: ["ground", "smoked", "sweet"], storageGuidance: "Keep in a sealed jar away from light.", seasonality: "Year-round" },
  { slug: "clementine", name: "Clementine", category: "Fruit",
    subcategory: "Citrus", aliases: ["clementines", "satsuma", "satsumas", "mandarin", "easy peelers"],
    description: "A small, easy-peel citrus fruit rich in vitamin C and folate; a popular everyday winter snack.",
    commonForms: ["whole", "segments"], storageGuidance: "Keep at room temperature for a week or refrigerate.", seasonality: "Winter" },
  { slug: "vanilla", name: "Vanilla", category: "Spices",
    subcategory: "Sweet spices", aliases: ["vanilla pods", "vanilla extract", "vanilla essence", "vanilla bean"],
    description: "A fragrant spice from orchid pods, used to add warmth and sweetness to baking and desserts.",
    commonForms: ["pods", "extract", "paste", "powder"], storageGuidance: "Keep pods in an airtight container; extract keeps in a cool, dark cupboard.", seasonality: "Year-round" },
  { slug: "chilli", name: "Chilli", category: "Spices",
    subcategory: "Chillies", aliases: ["chili", "red chilli", "green chilli", "chilli flakes", "chilli powder", "bird's eye chilli"],
    description: "A hot pepper supplying vitamin C, beta-carotene and protective polyphenols; available fresh, dried or ground.",
    commonForms: ["fresh", "dried", "flakes", "powder", "paste"], storageGuidance: "Refrigerate fresh; dried and ground keep in a sealed jar.", seasonality: "Year-round" },
  { slug: "black-pepper", name: "Black Pepper", category: "Spices",
    subcategory: "Peppercorns", aliases: ["ground black pepper", "peppercorns", "white pepper"],
    description: "The world's most widely used spice, supplying manganese and protective polyphenols from the piperine compound.",
    commonForms: ["whole peppercorns", "ground"], storageGuidance: "Keep in a sealed container; grind fresh for best flavour.", seasonality: "Year-round" },
  { slug: "cardamom", name: "Cardamom", category: "Spices",
    subcategory: "Pod spices", aliases: ["green cardamom", "ground cardamom", "cardamom pods"],
    description: "A fragrant aromatic spice from the ginger family, used across South Asian, Nordic and Middle Eastern cooking.",
    commonForms: ["pods", "ground", "seeds"], storageGuidance: "Keep pods or ground cardamom in a sealed jar away from light.", seasonality: "Year-round" },
  { slug: "star-anise", name: "Star Anise", category: "Spices",
    subcategory: "Pod spices", aliases: ["star anise pods"],
    description: "A star-shaped spice with an intense aniseed flavour, used in Chinese five-spice and many Asian and European dishes.",
    commonForms: ["whole", "ground"], storageGuidance: "Keep in a sealed jar; whole stars stay fresh for months.", seasonality: "Year-round" },
  { slug: "cloves", name: "Cloves", category: "Spices",
    subcategory: "Ground spices", aliases: ["whole cloves", "ground cloves"],
    description: "Intensely aromatic dried flower buds rich in manganese and protective polyphenols, used in both sweet and savoury cooking.",
    commonForms: ["whole", "ground"], storageGuidance: "Keep in a sealed jar away from heat and light.", seasonality: "Year-round" },
  { slug: "nutmeg", name: "Nutmeg", category: "Spices",
    subcategory: "Ground spices", aliases: ["ground nutmeg", "whole nutmeg"],
    description: "A warm, slightly sweet spice grated from a tropical tree seed, used in béchamel sauces, baking and spiced drinks.",
    commonForms: ["whole (grated)", "ground"], storageGuidance: "Keep in a sealed jar; whole nutmeg stays fresh for years.", seasonality: "Year-round" },

  // ── Wave 6: Nuts and Seeds ────────────────────────────────────────────────────
  { slug: "hazelnuts", name: "Hazelnuts", category: "Healthy fats",
    subcategory: "Nuts", aliases: ["hazelnut", "cobnuts", "filberts"],
    description: "A round tree nut rich in vitamin E, magnesium and copper, with a buttery flavour popular in baking and confectionery.",
    commonForms: ["whole", "chopped", "ground", "in spreads"], storageGuidance: "Store airtight in a cool place.", seasonality: "Autumn (dried year-round)" },
  { slug: "cashews", name: "Cashews", category: "Healthy fats",
    subcategory: "Nuts", aliases: ["cashew nut", "cashew nuts"],
    description: "A creamy tree nut supplying magnesium, copper, zinc and unsaturated fats, popular in cooking and as a snack.",
    commonForms: ["whole", "halves", "raw", "roasted", "butter"], storageGuidance: "Store airtight in a cool place.", seasonality: "Year-round" },
  { slug: "pistachios", name: "Pistachios", category: "Healthy fats",
    subcategory: "Nuts", aliases: ["pistachio nut", "pistachio nuts"],
    description: "A green tree nut rich in vitamin B6, potassium and copper, with a distinctive flavour and one of the most complete nut nutritional profiles.",
    commonForms: ["shelled", "in shells", "in desserts", "in rice dishes"], storageGuidance: "Store airtight in a cool place.", seasonality: "Year-round" },
  { slug: "brazil-nuts", name: "Brazil Nuts", category: "Healthy fats",
    subcategory: "Nuts", aliases: ["brazil nut"],
    description: "Large South American nuts and one of the richest food sources of selenium, also supplying magnesium, copper and zinc.",
    commonForms: ["whole", "chopped"], storageGuidance: "Refrigerate or freeze to prevent rancidity.", seasonality: "Year-round" },
  { slug: "pine-nuts", name: "Pine Nuts", category: "Healthy fats",
    subcategory: "Nuts", aliases: ["pine kernels", "pignoli"],
    description: "Small, soft seeds from pine trees rich in magnesium, zinc and vitamin E, the key ingredient in traditional pesto.",
    commonForms: ["whole", "toasted"], storageGuidance: "Refrigerate or freeze due to high fat content; use quickly once opened.", seasonality: "Year-round" },
  { slug: "pecans", name: "Pecans", category: "Healthy fats",
    subcategory: "Nuts", aliases: ["pecan nut", "pecan nuts"],
    description: "A rich, buttery tree nut supplying unsaturated fats, copper and manganese, with a mild sweet flavour.",
    commonForms: ["halves", "chopped", "in baking"], storageGuidance: "Store airtight in a cool place; refrigerate for longer storage.", seasonality: "Year-round" },
  { slug: "peanuts", name: "Peanuts", category: "Healthy fats",
    subcategory: "Nuts", aliases: ["groundnuts", "peanut", "monkey nuts"],
    description: "Technically a legume, peanuts are a rich source of plant protein, magnesium, vitamin E and zinc.",
    commonForms: ["whole", "roasted", "butter", "in satay sauces"], storageGuidance: "Store airtight; refrigerate peanut butter once opened.", seasonality: "Year-round" },
  { slug: "macadamia", name: "Macadamia Nuts", category: "Healthy fats",
    subcategory: "Nuts", aliases: ["macadamia nut", "macadamia nuts"],
    description: "Rich, buttery Australian tree nuts high in unsaturated fats, manganese and copper.",
    commonForms: ["whole", "halves", "roasted", "in baking"], storageGuidance: "Store airtight; refrigerate for longer freshness.", seasonality: "Year-round" },

  // ── Wave 7: Dairy and Alternatives ───────────────────────────────────────────
  { slug: "milk", name: "Milk", category: "Dairy",
    subcategory: "Cow's milk", aliases: ["whole milk", "semi-skimmed milk", "skimmed milk", "full-fat milk"],
    description: "A nutrient-dense dairy liquid supplying calcium, vitamin D, vitamin B12 and iodine.",
    commonForms: ["whole", "semi-skimmed", "skimmed", "in cooking", "in drinks"],
    storageGuidance: "Refrigerate and use before the use-by date.",
    seasonality: "Year-round" },
  { slug: "yoghurt", name: "Yoghurt", category: "Dairy",
    subcategory: "Fermented dairy", aliases: ["natural yoghurt", "plain yoghurt", "live yoghurt", "yogurt"],
    description: "A cultured dairy food supplying calcium and vitamin B12; live yoghurt also contains beneficial cultures.",
    commonForms: ["plain", "natural", "in dips", "in marinades", "with fruit"],
    storageGuidance: "Keep refrigerated and use before the use-by date.",
    seasonality: "Year-round" },
  { slug: "greek-yoghurt", name: "Greek Yoghurt", category: "Dairy",
    subcategory: "Fermented dairy", aliases: ["Greek-style yoghurt", "strained yoghurt"],
    description: "A thick, strained yoghurt with a much higher protein content than standard yoghurt, and a rich, creamy texture.",
    commonForms: ["plain", "full-fat", "low-fat", "in dips", "with honey"],
    storageGuidance: "Refrigerate and use before the use-by date.",
    seasonality: "Year-round" },
  { slug: "cheddar", name: "Cheddar", category: "Dairy",
    subcategory: "Hard cheese", aliases: ["cheddar cheese", "mature cheddar", "mild cheddar"],
    description: "A firm, tangy British cheese and an excellent source of calcium, vitamin B12 and iodine.",
    commonForms: ["block", "grated", "sliced", "mature", "mild"],
    storageGuidance: "Wrap tightly and refrigerate; hard cheese keeps well for weeks.",
    seasonality: "Year-round" },
  { slug: "mozzarella", name: "Mozzarella", category: "Dairy",
    subcategory: "Fresh cheese", aliases: ["fresh mozzarella", "buffalo mozzarella"],
    description: "A soft, mild Italian cheese supplying calcium and vitamin B12, traditionally made from buffalo or cow's milk.",
    commonForms: ["ball", "sliced", "grated", "on pizza", "in salads"],
    storageGuidance: "Keep in its liquid in the fridge; use within a day or two of opening.",
    seasonality: "Year-round" },
  { slug: "halloumi", name: "Halloumi", category: "Dairy",
    subcategory: "Semi-hard cheese", aliases: ["grilling cheese"],
    description: "A firm Cypriot cheese with a high melting point, supplying calcium and vitamin B12; best grilled or pan-fried.",
    commonForms: ["sliced", "grilled", "pan-fried", "in wraps", "in salads"],
    storageGuidance: "Keep refrigerated in its brine; freeze if not using soon.",
    seasonality: "Year-round" },
  { slug: "feta", name: "Feta", category: "Dairy",
    subcategory: "Soft cheese", aliases: ["feta cheese", "Greek cheese"],
    description: "A crumbly, tangy Greek cheese made from sheep's and goat's milk, supplying calcium and vitamin B12.",
    commonForms: ["block", "crumbled", "in salads", "in pastries"],
    storageGuidance: "Store in brine in the fridge; keeps for several weeks.",
    seasonality: "Year-round" },
  { slug: "parmesan", name: "Parmesan", category: "Dairy",
    subcategory: "Hard cheese", aliases: ["parmigiano reggiano", "parmigiano-reggiano", "grana padano"],
    description: "A hard, aged Italian cheese with an intense umami flavour, very rich in calcium, vitamin B12 and selenium.",
    commonForms: ["block", "grated", "shaved"],
    storageGuidance: "Wrap tightly and refrigerate; keeps for weeks.",
    seasonality: "Year-round" },
  { slug: "ricotta", name: "Ricotta", category: "Dairy",
    subcategory: "Fresh cheese", aliases: ["ricotta cheese"],
    description: "A soft, mild Italian whey cheese light in flavour and supplying calcium and vitamin B12.",
    commonForms: ["in pasta", "in baking", "with honey", "in lasagne"],
    storageGuidance: "Refrigerate and use within a few days of opening.",
    seasonality: "Year-round" },
  { slug: "oat-milk", name: "Oat Milk", category: "Dairy alternatives",
    subcategory: "Plant milks", aliases: ["oat drink"],
    description: "A plant-based milk made from oats, naturally supplying some fibre and manganese; commonly fortified with calcium and vitamin D.",
    commonForms: ["plain", "barista", "in coffee", "in cooking"],
    storageGuidance: "Refrigerate once opened; keep UHT versions in the cupboard.",
    seasonality: "Year-round" },
  { slug: "soy-milk", name: "Soy Milk", category: "Dairy alternatives",
    subcategory: "Plant milks", aliases: ["soya milk", "soya drink", "soy drink"],
    description: "A plant-based milk made from soybeans, naturally supplying plant protein; commonly fortified with calcium, vitamin D and vitamin B12.",
    commonForms: ["plain", "unsweetened", "in cooking", "in coffee"],
    storageGuidance: "Refrigerate once opened.",
    seasonality: "Year-round" },
  { slug: "almond-milk", name: "Almond Milk", category: "Dairy alternatives",
    subcategory: "Plant milks", aliases: ["almond drink"],
    description: "A plant-based milk made from almonds, naturally low in calories and supplying some vitamin E; commonly fortified with calcium and vitamin D.",
    commonForms: ["plain", "unsweetened", "in coffee", "in smoothies"],
    storageGuidance: "Refrigerate once opened.",
    seasonality: "Year-round" },
  { slug: "tofu", name: "Tofu", category: "Legumes",
    subcategory: "Soya", aliases: ["bean curd", "firm tofu", "silken tofu", "extra-firm tofu"],
    description: "A versatile soya food supplying plant protein, calcium and iron, available in firm and silken varieties.",
    commonForms: ["firm", "silken", "smoked", "marinated", "fried"],
    storageGuidance: "Keep in water in the fridge; change water daily and use within a few days of opening.",
    seasonality: "Year-round" },

  // ── Wave 8: Proteins ─────────────────────────────────────────────────────────
  { slug: "eggs", name: "Eggs", category: "Proteins",
    subcategory: "Eggs", aliases: ["egg", "hen eggs", "free-range eggs", "organic eggs"],
    description: "A complete protein food supplying vitamin D, vitamin B12, selenium and iodine, with the yolk providing most of the nutrients.",
    commonForms: ["boiled", "scrambled", "fried", "poached", "baked"],
    storageGuidance: "Store in the fridge in the UK; use within the best-before date.",
    seasonality: "Year-round" },
  { slug: "chicken", name: "Chicken", category: "Proteins",
    subcategory: "Poultry", aliases: ["chicken breast", "chicken thigh", "chicken leg", "whole chicken", "roast chicken"],
    description: "A widely eaten white meat supplying selenium, vitamin B6, zinc and vitamin B12.",
    commonForms: ["breast", "thigh", "drumstick", "whole", "mince"],
    storageGuidance: "Refrigerate and use by the use-by date; freeze for longer.",
    seasonality: "Year-round" },
  { slug: "turkey", name: "Turkey", category: "Proteins",
    subcategory: "Poultry", aliases: ["turkey breast", "turkey mince", "turkey steak"],
    description: "A lean white meat supplying selenium, vitamin B6, zinc and vitamin B12.",
    commonForms: ["breast", "mince", "escalope", "whole"],
    storageGuidance: "Refrigerate and use by the use-by date; freeze for longer.",
    seasonality: "Year-round (whole bird: Christmas season)" },
  { slug: "beef", name: "Beef", category: "Proteins",
    subcategory: "Red meat", aliases: ["beef mince", "steak", "ground beef", "minced beef"],
    description: "A red meat supplying well-absorbed iron, zinc, vitamin B12 and selenium.",
    commonForms: ["mince", "steak", "roasting joint", "slow-cook cuts"],
    storageGuidance: "Refrigerate and use by the use-by date; freeze for longer.",
    seasonality: "Year-round" },
  { slug: "lamb", name: "Lamb", category: "Proteins",
    subcategory: "Red meat", aliases: ["lamb chops", "lamb mince", "lamb leg", "mutton"],
    description: "A red meat with a distinctive flavour, supplying iron, zinc and vitamin B12.",
    commonForms: ["chops", "mince", "leg", "shoulder", "rack"],
    storageGuidance: "Refrigerate and use by the use-by date; freeze for longer.",
    seasonality: "Year-round (British lamb: spring to autumn)" },
  { slug: "pork", name: "Pork", category: "Proteins",
    subcategory: "White meat", aliases: ["pork chops", "pork loin", "pork belly", "pork mince"],
    description: "A versatile white meat supplying vitamin B6, vitamin B12, selenium and zinc.",
    commonForms: ["chops", "loin", "belly", "mince", "tenderloin"],
    storageGuidance: "Refrigerate and use by the use-by date; freeze for longer.",
    seasonality: "Year-round" },
  { slug: "duck", name: "Duck", category: "Proteins",
    subcategory: "Poultry", aliases: ["duck breast", "duck leg", "whole duck"],
    description: "A rich, dark poultry meat supplying iron, zinc and vitamin B12.",
    commonForms: ["breast", "leg", "whole", "confit"],
    storageGuidance: "Refrigerate and use by the use-by date; freeze for longer.",
    seasonality: "Year-round (autumn and winter for game duck)" },
  { slug: "tuna", name: "Tuna", category: "Healthy fats",
    subcategory: "Oily fish", aliases: ["tinned tuna", "tuna steak", "yellowfin tuna", "albacore"],
    description: "An oily fish supplying omega-3 fats, selenium and vitamin D; tinned tuna is an affordable and convenient everyday option.",
    commonForms: ["tinned", "steak", "seared"],
    storageGuidance: "Tins keep in the cupboard; refrigerate once opened.",
    seasonality: "Year-round" },
  { slug: "mackerel", name: "Mackerel", category: "Healthy fats",
    subcategory: "Oily fish", aliases: ["smoked mackerel", "Atlantic mackerel", "mackerel fillet"],
    description: "A rich, flavourful oily fish and one of the best dietary sources of omega-3 fats, vitamin D and vitamin B12.",
    commonForms: ["smoked", "fresh fillet", "tinned", "pâté"],
    storageGuidance: "Refrigerate and use within use-by date; smoked keeps longer.",
    seasonality: "Year-round (freshest in summer to autumn)" },
  { slug: "cod", name: "Cod", category: "Proteins",
    subcategory: "White fish", aliases: ["cod fillet", "salt cod", "cod loin"],
    description: "A mild-flavoured white fish supplying selenium, vitamin B12 and iodine, and a lean source of quality protein.",
    commonForms: ["fillet", "loin", "battered", "in fish pie"],
    storageGuidance: "Refrigerate and use by the use-by date; freeze for longer.",
    seasonality: "Year-round" },
  { slug: "haddock", name: "Haddock", category: "Proteins",
    subcategory: "White fish", aliases: ["smoked haddock", "haddock fillet"],
    description: "A firm white fish with a slightly sweet flavour, supplying selenium, vitamin B12 and iodine.",
    commonForms: ["fresh fillet", "smoked", "in fish pie", "in chowder"],
    storageGuidance: "Refrigerate and use by the use-by date; freeze for longer.",
    seasonality: "Year-round" },
  { slug: "anchovies", name: "Anchovies", category: "Healthy fats",
    subcategory: "Oily fish", aliases: ["anchovy", "tinned anchovies", "salted anchovies"],
    description: "Small, intensely flavoured oily fish supplying omega-3 fats, calcium and vitamin D; used to add depth to sauces and dressings.",
    commonForms: ["tinned in oil", "salted", "in sauces", "on pizza"],
    storageGuidance: "Tins keep in the cupboard; refrigerate in oil once opened.",
    seasonality: "Year-round (tinned)" },
  { slug: "prawns", name: "Prawns", category: "Proteins",
    subcategory: "Shellfish", aliases: ["shrimp", "king prawns", "tiger prawns", "cooked prawns"],
    description: "A lean shellfish supplying selenium, zinc, iodine and vitamin B12, popular in both hot dishes and cold salads.",
    commonForms: ["raw", "cooked", "frozen", "king", "tiger"],
    storageGuidance: "Keep frozen; refrigerate cooked prawns and use within two days.",
    seasonality: "Year-round" },

  // ── Grains & Cereals ─────────────────────────────────────────────────────────
  { slug: "oats", name: "Oats", category: "Grains",
    subcategory: "Whole grains", aliases: ["porridge oats", "rolled oats", "oat flakes", "jumbo oats", "pinhead oats"],
    description: "A whole grain rich in soluble fibre (beta-glucan), magnesium and iron, widely associated with heart health and sustained energy.",
    commonForms: ["rolled", "jumbo", "steel-cut", "oat flour", "porridge"],
    storageGuidance: "Store in an airtight container in a cool, dry place.",
    seasonality: "Year-round" },
  { slug: "brown-rice", name: "Brown Rice", category: "Grains",
    subcategory: "Whole grains", aliases: ["wholegrain rice", "long-grain brown rice"],
    description: "A whole grain with the bran layer intact, supplying fibre, magnesium, manganese and B vitamins.",
    commonForms: ["long-grain", "short-grain", "basmati", "cooked"],
    storageGuidance: "Store dry in an airtight container; refrigerate cooked rice and use within a day.",
    seasonality: "Year-round" },
  { slug: "white-rice", name: "White Rice", category: "Grains",
    subcategory: "Refined grains", aliases: ["basmati rice", "jasmine rice", "long-grain rice", "short-grain rice", "sushi rice"],
    description: "A refined grain with the bran removed, supplying easily digested starchy carbohydrate and, for enriched varieties, added B vitamins.",
    commonForms: ["basmati", "jasmine", "long-grain", "arborio", "cooked"],
    storageGuidance: "Store dry in an airtight container; refrigerate cooked rice and use within a day.",
    seasonality: "Year-round" },
  { slug: "quinoa", name: "Quinoa", category: "Grains",
    subcategory: "Pseudo-cereals", aliases: ["white quinoa", "red quinoa", "black quinoa"],
    description: "A seed used as a grain and one of few plant foods supplying all essential amino acids; a good source of iron, magnesium and fibre.",
    commonForms: ["white", "red", "tricolour", "puffed", "cooked"],
    storageGuidance: "Store dry in an airtight container.",
    seasonality: "Year-round" },
  { slug: "buckwheat", name: "Buckwheat", category: "Grains",
    subcategory: "Pseudo-cereals", aliases: ["buckwheat groats", "kasha", "buckwheat flour"],
    description: "A naturally gluten-free pseudo-cereal rich in fibre, magnesium and manganese, with a nutty flavour.",
    commonForms: ["groats", "flour", "noodles (soba)", "porridge"],
    storageGuidance: "Store in an airtight container.",
    seasonality: "Year-round" },
  { slug: "barley", name: "Barley", category: "Grains",
    subcategory: "Whole grains", aliases: ["pearl barley", "pot barley", "barley flakes"],
    description: "A chewy, nutty whole grain rich in soluble fibre and selenium, traditionally used in soups, stews and risotto-style dishes.",
    commonForms: ["pearl", "pot", "flakes", "in soups", "in stews"],
    storageGuidance: "Store dry in an airtight container.",
    seasonality: "Year-round" },
  { slug: "spelt", name: "Spelt", category: "Grains",
    subcategory: "Whole grains", aliases: ["spelt flour", "wholegrain spelt", "spelt pasta"],
    description: "An ancient variety of wheat with a nutty, slightly sweet flavour, supplying fibre, magnesium and iron.",
    commonForms: ["grains", "flour", "pasta", "bread"],
    storageGuidance: "Store in an airtight container.",
    seasonality: "Year-round" },
  { slug: "rye", name: "Rye", category: "Grains",
    subcategory: "Whole grains", aliases: ["rye bread", "rye flour", "dark rye"],
    description: "A dense, flavourful grain with a high fibre content and a lower glycaemic impact than most wheat products.",
    commonForms: ["bread", "crispbread", "flour", "grains"],
    storageGuidance: "Store grain and flour in an airtight container.",
    seasonality: "Year-round" },
  { slug: "wheat", name: "Wheat", category: "Grains",
    subcategory: "Whole grains", aliases: ["whole wheat", "wheat flour", "wholemeal flour", "wheat berries"],
    description: "The world's most widely grown cereal grain, supplying fibre, iron and B vitamins; whole wheat retains the most nutrition.",
    commonForms: ["flour", "berries", "wholemeal", "bread", "pasta"],
    storageGuidance: "Store flour in an airtight container.",
    seasonality: "Year-round" },
  { slug: "couscous", name: "Couscous", category: "Grains",
    subcategory: "Wheat products", aliases: ["wholewheat couscous", "giant couscous"],
    description: "Tiny steamed wheat granules that cook quickly, supplying selenium, fibre and folate; a staple of North African and Middle Eastern cooking.",
    commonForms: ["plain", "wholewheat", "giant", "Israeli couscous"],
    storageGuidance: "Store dry in an airtight container.",
    seasonality: "Year-round" },
  { slug: "bulgur-wheat", name: "Bulgur Wheat", category: "Grains",
    subcategory: "Wheat products", aliases: ["bulgur", "bulgar wheat", "cracked wheat"],
    description: "Pre-cooked cracked wheat with a nutty flavour, high in fibre and a good source of iron and magnesium.",
    commonForms: ["fine", "coarse", "in tabbouleh", "in pilafs"],
    storageGuidance: "Store in an airtight container.",
    seasonality: "Year-round" },
  { slug: "pasta", name: "Pasta", category: "Grains",
    subcategory: "Wheat products", aliases: ["spaghetti", "penne", "fusilli", "tagliatelle", "wholemeal pasta", "whole wheat pasta"],
    description: "A versatile wheat-based staple; wholemeal or whole wheat pasta adds significantly more fibre than refined white pasta.",
    commonForms: ["spaghetti", "penne", "fusilli", "tagliatelle", "lasagne sheets"],
    storageGuidance: "Store dried pasta in a sealed container; refrigerate fresh pasta.",
    seasonality: "Year-round" },
  { slug: "millet", name: "Millet", category: "Grains",
    subcategory: "Whole grains", aliases: ["millet flakes", "millet flour"],
    description: "A small gluten-free grain supplying magnesium, iron and fibre, with a mild, slightly sweet flavour.",
    commonForms: ["grain", "flakes", "flour", "puffed"],
    storageGuidance: "Store in an airtight container in a cool, dry place.",
    seasonality: "Year-round" },
  { slug: "freekeh", name: "Freekeh", category: "Grains",
    subcategory: "Wheat products", aliases: ["freekah", "farik"],
    description: "Roasted green durum wheat with a smoky, nutty flavour and notably high fibre and iron content.",
    commonForms: ["cracked", "whole grain", "in salads", "in pilafs"],
    storageGuidance: "Store in an airtight container.",
    seasonality: "Year-round" },

  // ── Other pantry staples ─────────────────────────────────────────────────────
  { slug: "coconut", name: "Coconut", category: "Healthy fats",
    subcategory: "Tropical nuts", aliases: ["coconut flesh", "desiccated coconut", "coconut milk", "coconut cream", "coconut water"],
    description: "A tropical drupe with fibre-rich flesh and a rich, distinctive flavour; coconut milk and cream are made from the pressed flesh.",
    commonForms: ["desiccated", "coconut milk", "coconut cream", "coconut water", "flakes"],
    storageGuidance: "Store desiccated coconut airtight; refrigerate opened coconut milk.",
    seasonality: "Year-round" },
  { slug: "dates", name: "Dates", category: "Fruit",
    subcategory: "Dried fruit", aliases: ["medjool dates", "dried dates", "deglet nour"],
    description: "A naturally sweet dried fruit rich in fibre, potassium and iron, and a useful natural sweetener in cooking and baking.",
    commonForms: ["whole", "pitted", "chopped", "in energy balls", "in baking"],
    storageGuidance: "Keep in an airtight container; refrigerate for longer freshness.",
    seasonality: "Year-round" },
  { slug: "dark-chocolate", name: "Dark Chocolate", category: "Healthy fats",
    subcategory: "Cacao", aliases: ["70% chocolate", "85% chocolate", "cocoa", "cacao", "dark choc"],
    description: "Dark chocolate (70%+ cocoa) is rich in polyphenols, magnesium and iron from the cacao plant.",
    commonForms: ["bar", "chips", "melted", "cocoa powder"],
    storageGuidance: "Keep in a cool, dry place away from strong odours.",
    seasonality: "Year-round" },
  { slug: "butter", name: "Butter", category: "Dairy",
    subcategory: "Dairy fats", aliases: ["unsalted butter", "salted butter", "block butter"],
    description: "A dairy fat made from churned cream, supplying fat-soluble vitamins A and D.",
    commonForms: ["block", "spreadable", "clarified (ghee)", "in baking", "in cooking"],
    storageGuidance: "Refrigerate; salted butter keeps longer than unsalted.",
    seasonality: "Year-round" },
  { slug: "sunflower-oil", name: "Sunflower Oil", category: "Healthy fats",
    subcategory: "Oils", aliases: ["sunflower cooking oil"],
    description: "A light, neutral vegetable oil supplying vitamin E and unsaturated fats, widely used for frying and baking.",
    commonForms: ["bottle", "in cooking", "in baking"],
    storageGuidance: "Keep in a cool, dark cupboard away from heat.",
    seasonality: "Year-round" },
];
