// WS0 — Nutrition Knowledge Registry: relationship seed data.
//
// Authored in a compact, human-editable map form (slug → [slugs]). Array order
// is meaningful: it becomes the `ranking` (0 = most prominent) when expanded
// into rows by the seed runner. Every association here is editorial and
// deterministic — conservative, well-established links only, no medical claims.
//
// Evidence strength for food↔benefit and nutrient↔benefit links is STORED ONLY
// and must not be surfaced to users yet (see registry helpers).

// ── Food → Nutrients it notably contributes ─────────────────────────────────
export const FOOD_NUTRIENTS: Record<string, string[]> = {
  // Healthy fats
  "extra-virgin-olive-oil": ["unsaturated-fats", "polyphenols", "vitamin-e"],
  "avocado": ["unsaturated-fats", "fibre", "potassium", "vitamin-e"],
  "walnuts": ["omega-3", "unsaturated-fats", "plant-protein", "magnesium"],
  "almonds": ["vitamin-e", "magnesium", "plant-protein", "unsaturated-fats"],
  "salmon": ["omega-3", "vitamin-d", "vitamin-b12", "selenium"],
  "sardines": ["omega-3", "calcium", "vitamin-d", "vitamin-b12"],
  // Seeds
  "pumpkin-seeds": ["magnesium", "zinc", "plant-protein", "iron"],
  "sunflower-seeds": ["vitamin-e", "selenium", "magnesium", "unsaturated-fats"],
  "chia-seeds": ["fibre", "omega-3", "calcium", "plant-protein"],
  "flaxseed": ["omega-3", "fibre", "plant-protein"],
  "sesame-seeds": ["calcium", "copper", "unsaturated-fats"],
  "hemp-seeds": ["plant-protein", "magnesium", "omega-3"],
  // Legumes
  "butter-beans": ["fibre", "plant-protein", "potassium", "iron"],
  "chickpeas": ["fibre", "plant-protein", "folate", "iron"],
  "red-lentils": ["plant-protein", "fibre", "iron", "folate"],
  "black-beans": ["fibre", "plant-protein", "anthocyanins", "folate"],
  "kidney-beans": ["fibre", "plant-protein", "iron"],
  "edamame": ["plant-protein", "folate", "fibre", "vitamin-k"],
  "garden-peas": ["fibre", "plant-protein", "vitamin-c", "vitamin-k"],
  // Fermented foods
  "kimchi": ["live-cultures", "fibre", "vitamin-c"],
  "sauerkraut": ["live-cultures", "fibre", "vitamin-c"],
  "kefir": ["live-cultures", "calcium", "plant-protein", "vitamin-b12"],
  "live-yogurt": ["live-cultures", "calcium", "vitamin-b12"],
  "miso": ["live-cultures", "plant-protein"],
  "tempeh": ["plant-protein", "live-cultures", "magnesium"],
  // Herbs
  "parsley": ["vitamin-k", "vitamin-c", "beta-carotene"],
  "basil": ["polyphenols", "vitamin-k"],
  "coriander": ["polyphenols", "vitamin-c"],
  "mint": ["polyphenols", "vitamin-a"],
  "rosemary": ["polyphenols"],
  "thyme": ["polyphenols", "vitamin-c"],
  // Mushrooms
  "white-mushrooms": ["vitamin-d", "selenium", "copper", "fibre"],
  "chestnut-mushrooms": ["selenium", "copper", "fibre"],
  "shiitake-mushrooms": ["copper", "selenium", "fibre"],
  "oyster-mushrooms": ["fibre", "vitamin-b6"],
  // Vegetables
  "kale": ["vitamin-k", "vitamin-c", "sulforaphane", "beta-carotene"],
  "spinach": ["folate", "iron", "vitamin-k", "beta-carotene"],
  "broccoli": ["vitamin-c", "sulforaphane", "folate", "fibre"],
  "tomatoes": ["lycopene", "vitamin-c", "potassium"],
  "sweet-potato": ["beta-carotene", "fibre", "potassium", "vitamin-c"],
  "red-pepper": ["vitamin-c", "beta-carotene", "vitamin-a"],
  "carrots": ["beta-carotene", "vitamin-a", "fibre"],
  "beetroot": ["nitrates", "folate", "anthocyanins"],
  "garlic": ["allicin", "manganese"],
  "onion": ["flavonoids", "fibre", "vitamin-c"],
  // Fruit
  "blueberries": ["anthocyanins", "polyphenols", "fibre", "vitamin-c"],
  "strawberries": ["vitamin-c", "flavonoids", "fibre"],
  "apples": ["fibre", "flavonoids", "vitamin-c"],
  "bananas": ["potassium", "vitamin-b6", "fibre"],
  "oranges": ["vitamin-c", "folate", "fibre"],
  "kiwi": ["vitamin-c", "fibre", "potassium"],
};

// ── Food → Health benefits it supports ──────────────────────────────────────
export const FOOD_BENEFITS: Record<string, string[]> = {
  "extra-virgin-olive-oil": ["heart-health", "anti-inflammatory-support", "brain-health"],
  "avocado": ["heart-health", "skin-health", "digestive-comfort"],
  "walnuts": ["brain-health", "heart-health", "mood-support"],
  "almonds": ["heart-health", "bone-health", "skin-health"],
  "salmon": ["heart-health", "brain-health", "mood-support"],
  "sardines": ["heart-health", "bone-health", "brain-health"],
  "pumpkin-seeds": ["sleep-quality", "heart-health", "immune-support"],
  "sunflower-seeds": ["skin-health", "immune-support", "heart-health"],
  "chia-seeds": ["gut-health", "heart-health", "blood-sugar-balance"],
  "flaxseed": ["gut-health", "heart-health", "digestive-comfort"],
  "sesame-seeds": ["bone-health", "heart-health"],
  "hemp-seeds": ["muscle-recovery", "heart-health"],
  "butter-beans": ["gut-health", "blood-sugar-balance", "heart-health"],
  "chickpeas": ["gut-health", "blood-sugar-balance", "muscle-recovery"],
  "red-lentils": ["gut-health", "energy-support", "muscle-recovery"],
  "black-beans": ["gut-health", "heart-health", "blood-sugar-balance"],
  "kidney-beans": ["gut-health", "blood-sugar-balance", "energy-support"],
  "edamame": ["muscle-recovery", "bone-health", "heart-health"],
  "garden-peas": ["gut-health", "immune-support"],
  "kimchi": ["gut-health", "digestive-comfort", "immune-support"],
  "sauerkraut": ["gut-health", "digestive-comfort", "immune-support"],
  "kefir": ["gut-health", "bone-health", "digestive-comfort"],
  "live-yogurt": ["gut-health", "bone-health", "digestive-comfort"],
  "miso": ["gut-health", "digestive-comfort"],
  "tempeh": ["gut-health", "muscle-recovery", "heart-health"],
  "parsley": ["bone-health", "immune-support"],
  "basil": ["anti-inflammatory-support", "heart-health"],
  "coriander": ["digestive-comfort", "anti-inflammatory-support"],
  "mint": ["digestive-comfort"],
  "rosemary": ["anti-inflammatory-support", "brain-health"],
  "thyme": ["immune-support", "anti-inflammatory-support"],
  "white-mushrooms": ["immune-support", "bone-health"],
  "chestnut-mushrooms": ["immune-support", "heart-health"],
  "shiitake-mushrooms": ["immune-support", "heart-health"],
  "oyster-mushrooms": ["immune-support", "heart-health"],
  "kale": ["bone-health", "eye-health", "anti-inflammatory-support", "healthy-ageing"],
  "spinach": ["eye-health", "energy-support", "bone-health"],
  "broccoli": ["immune-support", "anti-inflammatory-support", "healthy-ageing"],
  "tomatoes": ["heart-health", "skin-health", "healthy-ageing"],
  "sweet-potato": ["eye-health", "immune-support", "gut-health"],
  "red-pepper": ["immune-support", "skin-health", "eye-health"],
  "carrots": ["eye-health", "skin-health", "immune-support"],
  "beetroot": ["heart-health", "energy-support"],
  "garlic": ["immune-support", "heart-health", "anti-inflammatory-support"],
  "onion": ["gut-health", "heart-health"],
  "blueberries": ["brain-health", "heart-health", "healthy-ageing"],
  "strawberries": ["immune-support", "skin-health", "heart-health"],
  "apples": ["gut-health", "heart-health", "blood-sugar-balance"],
  "bananas": ["energy-support", "muscle-recovery", "gut-health"],
  "oranges": ["immune-support", "skin-health", "heart-health"],
  "kiwi": ["immune-support", "digestive-comfort", "skin-health"],
};

// ── Nutrient → Health benefits it supports ──────────────────────────────────
export const NUTRIENT_BENEFITS: Record<string, string[]> = {
  "fibre": ["gut-health", "blood-sugar-balance", "digestive-comfort", "heart-health"],
  "plant-protein": ["muscle-recovery", "energy-support"],
  "unsaturated-fats": ["heart-health", "brain-health"],
  "omega-3": ["heart-health", "brain-health", "mood-support", "anti-inflammatory-support"],
  "magnesium": ["sleep-quality", "muscle-recovery", "bone-health", "mood-support"],
  "zinc": ["immune-support", "skin-health"],
  "iron": ["energy-support"],
  "calcium": ["bone-health"],
  "potassium": ["heart-health", "muscle-recovery"],
  "selenium": ["immune-support", "anti-inflammatory-support"],
  "manganese": ["bone-health"],
  "copper": ["energy-support", "immune-support"],
  "iodine": ["energy-support"],
  "vitamin-c": ["immune-support", "skin-health", "energy-support"],
  "vitamin-d": ["bone-health", "immune-support", "mood-support"],
  "vitamin-e": ["skin-health", "healthy-ageing"],
  "vitamin-k": ["bone-health"],
  "vitamin-a": ["eye-health", "immune-support", "skin-health"],
  "beta-carotene": ["eye-health", "skin-health", "healthy-ageing"],
  "folate": ["energy-support", "healthy-ageing"],
  "vitamin-b6": ["energy-support", "mood-support"],
  "vitamin-b12": ["energy-support", "brain-health"],
  "polyphenols": ["heart-health", "healthy-ageing", "anti-inflammatory-support"],
  "flavonoids": ["heart-health", "brain-health"],
  "anthocyanins": ["brain-health", "heart-health", "healthy-ageing"],
  "lycopene": ["heart-health", "skin-health"],
  "sulforaphane": ["anti-inflammatory-support", "healthy-ageing"],
  "allicin": ["immune-support", "heart-health"],
  "nitrates": ["heart-health", "energy-support"],
  "live-cultures": ["gut-health", "digestive-comfort", "immune-support"],
};
