// WS0 — Nutrition Knowledge Registry: relationship seed data.
//
// Authored in a compact, human-editable map form (slug → [slugs]). Array order
// is meaningful: it becomes the `ranking` (0 = most prominent) when expanded
// into rows by the seed runner. Every association here is editorial and
// deterministic — conservative, well-established links only, no medical claims.
//
// Evidence strength for food↔benefit and nutrient↔benefit links is STORED ONLY
// and must not be surfaced to users yet (see registry helpers).

// ── Food → Nutrients it notably contributes ─────────────────────────────────
export const FOOD_NUTRIENTS: Record<string, string[]> = {
  // Healthy fats
  "extra-virgin-olive-oil": ["unsaturated-fats", "polyphenols", "vitamin-e"],
  "avocado": ["unsaturated-fats", "fibre", "potassium", "vitamin-e"],
  "walnuts": ["omega-3", "unsaturated-fats", "plant-protein", "magnesium"],
  "almonds": ["vitamin-e", "magnesium", "plant-protein", "unsaturated-fats"],
  "salmon": ["omega-3", "vitamin-d", "vitamin-b12", "selenium"],
  "sardines": ["omega-3", "calcium", "vitamin-d", "vitamin-b12"],
  // Seeds
  "pumpkin-seeds": ["magnesium", "zinc", "plant-protein", "iron"],
  "sunflower-seeds": ["vitamin-e", "selenium", "magnesium", "unsaturated-fats"],
  "chia-seeds": ["fibre", "omega-3", "calcium", "plant-protein"],
  "flaxseed": ["omega-3", "fibre", "plant-protein"],
  "sesame-seeds": ["calcium", "copper", "unsaturated-fats"],
  "hemp-seeds": ["plant-protein", "magnesium", "omega-3"],
  // Legumes
  "butter-beans": ["fibre", "plant-protein", "potassium", "iron"],
  "chickpeas": ["fibre", "plant-protein", "folate", "iron"],
  "red-lentils": ["plant-protein", "fibre", "iron", "folate"],
  "black-beans": ["fibre", "plant-protein", "anthocyanins", "folate"],
  "kidney-beans": ["fibre", "plant-protein", "iron"],
  "edamame": ["plant-protein", "folate", "fibre", "vitamin-k"],
  "garden-peas": ["fibre", "plant-protein", "vitamin-c", "vitamin-k"],
  // Fermented foods
  "kimchi": ["live-cultures", "fibre", "vitamin-c"],
  "sauerkraut": ["live-cultures", "fibre", "vitamin-c"],
  "kefir": ["live-cultures", "calcium", "plant-protein", "vitamin-b12"],
  "miso": ["live-cultures", "plant-protein"],
  "tempeh": ["plant-protein", "live-cultures", "magnesium"],
  // Herbs
  "parsley": ["vitamin-k", "vitamin-c", "beta-carotene"],
  "basil": ["polyphenols", "vitamin-k"],
  "coriander": ["polyphenols", "vitamin-c"],
  "mint": ["polyphenols", "vitamin-a"],
  "rosemary": ["polyphenols"],
  "thyme": ["polyphenols", "vitamin-c"],
  // Mushrooms
  "white-mushrooms": ["vitamin-d", "selenium", "copper", "fibre"],
  "chestnut-mushrooms": ["selenium", "copper", "fibre"],
  "shiitake-mushrooms": ["copper", "selenium", "fibre"],
  "oyster-mushrooms": ["fibre", "vitamin-b6"],
  // Vegetables
  "kale": ["vitamin-k", "vitamin-c", "sulforaphane", "beta-carotene"],
  "spinach": ["folate", "iron", "vitamin-k", "beta-carotene"],
  "broccoli": ["vitamin-c", "sulforaphane", "folate", "fibre"],
  "tomatoes": ["lycopene", "vitamin-c", "potassium"],
  "sweet-potato": ["beta-carotene", "fibre", "potassium", "vitamin-c"],
  "red-pepper": ["vitamin-c", "beta-carotene", "vitamin-a"],
  "carrots": ["beta-carotene", "vitamin-a", "fibre"],
  "beetroot": ["nitrates", "folate", "anthocyanins"],
  "garlic": ["allicin", "manganese", "vitamin-b6", "vitamin-c"], // FI1: added well-established B6/vitamin-C links (allicin stays the signature, rank 0)
  "onion": ["flavonoids", "fibre", "vitamin-c"],
  // Fruit
  "blueberries": ["anthocyanins", "polyphenols", "fibre", "vitamin-c"],
  "strawberries": ["vitamin-c", "flavonoids", "fibre"],
  "apples": ["fibre", "flavonoids", "vitamin-c"],
  "bananas": ["potassium", "vitamin-b6", "fibre"],
  "oranges": ["vitamin-c", "folate", "fibre"],
  "kiwi": ["vitamin-c", "fibre", "potassium"],
  // Mediterranean Vegetables (WS0.6)
  "watercress": ["vitamin-k", "vitamin-c", "beta-carotene", "calcium"],
  "rocket": ["vitamin-k", "folate", "vitamin-c", "calcium"],
  "parsnip": ["fibre", "folate", "potassium", "vitamin-c"],
  "turnip": ["vitamin-c", "fibre", "folate"],
  "swede": ["vitamin-c", "fibre", "potassium"],
  "red-cabbage": ["anthocyanins", "vitamin-c", "fibre", "vitamin-k"],
  "pak-choi": ["vitamin-k", "vitamin-c", "beta-carotene", "calcium"],
  "spring-onion": ["vitamin-k", "vitamin-c", "folate"],
  "aubergine": ["fibre", "polyphenols", "manganese"],
  "courgette": ["vitamin-c", "vitamin-b6", "potassium", "fibre"],
  "cucumber": ["vitamin-k", "potassium", "vitamin-c"],
  "fennel": ["fibre", "potassium", "vitamin-c", "folate"],
  "celery": ["vitamin-k", "potassium", "fibre", "folate"],
  "asparagus": ["folate", "vitamin-k", "fibre", "vitamin-c"],
  "artichoke": ["fibre", "folate", "vitamin-c", "magnesium"],
  "broad-beans": ["plant-protein", "fibre", "folate", "iron"],
  "radicchio": ["anthocyanins", "vitamin-k", "fibre", "folate"],
  "chicory": ["fibre", "vitamin-k", "folate", "vitamin-c"],

  // ── WS0.8 — Wave 1: Pantry Essentials ──────────────────────────────────────
  "potato": ["potassium", "vitamin-c", "vitamin-b6", "fibre"],
  "leek": ["folate", "vitamin-k", "vitamin-c", "manganese"],
  "shallot": ["flavonoids", "folate", "allicin", "vitamin-c"],
  "cauliflower": ["vitamin-c", "vitamin-k", "folate", "fibre"],
  "cabbage": ["vitamin-c", "vitamin-k", "fibre", "folate"],
  "butternut-squash": ["beta-carotene", "vitamin-c", "potassium", "fibre"],
  "pumpkin": ["beta-carotene", "vitamin-c", "potassium", "fibre"],
  "brussels-sprouts": ["vitamin-c", "vitamin-k", "sulforaphane", "folate"],
  "celeriac": ["vitamin-c", "vitamin-k", "fibre", "potassium"],
  "green-beans": ["vitamin-c", "vitamin-k", "folate", "fibre"],
  "radish": ["vitamin-c", "folate", "fibre"],
  "kohlrabi": ["vitamin-c", "fibre", "potassium"],
  "corn": ["fibre", "folate", "vitamin-c", "magnesium"],
  // ── WS0.8 — Wave 2: Mediterranean Vegetables ───────────────────────────────
  "lettuce": ["vitamin-k", "folate", "vitamin-c", "beta-carotene"],
  "olives": ["unsaturated-fats", "vitamin-e", "polyphenols"],
  "chard": ["vitamin-k", "vitamin-c", "magnesium", "beta-carotene"],
  "jerusalem-artichoke": ["fibre", "potassium", "iron"],
  // ── WS0.8 — Wave 3: Beans, Pulses and Legumes ──────────────────────────────
  "cannellini-beans": ["fibre", "plant-protein", "folate", "iron"],
  "borlotti-beans": ["fibre", "plant-protein", "iron", "folate"],
  "haricot-beans": ["fibre", "plant-protein", "folate", "iron"],
  "green-lentils": ["plant-protein", "fibre", "iron", "folate"],
  "puy-lentils": ["plant-protein", "fibre", "iron", "folate"],
  "beluga-lentils": ["plant-protein", "fibre", "iron", "anthocyanins"],
  // ── WS0.8 — Wave 4: Fruit ──────────────────────────────────────────────────
  "raspberry": ["fibre", "vitamin-c", "flavonoids", "folate"],
  "pear": ["fibre", "vitamin-c", "flavonoids", "potassium"],
  "mango": ["beta-carotene", "vitamin-c", "folate", "fibre"],
  "grape": ["flavonoids", "polyphenols", "potassium", "vitamin-c"],
  "lemon": ["vitamin-c", "flavonoids", "folate"],
  "lime": ["vitamin-c", "flavonoids", "folate"],
  "pomegranate": ["anthocyanins", "polyphenols", "vitamin-c", "folate"],
  "peach": ["beta-carotene", "vitamin-c", "fibre", "potassium"],
  "plum": ["vitamin-c", "fibre", "potassium", "flavonoids"],
  "cherry": ["anthocyanins", "flavonoids", "vitamin-c", "potassium"],
  "nectarine": ["beta-carotene", "vitamin-c", "fibre", "potassium"],
  "watermelon": ["lycopene", "vitamin-c", "potassium", "beta-carotene"],
  "pineapple": ["vitamin-c", "manganese", "fibre", "folate"],
  "fig": ["fibre", "calcium", "potassium", "iron"],
  "apricot": ["beta-carotene", "vitamin-c", "fibre", "potassium"],
  "passion-fruit": ["fibre", "vitamin-c", "potassium", "vitamin-a"],
  "blackberry": ["anthocyanins", "vitamin-c", "fibre", "folate"],
  "melon": ["beta-carotene", "vitamin-c", "potassium", "folate"],
  "cranberry": ["flavonoids", "vitamin-c", "fibre"],
  "blackcurrant": ["vitamin-c", "anthocyanins", "fibre", "potassium"],
  "redcurrant": ["vitamin-c", "flavonoids", "fibre"],
  "gooseberry": ["vitamin-c", "fibre", "folate"],
  "raisins": ["fibre", "potassium", "iron", "folate"],
  // ── WS0.8 — Wave 5: Herbs ──────────────────────────────────────────────────
  "oregano": ["polyphenols", "vitamin-k", "iron", "manganese"],
  "dill": ["vitamin-c", "vitamin-k", "folate", "manganese"],
  "chives": ["vitamin-k", "vitamin-c", "folate"],
  "sage": ["polyphenols", "vitamin-k", "manganese"],
  "tarragon": ["polyphenols", "vitamin-k", "manganese"],
  "bay-leaf": ["polyphenols", "vitamin-a", "manganese"],
  "lemongrass": ["polyphenols", "manganese", "iron"],
  // ── WS0.8 — Wave 5: Spices (new knowledge foods for existing canonicals) ────
  "ginger": ["polyphenols", "manganese", "magnesium"],
  "turmeric": ["polyphenols", "manganese", "iron"],
  "cumin": ["iron", "manganese", "polyphenols"],
  "cinnamon": ["manganese", "polyphenols", "calcium"],
  "paprika": ["beta-carotene", "vitamin-a", "polyphenols"],
  "clementine": ["vitamin-c", "flavonoids", "folate", "fibre"],
  "vanilla": ["polyphenols", "manganese"],
  "chilli": ["vitamin-c", "beta-carotene", "vitamin-a", "polyphenols"],
  "black-pepper": ["manganese", "iron", "polyphenols"],
  "cardamom": ["manganese", "iron", "polyphenols"],
  "star-anise": ["iron", "manganese", "polyphenols"],
  "cloves": ["manganese", "vitamin-k", "polyphenols"],
  "nutmeg": ["manganese", "copper", "polyphenols"],
  // ── WS0.8 — Wave 6: Nuts and Seeds ─────────────────────────────────────────
  "hazelnuts": ["vitamin-e", "magnesium", "copper", "unsaturated-fats"],
  "cashews": ["magnesium", "copper", "zinc", "unsaturated-fats"],
  "pistachios": ["vitamin-b6", "potassium", "copper", "plant-protein"],
  "brazil-nuts": ["selenium", "magnesium", "copper", "zinc"],
  "pine-nuts": ["magnesium", "zinc", "vitamin-e", "copper"],
  "pecans": ["unsaturated-fats", "zinc", "copper", "manganese"],
  "peanuts": ["plant-protein", "magnesium", "vitamin-e", "zinc"],
  "macadamia": ["unsaturated-fats", "manganese", "copper", "magnesium"],
  // ── WS0.8 — Wave 7: Dairy and Alternatives ─────────────────────────────────
  "milk": ["calcium", "vitamin-d", "vitamin-b12", "iodine"],
  "yoghurt": ["calcium", "vitamin-b12", "vitamin-d", "live-cultures"],
  "greek-yoghurt": ["calcium", "vitamin-b12", "vitamin-d", "selenium"],
  "cheddar": ["calcium", "vitamin-b12", "iodine", "selenium"],
  "mozzarella": ["calcium", "vitamin-b12", "selenium"],
  "halloumi": ["calcium", "vitamin-b12", "selenium"],
  "feta": ["calcium", "vitamin-b12", "selenium"],
  "parmesan": ["calcium", "vitamin-b12", "selenium", "zinc"],
  "ricotta": ["calcium", "vitamin-b12", "selenium"],
  "oat-milk": ["fibre", "manganese", "folate"],
  "soy-milk": ["plant-protein", "calcium", "vitamin-d", "vitamin-b12"],
  "almond-milk": ["vitamin-e", "calcium", "vitamin-d"],
  "tofu": ["plant-protein", "calcium", "iron", "manganese"],
  // ── WS0.8 — Wave 8: Proteins ────────────────────────────────────────────────
  "eggs": ["vitamin-d", "vitamin-b12", "selenium", "iodine"],
  "chicken": ["selenium", "vitamin-b6", "zinc", "vitamin-b12"],
  "turkey": ["selenium", "vitamin-b6", "zinc", "vitamin-b12"],
  "beef": ["iron", "zinc", "vitamin-b12", "selenium"],
  "lamb": ["iron", "zinc", "vitamin-b12", "selenium"],
  "pork": ["vitamin-b6", "vitamin-b12", "selenium", "zinc"],
  "duck": ["iron", "zinc", "vitamin-b12", "selenium"],
  "tuna": ["omega-3", "selenium", "vitamin-d", "vitamin-b12"],
  "mackerel": ["omega-3", "vitamin-d", "selenium", "vitamin-b12"],
  "cod": ["selenium", "vitamin-b12", "iodine", "vitamin-d"],
  "haddock": ["selenium", "vitamin-b12", "iodine", "vitamin-d"],
  "anchovies": ["omega-3", "calcium", "selenium", "vitamin-d"],
  "prawns": ["selenium", "zinc", "iodine", "vitamin-b12"],
  // ── WS0.8 — Grains & Cereals ────────────────────────────────────────────────
  "oats": ["fibre", "magnesium", "iron", "zinc"],
  "brown-rice": ["fibre", "magnesium", "manganese", "selenium"],
  "white-rice": ["selenium", "folate", "iron"],
  "quinoa": ["plant-protein", "fibre", "magnesium", "iron"],
  "buckwheat": ["fibre", "magnesium", "manganese", "iron"],
  "barley": ["fibre", "selenium", "magnesium", "iron"],
  "spelt": ["fibre", "magnesium", "iron", "zinc"],
  "rye": ["fibre", "iron", "magnesium", "selenium"],
  "wheat": ["fibre", "iron", "magnesium", "folate"],
  "couscous": ["selenium", "fibre", "folate", "iron"],
  "bulgur-wheat": ["fibre", "iron", "magnesium", "manganese"],
  "pasta": ["fibre", "iron", "folate", "selenium"],
  "millet": ["magnesium", "iron", "fibre", "copper"],
  "freekeh": ["fibre", "iron", "magnesium", "zinc"],
  // ── WS0.8 — Other pantry staples ────────────────────────────────────────────
  "coconut": ["fibre", "manganese", "copper", "potassium"],
  "dates": ["fibre", "potassium", "magnesium", "iron"],
  "dark-chocolate": ["polyphenols", "magnesium", "iron", "manganese"],
  "butter": ["vitamin-a", "vitamin-d"],
  "sunflower-oil": ["vitamin-e", "unsaturated-fats"],

  // ── WS0X.2 — H1 UK Household Promotion Batch 2026-06-24 ────────────────
  // Fish & Seafood
  "pollock": ["selenium", "vitamin-b12", "iodine", "vitamin-d"],
  "tilapia": ["selenium", "vitamin-b12", "iodine"],
  "sea-bass": ["selenium", "vitamin-b12", "iodine", "vitamin-d"],
  "sea-bream": ["selenium", "vitamin-b12", "iodine"],
  "squid": ["selenium", "copper", "zinc", "vitamin-b12"],
  "mussels": ["omega-3", "iron", "selenium", "vitamin-b12"],
  "crab": ["selenium", "zinc", "copper", "vitamin-b12"],
  "scallops": ["selenium", "zinc", "vitamin-b12", "iodine"],
  // Meat
  "venison": ["iron", "zinc", "vitamin-b12", "selenium"],
  "liver": ["iron", "vitamin-b12", "folate", "vitamin-a"],
  // Vegetables
  "okra": ["fibre", "folate", "vitamin-c", "vitamin-k"],
  "runner-beans": ["fibre", "folate", "vitamin-c", "vitamin-k"],
  "mangetout": ["vitamin-c", "vitamin-k", "folate", "fibre"],
  "sugar-snap-peas": ["vitamin-c", "vitamin-k", "fibre", "folate"],
  "purple-sprouting-broccoli": ["vitamin-c", "sulforaphane", "folate", "vitamin-k"],
  "spring-greens": ["vitamin-k", "folate", "vitamin-c", "beta-carotene"],
  "savoy-cabbage": ["vitamin-c", "vitamin-k", "fibre", "folate"],
  "white-cabbage": ["vitamin-c", "vitamin-k", "fibre", "folate"],
  "water-chestnuts": ["fibre", "potassium", "vitamin-b6"],
  "baby-corn": ["fibre", "folate", "vitamin-c"],
  "bean-sprouts": ["vitamin-c", "folate", "fibre"],
  "bamboo-shoots": ["fibre", "potassium", "vitamin-b6"],
  "cassava": ["fibre", "potassium", "vitamin-c"],
  "broccoli-raab": ["folate", "vitamin-k", "vitamin-c", "calcium"],
  "mustard-greens": ["folate", "vitamin-k", "vitamin-c", "beta-carotene"],
  // Fruit
  "jackfruit": ["fibre", "vitamin-c", "potassium"],
  "elderberries": ["vitamin-c", "anthocyanins", "fibre"],
  "goji-berries": ["vitamin-c", "iron", "beta-carotene"],
  "lychees": ["vitamin-c", "folate", "potassium"],
  "papayas": ["vitamin-c", "folate", "beta-carotene"],
  "mulberries": ["vitamin-c", "anthocyanins", "iron"],
  "loganberries": ["vitamin-c", "flavonoids", "fibre"],
  "guava": ["vitamin-c", "folate", "potassium"],
  "plantain": ["potassium", "fibre", "vitamin-b6"],
  "physalis": ["vitamin-c", "beta-carotene", "polyphenols"],
  // Grains
  "sorghum": ["fibre", "iron", "magnesium"],
  "amaranth": ["plant-protein", "iron", "magnesium", "calcium"],
  "farro": ["fibre", "iron", "magnesium", "zinc"],
  "semolina": ["fibre", "iron", "folate"],
  "black-rice": ["anthocyanins", "fibre", "iron"],
  "polenta": ["fibre", "iron"],
  "teff": ["iron", "calcium", "fibre", "magnesium"],
  "rice-flour": ["iron", "folate"],
  "almond-flour": ["vitamin-e", "magnesium", "plant-protein"],
  "coconut-flour": ["fibre", "manganese"],
  "spelt-flour": ["fibre", "magnesium", "iron", "zinc"],
  "barley-flour": ["fibre", "iron", "magnesium"],
  // Legumes
  "pinto-beans": ["fibre", "plant-protein", "iron", "folate"],
  "black-eyed-peas": ["fibre", "plant-protein", "folate", "iron"],
  "chickpea-flour": ["plant-protein", "fibre", "iron", "folate"],
  // Dairy
  "cottage-cheese": ["calcium", "vitamin-b12", "selenium"],
  "cream-cheese": ["calcium", "vitamin-a"],
  "sour-cream": ["calcium"],
  "creme-fraiche": ["calcium"],
  "buttermilk": ["calcium", "vitamin-b12"],
  "blue-cheese": ["calcium", "vitamin-b12", "selenium", "zinc"],
  "gouda": ["calcium", "vitamin-b12", "selenium"],
  "brie": ["calcium", "vitamin-b12", "selenium"],
  "camembert": ["calcium", "vitamin-b12", "selenium"],
  "stilton": ["calcium", "vitamin-b12", "selenium", "zinc"],
  "goat-cheese": ["calcium", "vitamin-b12", "selenium"],
  "mascarpone": ["calcium"],
  "double-cream": ["vitamin-a", "vitamin-d"],
  // Nuts & Seeds
  "almond-butter": ["vitamin-e", "magnesium", "plant-protein", "unsaturated-fats"],
  "tahini": ["calcium", "copper", "unsaturated-fats", "plant-protein"],
  "nigella-seeds": ["iron", "calcium", "polyphenols"],
  // Herbs
  "marjoram": ["polyphenols", "vitamin-k", "iron"],
  "chervil": ["vitamin-c", "folate", "vitamin-k"],
  // Spices & Condiments
  "capers": ["vitamin-k", "polyphenols"],
  "horseradish": ["vitamin-c", "vitamin-k"],
  "caraway-seeds": ["iron", "manganese", "calcium"],
  "fenugreek": ["iron", "fibre", "manganese"],
  "sumac": ["polyphenols", "vitamin-c"],
  // Oils
  "coconut-oil": ["vitamin-e", "manganese"],
  "rapeseed-oil": ["vitamin-e", "unsaturated-fats", "vitamin-k"],
  "sesame-oil": ["vitamin-e", "polyphenols", "unsaturated-fats"],
  // Fermented
  "natto": ["vitamin-k", "plant-protein", "fibre", "live-cultures"],
};

// ── Food → Health benefits it supports ──────────────────────────────────────
export const FOOD_BENEFITS: Record<string, string[]> = {
  "extra-virgin-olive-oil": ["heart-health", "anti-inflammatory-support", "brain-health"],
  "avocado": ["heart-health", "skin-health", "digestive-comfort"],
  "walnuts": ["brain-health", "heart-health", "mood-support", "muscle-recovery"], // FI2: plant-protein+magnesium→muscle-recovery
  "almonds": ["heart-health", "bone-health", "skin-health", "muscle-recovery"], // FI2: plant-protein+magnesium→muscle-recovery
  "salmon": ["heart-health", "brain-health", "mood-support", "energy-support"], // FI2: vitamin-b12+selenium→energy-support
  "sardines": ["heart-health", "bone-health", "brain-health", "energy-support"], // FI2: vitamin-b12→energy-support
  "pumpkin-seeds": ["sleep-quality", "heart-health", "immune-support", "mood-support"], // FI2: magnesium→mood-support
  "sunflower-seeds": ["skin-health", "immune-support", "heart-health"],
  "chia-seeds": ["gut-health", "heart-health", "blood-sugar-balance"],
  "flaxseed": ["gut-health", "heart-health", "digestive-comfort"],
  "sesame-seeds": ["bone-health", "heart-health"],
  "hemp-seeds": ["muscle-recovery", "heart-health", "mood-support"], // FI2: magnesium→mood-support
  "butter-beans": ["gut-health", "blood-sugar-balance", "heart-health"],
  "chickpeas": ["gut-health", "blood-sugar-balance", "muscle-recovery", "energy-support"], // FI2: iron+folate→energy-support
  "red-lentils": ["gut-health", "energy-support", "muscle-recovery"],
  "black-beans": ["gut-health", "heart-health", "blood-sugar-balance"],
  "kidney-beans": ["gut-health", "blood-sugar-balance", "energy-support"],
  "edamame": ["muscle-recovery", "bone-health", "heart-health"],
  "garden-peas": ["gut-health", "immune-support"],
  "kimchi": ["gut-health", "digestive-comfort", "immune-support"],
  "sauerkraut": ["gut-health", "digestive-comfort", "immune-support"],
  "kefir": ["gut-health", "bone-health", "digestive-comfort"],
  "miso": ["gut-health", "digestive-comfort"],
  "tempeh": ["gut-health", "muscle-recovery", "heart-health"],
  "parsley": ["bone-health", "immune-support"],
  "basil": ["anti-inflammatory-support", "heart-health"],
  "coriander": ["digestive-comfort", "anti-inflammatory-support"],
  "mint": ["digestive-comfort"],
  "rosemary": ["anti-inflammatory-support", "brain-health"],
  "thyme": ["immune-support", "anti-inflammatory-support"],
  "white-mushrooms": ["immune-support", "bone-health"],
  "chestnut-mushrooms": ["immune-support", "heart-health"],
  "shiitake-mushrooms": ["immune-support", "heart-health"],
  "oyster-mushrooms": ["immune-support", "heart-health"],
  "kale": ["bone-health", "eye-health", "anti-inflammatory-support", "healthy-ageing", "immune-support"], // FI2: vitamin-c→immune-support
  "spinach": ["eye-health", "energy-support", "bone-health", "muscle-recovery"], // FI2: iron+plant-protein awareness→muscle-recovery
  "broccoli": ["immune-support", "anti-inflammatory-support", "healthy-ageing", "eye-health"], // FI2: beta-carotene→eye-health
  "tomatoes": ["heart-health", "skin-health", "healthy-ageing"],
  "sweet-potato": ["eye-health", "immune-support", "gut-health"],
  "red-pepper": ["immune-support", "skin-health", "eye-health"],
  "carrots": ["eye-health", "skin-health", "immune-support"],
  "beetroot": ["heart-health", "energy-support"],
  "garlic": ["immune-support", "heart-health", "anti-inflammatory-support"],
  "onion": ["gut-health", "heart-health"],
  "blueberries": ["brain-health", "heart-health", "healthy-ageing"],
  "strawberries": ["immune-support", "skin-health", "heart-health"],
  "apples": ["gut-health", "heart-health", "blood-sugar-balance"],
  "bananas": ["energy-support", "muscle-recovery", "gut-health"],
  "oranges": ["immune-support", "skin-health", "heart-health"],
  "kiwi": ["immune-support", "digestive-comfort", "skin-health"],
  // Mediterranean Vegetables (WS0.6)
  "watercress": ["immune-support", "bone-health", "eye-health", "anti-inflammatory-support", "energy-support"], // FI2: iron+folate→energy-support
  "rocket": ["bone-health", "anti-inflammatory-support", "immune-support", "energy-support", "eye-health"], // FI2: folate+vitamin-c→energy-support; beta-carotene→eye-health
  "parsnip": ["gut-health", "heart-health", "energy-support"],
  "turnip": ["immune-support", "gut-health"],
  "swede": ["immune-support", "gut-health", "heart-health"],
  "red-cabbage": ["gut-health", "anti-inflammatory-support", "immune-support", "healthy-ageing"],
  "pak-choi": ["bone-health", "immune-support", "eye-health"],
  "spring-onion": ["bone-health", "immune-support"],
  "aubergine": ["heart-health", "gut-health", "anti-inflammatory-support"],
  "courgette": ["immune-support", "heart-health", "gut-health"],
  "cucumber": ["heart-health", "digestive-comfort"],
  "fennel": ["gut-health", "digestive-comfort", "heart-health"],
  "celery": ["heart-health", "bone-health", "digestive-comfort"],
  "asparagus": ["bone-health", "gut-health", "energy-support"],
  "artichoke": ["gut-health", "digestive-comfort", "heart-health", "blood-sugar-balance"],
  "broad-beans": ["muscle-recovery", "gut-health", "energy-support"],
  "radicchio": ["gut-health", "anti-inflammatory-support", "bone-health", "healthy-ageing"],
  "chicory": ["gut-health", "digestive-comfort", "anti-inflammatory-support"],

  // ── WS0.8 — Wave 1: Pantry Essentials ──────────────────────────────────────
  "potato": ["energy-support", "gut-health", "immune-support"],
  "leek": ["gut-health", "heart-health", "bone-health"],
  "shallot": ["gut-health", "immune-support", "anti-inflammatory-support"],
  "cauliflower": ["immune-support", "anti-inflammatory-support", "healthy-ageing"],
  "cabbage": ["gut-health", "immune-support", "anti-inflammatory-support"],
  "butternut-squash": ["eye-health", "immune-support", "anti-inflammatory-support"],
  "pumpkin": ["eye-health", "immune-support", "skin-health"],
  "brussels-sprouts": ["immune-support", "anti-inflammatory-support", "bone-health"],
  "celeriac": ["digestive-comfort", "immune-support", "heart-health"],
  "green-beans": ["bone-health", "immune-support", "gut-health"],
  "radish": ["immune-support", "digestive-comfort"],
  "kohlrabi": ["immune-support", "gut-health"],
  "corn": ["energy-support", "gut-health"],
  // ── WS0.8 — Wave 2: Mediterranean Vegetables ───────────────────────────────
  "lettuce": ["bone-health", "digestive-comfort", "immune-support"],
  "olives": ["heart-health", "anti-inflammatory-support", "brain-health"],
  "chard": ["bone-health", "energy-support", "anti-inflammatory-support"],
  "jerusalem-artichoke": ["gut-health", "digestive-comfort", "energy-support"],
  // ── WS0.8 — Wave 3: Beans, Pulses and Legumes ──────────────────────────────
  "cannellini-beans": ["gut-health", "blood-sugar-balance", "muscle-recovery"],
  "borlotti-beans": ["gut-health", "blood-sugar-balance", "energy-support"],
  "haricot-beans": ["gut-health", "blood-sugar-balance", "muscle-recovery"],
  "green-lentils": ["gut-health", "energy-support", "muscle-recovery"],
  "puy-lentils": ["gut-health", "energy-support", "muscle-recovery"],
  "beluga-lentils": ["gut-health", "energy-support", "anti-inflammatory-support"],
  // ── WS0.8 — Wave 4: Fruit ──────────────────────────────────────────────────
  "raspberry": ["gut-health", "immune-support", "healthy-ageing"],
  "pear": ["gut-health", "heart-health", "digestive-comfort"],
  "mango": ["immune-support", "skin-health", "eye-health"],
  "grape": ["heart-health", "brain-health", "healthy-ageing"],
  "lemon": ["immune-support", "skin-health", "digestive-comfort"],
  "lime": ["immune-support", "skin-health"],
  "pomegranate": ["heart-health", "anti-inflammatory-support", "healthy-ageing"],
  "peach": ["immune-support", "skin-health", "eye-health"],
  "plum": ["gut-health", "anti-inflammatory-support", "healthy-ageing"],
  "cherry": ["anti-inflammatory-support", "healthy-ageing", "heart-health"],
  "nectarine": ["immune-support", "skin-health", "eye-health"],
  "watermelon": ["heart-health", "skin-health", "digestive-comfort"],
  "pineapple": ["immune-support", "digestive-comfort", "anti-inflammatory-support"],
  "fig": ["gut-health", "bone-health", "energy-support"],
  "apricot": ["eye-health", "skin-health", "immune-support"],
  "passion-fruit": ["gut-health", "immune-support", "heart-health"],
  "blackberry": ["gut-health", "anti-inflammatory-support", "healthy-ageing"],
  "melon": ["immune-support", "skin-health", "digestive-comfort"],
  "cranberry": ["immune-support", "gut-health"],
  "blackcurrant": ["immune-support", "anti-inflammatory-support", "healthy-ageing"],
  "redcurrant": ["immune-support", "gut-health"],
  "gooseberry": ["immune-support", "gut-health"],
  "raisins": ["energy-support", "gut-health"],
  // ── WS0.8 — Wave 5: Herbs ──────────────────────────────────────────────────
  "oregano": ["anti-inflammatory-support", "immune-support"],
  "dill": ["digestive-comfort", "bone-health"],
  "chives": ["bone-health", "immune-support"],
  "sage": ["anti-inflammatory-support", "brain-health"],
  "tarragon": ["digestive-comfort", "anti-inflammatory-support"],
  "bay-leaf": ["digestive-comfort", "anti-inflammatory-support"],
  "lemongrass": ["digestive-comfort", "anti-inflammatory-support"],
  // ── WS0.8 — Wave 5: Spices ──────────────────────────────────────────────────
  "ginger": ["digestive-comfort", "anti-inflammatory-support", "immune-support"],
  "turmeric": ["anti-inflammatory-support", "brain-health", "healthy-ageing"],
  "cumin": ["digestive-comfort", "energy-support"],
  "cinnamon": ["blood-sugar-balance", "anti-inflammatory-support"],
  "paprika": ["immune-support", "anti-inflammatory-support"],
  "clementine": ["immune-support", "skin-health", "heart-health"],
  "vanilla": ["digestive-comfort"],
  "chilli": ["immune-support", "anti-inflammatory-support", "digestive-comfort"],
  "black-pepper": ["digestive-comfort", "anti-inflammatory-support"],
  "cardamom": ["digestive-comfort", "anti-inflammatory-support"],
  "star-anise": ["digestive-comfort", "anti-inflammatory-support"],
  "cloves": ["anti-inflammatory-support", "bone-health"],
  "nutmeg": ["digestive-comfort", "anti-inflammatory-support"],
  // ── WS0.8 — Wave 6: Nuts and Seeds ─────────────────────────────────────────
  "hazelnuts": ["heart-health", "skin-health", "brain-health"],
  "cashews": ["heart-health", "muscle-recovery", "bone-health"],
  "pistachios": ["heart-health", "gut-health", "blood-sugar-balance"],
  "brazil-nuts": ["immune-support", "anti-inflammatory-support", "healthy-ageing"],
  "pine-nuts": ["heart-health", "skin-health", "muscle-recovery"],
  "pecans": ["heart-health", "brain-health", "anti-inflammatory-support"],
  "peanuts": ["heart-health", "muscle-recovery", "blood-sugar-balance"],
  "macadamia": ["heart-health", "anti-inflammatory-support", "brain-health"],
  // ── WS0.8 — Wave 7: Dairy and Alternatives ─────────────────────────────────
  "milk": ["bone-health", "muscle-recovery", "energy-support"],
  "yoghurt": ["bone-health", "digestive-comfort", "gut-health"],
  "greek-yoghurt": ["bone-health", "muscle-recovery", "gut-health"],
  "cheddar": ["bone-health", "energy-support"],
  "mozzarella": ["bone-health", "muscle-recovery"],
  "halloumi": ["bone-health", "muscle-recovery"],
  "feta": ["bone-health"],
  "parmesan": ["bone-health", "muscle-recovery", "energy-support"],
  "ricotta": ["bone-health", "muscle-recovery"],
  "oat-milk": ["heart-health", "gut-health", "blood-sugar-balance"],
  "soy-milk": ["bone-health", "heart-health", "muscle-recovery"],
  "almond-milk": ["bone-health", "skin-health"],
  "tofu": ["muscle-recovery", "bone-health", "heart-health"],
  // ── WS0.8 — Wave 8: Proteins ────────────────────────────────────────────────
  "eggs": ["brain-health", "energy-support", "bone-health"],
  "chicken": ["muscle-recovery", "energy-support"],
  "turkey": ["muscle-recovery", "energy-support", "mood-support"],
  "beef": ["energy-support", "muscle-recovery"],
  "lamb": ["energy-support", "muscle-recovery"],
  "pork": ["energy-support", "muscle-recovery"],
  "duck": ["energy-support", "muscle-recovery"],
  "tuna": ["heart-health", "brain-health", "muscle-recovery"],
  "mackerel": ["heart-health", "brain-health", "mood-support"],
  "cod": ["muscle-recovery", "energy-support", "bone-health"],
  "haddock": ["muscle-recovery", "energy-support", "bone-health"],
  "anchovies": ["heart-health", "bone-health", "brain-health"],
  "prawns": ["muscle-recovery", "immune-support", "energy-support"],
  // ── WS0.8 — Grains & Cereals ────────────────────────────────────────────────
  "oats": ["gut-health", "blood-sugar-balance", "heart-health"],
  "brown-rice": ["gut-health", "energy-support", "blood-sugar-balance"],
  "white-rice": ["energy-support"],
  "quinoa": ["muscle-recovery", "gut-health", "energy-support"],
  "buckwheat": ["heart-health", "blood-sugar-balance", "gut-health"],
  "barley": ["gut-health", "blood-sugar-balance", "heart-health"],
  "spelt": ["gut-health", "energy-support", "heart-health"],
  "rye": ["gut-health", "blood-sugar-balance", "heart-health"],
  "wheat": ["gut-health", "energy-support"],
  "couscous": ["energy-support", "gut-health"],
  "bulgur-wheat": ["gut-health", "blood-sugar-balance", "energy-support"],
  "pasta": ["energy-support", "gut-health"],
  "millet": ["gut-health", "energy-support", "blood-sugar-balance"],
  "freekeh": ["gut-health", "blood-sugar-balance", "energy-support"],
  // ── WS0.8 — Other pantry staples ────────────────────────────────────────────
  "coconut": ["energy-support", "gut-health"],
  "dates": ["energy-support", "gut-health"],
  "dark-chocolate": ["heart-health", "brain-health", "anti-inflammatory-support"],
  "butter": ["bone-health", "eye-health"],
  "sunflower-oil": ["skin-health", "heart-health"],

  // ── WS0X.2 — H1 UK Household Promotion Batch 2026-06-24 ────────────────
  // Fish & Seafood
  "pollock": ["muscle-recovery", "energy-support", "bone-health"],
  "tilapia": ["muscle-recovery", "energy-support"],
  "sea-bass": ["muscle-recovery", "energy-support", "heart-health"],
  "sea-bream": ["muscle-recovery", "energy-support"],
  "squid": ["muscle-recovery", "immune-support"],
  "mussels": ["heart-health", "energy-support", "immune-support"],
  "crab": ["muscle-recovery", "immune-support", "energy-support"],
  "scallops": ["muscle-recovery", "immune-support"],
  // Meat
  "venison": ["energy-support", "muscle-recovery"],
  "liver": ["energy-support", "healthy-ageing", "immune-support"],
  // Vegetables
  "okra": ["gut-health", "immune-support", "bone-health"],
  "runner-beans": ["gut-health", "bone-health", "immune-support"],
  "mangetout": ["immune-support", "bone-health"],
  "sugar-snap-peas": ["immune-support", "gut-health"],
  "purple-sprouting-broccoli": ["immune-support", "anti-inflammatory-support", "bone-health"],
  "spring-greens": ["bone-health", "immune-support", "eye-health"],
  "savoy-cabbage": ["immune-support", "gut-health", "anti-inflammatory-support"],
  "white-cabbage": ["immune-support", "gut-health", "anti-inflammatory-support"],
  "water-chestnuts": ["gut-health", "energy-support"],
  "baby-corn": ["gut-health", "energy-support"],
  "bean-sprouts": ["immune-support", "digestive-comfort"],
  "bamboo-shoots": ["gut-health", "digestive-comfort"],
  "cassava": ["energy-support", "gut-health"],
  "broccoli-raab": ["bone-health", "immune-support", "anti-inflammatory-support"],
  "mustard-greens": ["bone-health", "immune-support", "eye-health"],
  // Fruit
  "jackfruit": ["gut-health", "immune-support"],
  "elderberries": ["immune-support", "anti-inflammatory-support", "healthy-ageing"],
  "goji-berries": ["immune-support", "eye-health", "anti-inflammatory-support"],
  "lychees": ["immune-support", "skin-health"],
  "papayas": ["immune-support", "digestive-comfort", "skin-health"],
  "mulberries": ["gut-health", "anti-inflammatory-support", "immune-support"],
  "loganberries": ["gut-health", "immune-support"],
  "guava": ["immune-support", "skin-health", "gut-health"],
  "plantain": ["energy-support", "gut-health"],
  "physalis": ["immune-support", "anti-inflammatory-support"],
  // Grains
  "sorghum": ["gut-health", "energy-support", "blood-sugar-balance"],
  "amaranth": ["muscle-recovery", "gut-health", "energy-support"],
  "farro": ["gut-health", "energy-support", "blood-sugar-balance"],
  "semolina": ["energy-support", "gut-health"],
  "black-rice": ["gut-health", "anti-inflammatory-support", "healthy-ageing"],
  "polenta": ["energy-support", "gut-health"],
  "teff": ["energy-support", "bone-health", "gut-health"],
  "rice-flour": ["energy-support"],
  "almond-flour": ["heart-health", "skin-health", "bone-health"],
  "coconut-flour": ["gut-health", "blood-sugar-balance"],
  "spelt-flour": ["gut-health", "energy-support", "heart-health"],
  "barley-flour": ["gut-health", "blood-sugar-balance", "heart-health"],
  // Legumes
  "pinto-beans": ["gut-health", "blood-sugar-balance", "muscle-recovery"],
  "black-eyed-peas": ["gut-health", "energy-support", "muscle-recovery"],
  "chickpea-flour": ["gut-health", "muscle-recovery", "blood-sugar-balance"],
  // Dairy
  "cottage-cheese": ["bone-health", "muscle-recovery"],
  "cream-cheese": ["bone-health"],
  "sour-cream": ["gut-health", "digestive-comfort"],
  "creme-fraiche": ["gut-health", "digestive-comfort"],
  "buttermilk": ["gut-health", "digestive-comfort", "bone-health"],
  "blue-cheese": ["bone-health", "muscle-recovery"],
  "gouda": ["bone-health", "muscle-recovery"],
  "brie": ["bone-health", "muscle-recovery"],
  "camembert": ["bone-health", "muscle-recovery"],
  "stilton": ["bone-health", "muscle-recovery"],
  "goat-cheese": ["bone-health", "digestive-comfort"],
  "mascarpone": ["bone-health"],
  "double-cream": ["bone-health", "energy-support"],
  // Nuts & Seeds
  "almond-butter": ["heart-health", "skin-health", "muscle-recovery"],
  "tahini": ["bone-health", "heart-health", "energy-support"],
  "nigella-seeds": ["anti-inflammatory-support", "digestive-comfort"],
  // Herbs
  "marjoram": ["anti-inflammatory-support", "digestive-comfort"],
  "chervil": ["immune-support", "bone-health"],
  // Spices & Condiments
  "capers": ["anti-inflammatory-support", "heart-health"],
  "horseradish": ["immune-support", "anti-inflammatory-support"],
  "caraway-seeds": ["digestive-comfort", "anti-inflammatory-support"],
  "fenugreek": ["digestive-comfort", "blood-sugar-balance", "energy-support"],
  "sumac": ["anti-inflammatory-support", "digestive-comfort"],
  // Oils
  "coconut-oil": ["energy-support"],
  "rapeseed-oil": ["heart-health", "anti-inflammatory-support", "healthy-ageing"],
  "sesame-oil": ["heart-health", "anti-inflammatory-support", "skin-health"],
  // Fermented
  "natto": ["bone-health", "gut-health", "healthy-ageing"],
};

// ── Nutrient → Health benefits it supports ──────────────────────────────────
export const NUTRIENT_BENEFITS: Record<string, string[]> = {
  "fibre": ["gut-health", "blood-sugar-balance", "digestive-comfort", "heart-health"],
  "plant-protein": ["muscle-recovery", "energy-support"],
  "unsaturated-fats": ["heart-health", "brain-health"],
  "omega-3": ["heart-health", "brain-health", "mood-support", "anti-inflammatory-support"],
  "magnesium": ["sleep-quality", "muscle-recovery", "bone-health", "mood-support"],
  "zinc": ["immune-support", "skin-health"],
  "iron": ["energy-support"],
  "calcium": ["bone-health"],
  "potassium": ["heart-health", "muscle-recovery"],
  "selenium": ["immune-support", "anti-inflammatory-support"],
  "manganese": ["bone-health"],
  "copper": ["energy-support", "immune-support"],
  "iodine": ["energy-support"],
  "vitamin-c": ["immune-support", "skin-health", "energy-support"],
  "vitamin-d": ["bone-health", "immune-support", "mood-support"],
  "vitamin-e": ["skin-health", "healthy-ageing"],
  "vitamin-k": ["bone-health"],
  "vitamin-a": ["eye-health", "immune-support", "skin-health"],
  "beta-carotene": ["eye-health", "skin-health", "healthy-ageing"],
  "folate": ["energy-support", "healthy-ageing"],
  "vitamin-b6": ["energy-support", "mood-support"],
  "vitamin-b12": ["energy-support", "brain-health"],
  "polyphenols": ["heart-health", "healthy-ageing", "anti-inflammatory-support"],
  "flavonoids": ["heart-health", "brain-health"],
  "anthocyanins": ["brain-health", "heart-health", "healthy-ageing"],
  "lycopene": ["heart-health", "skin-health"],
  "sulforaphane": ["anti-inflammatory-support", "healthy-ageing"],
  "allicin": ["immune-support", "heart-health"],
  "nitrates": ["heart-health", "energy-support"],
  "live-cultures": ["gut-health", "digestive-comfort", "immune-support"],
};
