/**
 * restriction-library.ts
 * ======================
 * Canonical restriction definitions.
 *
 * Phase 3 scope: peanut, tree_nut (split from Phase 2 nut_free), sesame, soy,
 * mustard, shellfish, eggs, coconut — plus preserved gluten and dairy.
 *
 * nut_free is no longer a canonical definition. Backward compatibility is
 * handled in the resolver via LEGACY_ALIAS_EXPANSIONS.
 *
 * Authoring rules:
 * - All definitions must be human-authored and reviewed before merging.
 * - Never generated by AI or the database.
 * - Empty arrays are valid where data does not yet exist.
 * - derivedIngredients: products made FROM the allergen (indirect sources).
 * - hiddenIngredients: products where the allergen is not obvious by name.
 * - substitutions: for display and future recommendation only; not used in matching.
 *   Include cross-restriction caveats inline (e.g. "tahini (check sesame restriction)").
 * - prohibitedPhrases: for future post-generation content validation only.
 *
 * Phase 4 candidates: fish, celery, lupin, molluscs, sulphites.
 */

import type { RestrictionDefinition } from './restriction-types.js';

export const RESTRICTION_LIBRARY_VERSION = '3.0.0';

export const RESTRICTION_DEFINITIONS: RestrictionDefinition[] = [

  // ── GLUTEN ──────────────────────────────────────────────────────────────────
  //
  // Covers wheat, barley, rye, and their derivatives.
  // Coeliac disease and non-coeliac gluten sensitivity are both mapped here.
  {
    id: 'gluten',
    displayName: 'Gluten',
    tier: 'major_allergen',
    aliases: [
      'gluten',
      'gluten free',
      'gluten-free',
      'wheat',
      'wheat free',
      'wheat-free',
      'coeliac',
      'celiac',
    ],
    derivedIngredients: [
      'wholemeal',
      'wholegrain',
      'bulgur wheat',
      'bulgur',
      'couscous',
      'semolina',
      'spelt',
      'barley',
      'rye',
      'durum',
      'farro',
      'freekeh',
      'kamut',
      'flour',
      'bread',
      'pasta',
      'noodles',
      'tortilla',
      'panko',
    ],
    hiddenIngredients: [
      'soy sauce',
      'malt vinegar',
      'worcestershire sauce',
      'beer',
      'barley malt',
      'malt extract',
      'hoisin sauce',
      'teriyaki sauce',
    ],
    substitutions: [
      'gluten-free pasta',
      'gluten-free bread',
      'rice flour',
      'cornflour',
      'rice noodles',
      'buckwheat',
      'quinoa',
    ],
    prohibitedPhrases: [
      'wheat flour',
      'plain flour',
      'self-raising flour',
      'breadcrumbs',
      'pasta',
      'barley',
      'rye bread',
      'spelt',
    ],
  },

  // ── DAIRY ───────────────────────────────────────────────────────────────────
  //
  // Covers cow's milk protein allergy and lactose intolerance.
  {
    id: 'dairy',
    displayName: 'Dairy',
    tier: 'major_allergen',
    aliases: [
      'dairy',
      'dairy free',
      'dairy-free',
      'milk',
      'milk free',
      'milk-free',
      'lactose',
      'lactose free',
      'lactose-free',
      'lactose intolerant',
    ],
    derivedIngredients: [
      'butter',
      'cream',
      'yoghurt',
      'yogurt',
      'cheese',
      'ghee',
      'whey',
      'casein',
      'creme fraiche',
      'fromage frais',
      'sour cream',
      'double cream',
      'single cream',
      'clotted cream',
      'custard',
      'condensed milk',
      'evaporated milk',
      'buttermilk',
    ],
    hiddenIngredients: [
      'milk chocolate',
      'white chocolate',
      'caramel',
    ],
    substitutions: [
      'oat milk',
      'plant-based milk',
      'coconut cream (check coconut restriction)',
      'dairy-free yoghurt',
      'vegan butter',
      'olive oil',
    ],
    prohibitedPhrases: [
      'milk',
      'butter',
      'cream',
      'cheese',
      'yoghurt',
      'yogurt',
      'ghee',
    ],
    excludedCompounds: [
      // Plant milks — contain "milk" alias but are dairy-free by definition
      'coconut milk',
      'oat milk',
      'rice milk',
      'almond milk',
      'cashew milk',
      'hemp milk',
      'pea milk',
      'soy milk',
      'soya milk',
      'hazelnut milk',
      'macadamia milk',
      'plant milk',
      'plant-based milk',
      'oat mylk',
      // Plant creams — contain "cream" derivedIngredient but are dairy-free by definition
      'coconut cream',
      'oat cream',
      'soya cream',
      'soy cream',
      'almond cream',
      'cashew cream',
      'rice cream',
    ],
  },

  // ── PEANUT ──────────────────────────────────────────────────────────────────
  //
  // Peanuts are a legume, not a tree nut — a distinct allergen and medical category.
  // Separated from tree_nut in Phase 3. Backward compat: "nut_free" expands to
  // both peanut + tree_nut via LEGACY_ALIAS_EXPANSIONS in the resolver.
  {
    id: 'peanut',
    displayName: 'Peanut',
    tier: 'major_allergen',
    aliases: [
      'peanut',
      'peanuts',
      'groundnut',
      'groundnuts',
      'peanut free',
      'peanut-free',
      'peanut allergy',
    ],
    derivedIngredients: [
      'peanut butter',
      'peanut oil',
      'peanut sauce',
      'groundnut oil',
    ],
    hiddenIngredients: [
      'satay sauce',
      'satay',
      'pad thai sauce',
    ],
    substitutions: [
      'sunflower seed butter',
      'tahini (check sesame restriction)',
      'seed butter',
    ],
    prohibitedPhrases: [
      'peanut',
      'groundnut',
    ],
  },

  // ── TREE_NUT ─────────────────────────────────────────────────────────────────
  //
  // Covers all tree nuts. Cross-contamination between tree nut varieties means
  // allergic households often restrict all. Individual nuts are listed in
  // derivedIngredients so "almond milk" and "walnut pesto" are both caught.
  // Separated from peanut in Phase 3.
  {
    id: 'tree_nut',
    displayName: 'Tree Nuts',
    tier: 'major_allergen',
    aliases: [
      'tree nut',
      'tree nuts',
      'tree-nut',
      'tree nut allergy',
      'tree nut free',
      'tree-nut-free',
    ],
    derivedIngredients: [
      // Almonds
      'almond',
      'almonds',
      'almond milk',
      'almond flour',
      'almond butter',
      // Cashews
      'cashew',
      'cashews',
      'cashew butter',
      'cashew cream',
      // Walnuts
      'walnut',
      'walnuts',
      // Hazelnuts
      'hazelnut',
      'hazelnuts',
      'hazelnut spread',
      // Pecans
      'pecan',
      'pecans',
      // Pistachios
      'pistachio',
      'pistachios',
      // Macadamia
      'macadamia',
      // Brazil nuts
      'brazil nut',
      'brazil nuts',
      // Pine nuts
      'pine nut',
      'pine nuts',
      // Derived products
      'nut butter',
      'marzipan',
      'praline',
      'nougat',
      'frangipane',
    ],
    hiddenIngredients: [
      'pesto',
      'romesco sauce',
    ],
    substitutions: [
      'seed butter',
      'sunflower seeds',
      'pumpkin seeds',
    ],
    prohibitedPhrases: [
      'almond',
      'cashew',
      'walnut',
      'pecan',
      'hazelnut',
      'pistachio',
      'brazil nut',
      'pine nut',
      'macadamia',
      'praline',
      'marzipan',
    ],
  },

  // ── SESAME ──────────────────────────────────────────────────────────────────
  //
  // UK major allergen since 2021. Tahini is the most common hidden sesame source.
  // Hummus typically contains tahini — listed in hiddenIngredients as a caution.
  {
    id: 'sesame',
    displayName: 'Sesame',
    tier: 'major_allergen',
    aliases: [
      'sesame',
      'sesame seed',
      'sesame seeds',
      'sesame-free',
      'sesame free',
    ],
    derivedIngredients: [
      'tahini',
      'sesame oil',
      'toasted sesame oil',
      'sesame paste',
      'sesame dressing',
      'sesame butter',
    ],
    hiddenIngredients: [
      'hummus',
    ],
    substitutions: [
      'sunflower seed butter',
      'pumpkin seed butter',
      'olive oil',
    ],
    prohibitedPhrases: [
      'sesame',
      'tahini',
      'sesame oil',
    ],
  },

  // ── SOY ─────────────────────────────────────────────────────────────────────
  //
  // Covers soy protein allergy and soya intolerance.
  // Note: soy sauce also contains gluten — both restrictions may flag it.
  // Word-boundary matching prevents "soy" matching "savoy cabbage".
  {
    id: 'soy',
    displayName: 'Soy',
    tier: 'major_allergen',
    aliases: [
      'soy',
      'soya',
      // Whole bean forms — wordBoundaryIncludes("soy") does not match "soybean"
      // because 'b' follows 'soy' without a word boundary. These must be listed
      // explicitly so "soybeans" in an ingredient list is caught.
      'soybean',
      'soybeans',
      'soya bean',
      'soya beans',
      'soy bean',
      'soy beans',
      'soy free',
      'soy-free',
      'soya free',
      'soya-free',
      'soy allergy',
    ],
    derivedIngredients: [
      'soy sauce',
      'soya sauce',
      'tofu',
      'tempeh',
      'edamame',
      'miso',
      'soy milk',
      'soya milk',
      'tamari',
      'soy cream',
      'soya cream',
      'soy flour',
    ],
    hiddenIngredients: [],
    substitutions: [
      'coconut aminos (check coconut restriction)',
      'salt, lemon juice, or stock alternatives',
    ],
    prohibitedPhrases: [
      'soy sauce',
      'tofu',
      'miso',
      'edamame',
    ],
  },

  // ── MUSTARD ─────────────────────────────────────────────────────────────────
  //
  // UK major allergen. Mustard can cause severe reactions in sensitised individuals.
  // All mustard-containing products share "mustard" in their name — alias matching
  // is generally sufficient; few hidden sources.
  {
    id: 'mustard',
    displayName: 'Mustard',
    tier: 'major_allergen',
    aliases: [
      'mustard',
      'mustard-free',
      'mustard free',
      'mustard allergy',
    ],
    derivedIngredients: [
      'mustard powder',
      'mustard seeds',
      'mustard seed',
      'dijon mustard',
      'english mustard',
      'wholegrain mustard',
      'whole grain mustard',
      'mustard oil',
      'mustard paste',
      'french mustard',
      'american mustard',
      'yellow mustard',
    ],
    hiddenIngredients: [],
    substitutions: [
      'horseradish',
      'wasabi',
      'herbs and spices depending on recipe',
    ],
    prohibitedPhrases: [
      'mustard',
    ],
  },

  // ── SHELLFISH ────────────────────────────────────────────────────────────────
  //
  // Covers crustaceans and molluscs together, as UK labelling law treats them
  // as a combined major allergen category. Oyster sauce is a common hidden source.
  {
    id: 'shellfish',
    displayName: 'Shellfish',
    tier: 'major_allergen',
    aliases: [
      'shellfish',
      'shellfish-free',
      'crustacean',
      'crustaceans',
      'mollusc',
      'molluscs',
      'mollusk',
      'mollusks',
      'shellfish allergy',
    ],
    derivedIngredients: [
      'prawn',
      'prawns',
      'shrimp',
      'crab',
      'lobster',
      'mussel',
      'mussels',
      'clam',
      'clams',
      'scallop',
      'scallops',
      'oyster',
      'oysters',
      'langoustine',
      'langoustines',
      'crayfish',
      'squid',
      'calamari',
      'octopus',
    ],
    hiddenIngredients: [
      'oyster sauce',
      'prawn crackers',
      'seafood sauce',
    ],
    substitutions: [
      'chicken',
      'mushrooms',
      'white fish (check fish restriction)',
      'tofu (check soy restriction)',
    ],
    prohibitedPhrases: [
      'prawn',
      'shrimp',
      'crab',
      'lobster',
      'shellfish',
      'mussel',
      'clam',
      'scallop',
      'oyster',
    ],
  },

  // ── EGGS ────────────────────────────────────────────────────────────────────
  //
  // Covers hen's egg allergy. Eggs appear in many forms in baking and sauces.
  // Aquafaba (chickpea water) is the most reliable allergen-safe binder substitute.
  {
    id: 'eggs',
    displayName: 'Eggs',
    tier: 'major_allergen',
    aliases: [
      'egg',
      'eggs',
      'egg free',
      'egg-free',
      'egg allergy',
    ],
    derivedIngredients: [
      'mayonnaise',
      'egg wash',
      'meringue',
      'omelette',
      'frittata',
      'hollandaise',
      'quiche',
      'aioli',
    ],
    hiddenIngredients: [
      'brioche',
      'caesar dressing',
      'fresh pasta',
    ],
    substitutions: [
      'aquafaba',
      'flax egg (1 tbsp ground flaxseed + 3 tbsp water)',
      'chia egg (1 tbsp chia seeds + 3 tbsp water)',
      'yoghurt (check dairy restriction)',
      'mashed banana for baking',
    ],
    prohibitedPhrases: [
      'egg',
      'mayonnaise',
      'egg wash',
      'meringue',
    ],
  },

  // ── COCONUT ─────────────────────────────────────────────────────────────────
  //
  // Not a UK major allergen but a common additional restriction.
  // Coconut allergy is distinct from tree nut allergy, though some allergists
  // recommend caution for tree-nut-allergic individuals.
  // Tier: additional_restriction (not a statutory major allergen in UK law).
  {
    id: 'coconut',
    displayName: 'Coconut',
    tier: 'additional_restriction',
    aliases: [
      'coconut',
      'coconut free',
      'coconut-free',
      'coconut allergy',
    ],
    derivedIngredients: [
      'coconut milk',
      'coconut cream',
      'coconut oil',
      'desiccated coconut',
      'coconut yoghurt',
      'coconut flakes',
      'coconut flour',
      'coconut water',
      'coconut butter',
      'coconut sugar',
      'coconut aminos',
    ],
    hiddenIngredients: [],
    substitutions: [
      'oat cream (check gluten restriction)',
      'dairy cream (check dairy restriction)',
      'almond milk (check tree nut restriction)',
      'oat milk (check gluten restriction)',
    ],
    prohibitedPhrases: [
      'coconut',
    ],
  },

];
