/**
 * restriction-library.ts
 * ======================
 * Canonical restriction definitions.
 *
 * Phase 3 scope: peanut, tree_nut (split from Phase 2 nut_free), sesame, soy,
 * mustard, shellfish, eggs, coconut — plus preserved gluten and dairy.
 * Phase 4 scope (SURF1B2): meat, fish, honey — the three values THA accepted and
 * stored as hard restrictions while this library defined nothing for them.
 * Phase 5 scope (SURF1B4): no new definition. The Vegan and Vegetarian diet
 * PATTERNS now resolve their hard exclusions here instead of from the private
 * keyword lists `dietRules` used to hold, so this library became the single owner
 * of "what is meat", "what is fish" and "what is dairy" for every gate in THA.
 * Everything those retired lists knew and this one did not was folded in — the
 * named cheeses (`dairy`) and the meat dish names (`meat`) — and everything they
 * got wrong was left behind. A test asserts the superset in both directions.
 *
 * nut_free is no longer a canonical definition. Backward compatibility is
 * handled in the resolver via LEGACY_ALIAS_EXPANSIONS.
 *
 * Authoring rules:
 * - All definitions must be human-authored and reviewed before merging.
 * - Never generated by AI or the database.
 * - Empty arrays are valid where data does not yet exist.
 * - derivedIngredients: products made FROM the allergen (indirect sources).
 * - hiddenIngredients: products where the allergen is not obvious by name.
 * - substitutions: for display and future recommendation only; not used in matching.
 *   Include cross-restriction caveats inline (e.g. "tahini (check sesame restriction)").
 * - prohibitedPhrases: for future post-generation content validation only.
 *
 * ── WHICH FIELD A TERM BELONGS IN (read before adding one) ───────────────────
 * The resolver matches each field differently, and putting a term in the wrong
 * field is how a false positive gets shipped. See restriction-resolver.ts.
 *
 *   aliases            → WHOLE-WORD match (`wordBoundaryIncludes`).
 *                        Safe for short words that are substrings of unrelated
 *                        foods: "ham" here cannot match "chamomile", and "lamb"
 *                        cannot match "lambrusco".
 *                        Aliases ALSO resolve a declared restriction string to
 *                        this definition (`findRestrictionByAlias`), so every
 *                        term here is a name a household could reasonably declare.
 *
 *   derivedIngredients → FORWARD SUBSTRING match.
 *   hiddenIngredients    Handles plurals and compounds for free ("sausage"
 *                        catches "sausages"), but a short entry is dangerous:
 *                        "ham" here WOULD match "chamomile". Use for distinctive
 *                        words (≥5–6 chars) and multi-word phrases only.
 *
 *   excludedCompounds  → SUBSTRING, and an UNCONDITIONAL EARLY EXIT for the whole
 *                        definition. Add a compound here ONLY when a match would
 *                        otherwise wrongly occur ("kidney beans" would match the
 *                        `meat` alias "kidney"; "honeydew" would not match "honey"
 *                        at all, so it does not belong here). Every unnecessary
 *                        entry is a fail-OPEN path: an ingredient string containing
 *                        both an excluded compound and a genuine allergen exits
 *                        before the allergen is seen.
 *
 * Phase 5 candidates: celery, lupin, sulphites, alcohol, pork-only (Halal/Kosher).
 */

import type { RestrictionDefinition } from './restriction-types.js';

export const RESTRICTION_LIBRARY_VERSION = '5.0.0';

export const RESTRICTION_DEFINITIONS: RestrictionDefinition[] = [

  // ── GLUTEN ──────────────────────────────────────────────────────────────────
  //
  // Covers wheat, barley, rye, and their derivatives.
  // Coeliac disease and non-coeliac gluten sensitivity are both mapped here.
  {
    id: 'gluten',
    displayName: 'Gluten',
    tier: 'major_allergen',
    aliases: [
      'gluten',
      'gluten free',
      'gluten-free',
      'wheat',
      'wheat free',
      'wheat-free',
      'coeliac',
      'celiac',
    ],
    derivedIngredients: [
      'wholemeal',
      'wholegrain',
      'bulgur wheat',
      'bulgur',
      'couscous',
      'semolina',
      'spelt',
      'barley',
      'rye',
      'durum',
      'farro',
      'freekeh',
      'kamut',
      'flour',
      'bread',
      'pasta',
      'noodles',
      'tortilla',
      'panko',
    ],
    hiddenIngredients: [
      'soy sauce',
      'malt vinegar',
      'worcestershire sauce',
      'beer',
      'barley malt',
      'malt extract',
      'hoisin sauce',
      'teriyaki sauce',
    ],
    substitutions: [
      'gluten-free pasta',
      'gluten-free bread',
      'rice flour',
      'cornflour',
      'rice noodles',
      'buckwheat',
      'quinoa',
    ],
    prohibitedPhrases: [
      'wheat flour',
      'plain flour',
      'self-raising flour',
      'breadcrumbs',
      'pasta',
      'barley',
      'rye bread',
      'spelt',
    ],
  },

  // ── DAIRY ───────────────────────────────────────────────────────────────────
  //
  // Covers cow's milk protein allergy and lactose intolerance.
  //
  // Phase 5 (SURF1B4): the named cheeses were added. Until then this definition
  // held `cheese` and nothing else, while `dietRules.DAIRY_KEYWORDS` — the second
  // owner the Vegan pattern used — knew cheddar, mozzarella, feta, halloumi and
  // paneer. A Dairy-Free household could be served a halloumi salad by the
  // canonical path, because the canonical path had never been told what halloumi is.
  // The pattern path now delegates here, so this definition must know every dairy
  // food THA knows. A test asserts the superset.
  {
    id: 'dairy',
    displayName: 'Dairy',
    tier: 'major_allergen',
    aliases: [
      'dairy',
      'dairy free',
      'dairy-free',
      'milk',
      'milk free',
      'milk-free',
      'lactose',
      'lactose free',
      'lactose-free',
      'lactose intolerant',
      // Short cheese names — whole-word only. As derivedIngredients these would be
      // substring-matched and "brie" would match "brief", "edam" would match
      // "edamame", and "feta" would match nothing safely.
      'brie',
      'feta',
      'edam',
    ],
    derivedIngredients: [
      'butter',
      'cream',
      'yoghurt',
      'yogurt',
      'cheese',
      'ghee',
      'whey',
      'casein',
      'creme fraiche',
      'fromage frais',
      'sour cream',
      'double cream',
      'single cream',
      'clotted cream',
      'custard',
      'condensed milk',
      'evaporated milk',
      'buttermilk',
      // Named cheeses — distinctive words, safe as substrings, plurals free.
      'cheddar',
      'mozzarella',
      'parmesan',
      'parmigiano',
      'pecorino',
      'gorgonzola',
      'camembert',
      'ricotta',
      'mascarpone',
      'halloumi',
      'paneer',
      'stilton',
      'gruyere',
      'gouda',
      'burrata',
      'emmental',
      'manchego',
      'provolone',
      'wensleydale',
      // Other dairy products
      'kefir',
      'quark',
      'skyr',
    ],
    hiddenIngredients: [
      'milk chocolate',
      'white chocolate',
      'caramel',
    ],
    substitutions: [
      'oat milk',
      'plant-based milk',
      'coconut cream (check coconut restriction)',
      'dairy-free yoghurt',
      'vegan butter',
      'olive oil',
    ],
    prohibitedPhrases: [
      'milk',
      'butter',
      'cream',
      'cheese',
      'yoghurt',
      'yogurt',
      'ghee',
    ],
    excludedCompounds: [
      // Plant milks — contain "milk" alias but are dairy-free by definition
      'coconut milk',
      'oat milk',
      'rice milk',
      'almond milk',
      'cashew milk',
      'hemp milk',
      'pea milk',
      'soy milk',
      'soya milk',
      'hazelnut milk',
      'macadamia milk',
      'plant milk',
      'plant-based milk',
      'oat mylk',
      // Plant creams — contain "cream" derivedIngredient but are dairy-free by definition
      'coconut cream',
      'oat cream',
      'soya cream',
      'soy cream',
      'almond cream',
      'cashew cream',
      'rice cream',

      // ── Foods that merely SHARE A WORD with a dairy term (SURF1B4). Each of
      //    these was a live FALSE exclusion: the substring "butter" is inside
      //    "butternut squash", and a dairy-free household was refused a squash soup.
      'butternut',        // butternut squash — a vegetable
      'butter bean',      // a legume
      'butter beans',
      'butterbean',
      'butterbeans',
      'butterhead',       // a lettuce
      'butterfly',        // "butterflied" chicken — a cut, not a dairy product
      'peanut butter',    // nut and seed butters — no dairy in any of them
      'almond butter',
      'cashew butter',
      'hazelnut butter',
      'nut butter',
      'seed butter',
      'sunflower seed butter',
      'pumpkin seed butter',
      'coconut butter',
      'cocoa butter',
      'shea butter',
      'apple butter',
      'cream of tartar',  // a plant-derived acid salt

      // ── Plant-based analogues. A dairy-free product must never be excluded from
      //    a household avoiding dairy — that is the entire purpose of it.
      'dairy free',
      'dairy-free',
      'non dairy',
      'non-dairy',
      'vegan cheese',
      'vegan cheddar',
      'vegan mozzarella',
      'vegan parmesan',
      'vegetarian parmesan',
      'vegan feta',
      'vegan brie',
      'plant based cheese',
      'plant-based cheese',
      'cashew cheese',
      'nut cheese',
      'vegan butter',
      'plant butter',
      'vegan cream',
      'vegan yoghurt',
      'vegan yogurt',
      'coconut yoghurt',
      'coconut yogurt',
      'soy yoghurt',
      'soy yogurt',
      'soya yoghurt',
      'oat yoghurt',
      'oat yogurt',
      'almond yoghurt',
      'almond yogurt',
      'vegan ice cream',
      'vegan custard',
    ],
  },

  // ── PEANUT ──────────────────────────────────────────────────────────────────
  //
  // Peanuts are a legume, not a tree nut — a distinct allergen and medical category.
  // Separated from tree_nut in Phase 3. Backward compat: "nut_free" expands to
  // both peanut + tree_nut via LEGACY_ALIAS_EXPANSIONS in the resolver.
  {
    id: 'peanut',
    displayName: 'Peanut',
    tier: 'major_allergen',
    aliases: [
      'peanut',
      'peanuts',
      'groundnut',
      'groundnuts',
      'peanut free',
      'peanut-free',
      'peanut allergy',
    ],
    derivedIngredients: [
      'peanut butter',
      'peanut oil',
      'peanut sauce',
      'groundnut oil',
    ],
    hiddenIngredients: [
      'satay sauce',
      'satay',
      'pad thai sauce',
    ],
    substitutions: [
      'sunflower seed butter',
      'tahini (check sesame restriction)',
      'seed butter',
    ],
    prohibitedPhrases: [
      'peanut',
      'groundnut',
    ],
  },

  // ── TREE_NUT ─────────────────────────────────────────────────────────────────
  //
  // Covers all tree nuts. Cross-contamination between tree nut varieties means
  // allergic households often restrict all. Individual nuts are listed in
  // derivedIngredients so "almond milk" and "walnut pesto" are both caught.
  // Separated from peanut in Phase 3.
  {
    id: 'tree_nut',
    displayName: 'Tree Nuts',
    tier: 'major_allergen',
    aliases: [
      'tree nut',
      'tree nuts',
      'tree-nut',
      'tree nut allergy',
      'tree nut free',
      'tree-nut-free',
    ],
    derivedIngredients: [
      // Almonds
      'almond',
      'almonds',
      'almond milk',
      'almond flour',
      'almond butter',
      // Cashews
      'cashew',
      'cashews',
      'cashew butter',
      'cashew cream',
      // Walnuts
      'walnut',
      'walnuts',
      // Hazelnuts
      'hazelnut',
      'hazelnuts',
      'hazelnut spread',
      // Pecans
      'pecan',
      'pecans',
      // Pistachios
      'pistachio',
      'pistachios',
      // Macadamia
      'macadamia',
      // Brazil nuts
      'brazil nut',
      'brazil nuts',
      // Pine nuts
      'pine nut',
      'pine nuts',
      // Derived products
      'nut butter',
      'marzipan',
      'praline',
      'nougat',
      'frangipane',
    ],
    hiddenIngredients: [
      'pesto',
      'romesco sauce',
    ],
    substitutions: [
      'seed butter',
      'sunflower seeds',
      'pumpkin seeds',
    ],
    prohibitedPhrases: [
      'almond',
      'cashew',
      'walnut',
      'pecan',
      'hazelnut',
      'pistachio',
      'brazil nut',
      'pine nut',
      'macadamia',
      'praline',
      'marzipan',
    ],
  },

  // ── SESAME ──────────────────────────────────────────────────────────────────
  //
  // UK major allergen since 2021. Tahini is the most common hidden sesame source.
  // Hummus typically contains tahini — listed in hiddenIngredients as a caution.
  {
    id: 'sesame',
    displayName: 'Sesame',
    tier: 'major_allergen',
    aliases: [
      'sesame',
      'sesame seed',
      'sesame seeds',
      'sesame-free',
      'sesame free',
    ],
    derivedIngredients: [
      'tahini',
      'sesame oil',
      'toasted sesame oil',
      'sesame paste',
      'sesame dressing',
      'sesame butter',
    ],
    hiddenIngredients: [
      'hummus',
    ],
    substitutions: [
      'sunflower seed butter',
      'pumpkin seed butter',
      'olive oil',
    ],
    prohibitedPhrases: [
      'sesame',
      'tahini',
      'sesame oil',
    ],
  },

  // ── SOY ─────────────────────────────────────────────────────────────────────
  //
  // Covers soy protein allergy and soya intolerance.
  // Note: soy sauce also contains gluten — both restrictions may flag it.
  // Word-boundary matching prevents "soy" matching "savoy cabbage".
  {
    id: 'soy',
    displayName: 'Soy',
    tier: 'major_allergen',
    aliases: [
      'soy',
      'soya',
      // Whole bean forms — wordBoundaryIncludes("soy") does not match "soybean"
      // because 'b' follows 'soy' without a word boundary. These must be listed
      // explicitly so "soybeans" in an ingredient list is caught.
      'soybean',
      'soybeans',
      'soya bean',
      'soya beans',
      'soy bean',
      'soy beans',
      'soy free',
      'soy-free',
      'soya free',
      'soya-free',
      'soy allergy',
    ],
    derivedIngredients: [
      'soy sauce',
      'soya sauce',
      'tofu',
      'tempeh',
      'edamame',
      'miso',
      'soy milk',
      'soya milk',
      'tamari',
      'soy cream',
      'soya cream',
      'soy flour',
    ],
    hiddenIngredients: [],
    substitutions: [
      'coconut aminos (check coconut restriction)',
      'salt, lemon juice, or stock alternatives',
    ],
    prohibitedPhrases: [
      'soy sauce',
      'tofu',
      'miso',
      'edamame',
    ],
  },

  // ── MUSTARD ─────────────────────────────────────────────────────────────────
  //
  // UK major allergen. Mustard can cause severe reactions in sensitised individuals.
  // All mustard-containing products share "mustard" in their name — alias matching
  // is generally sufficient; few hidden sources.
  {
    id: 'mustard',
    displayName: 'Mustard',
    tier: 'major_allergen',
    aliases: [
      'mustard',
      'mustard-free',
      'mustard free',
      'mustard allergy',
    ],
    derivedIngredients: [
      'mustard powder',
      'mustard seeds',
      'mustard seed',
      'dijon mustard',
      'english mustard',
      'wholegrain mustard',
      'whole grain mustard',
      'mustard oil',
      'mustard paste',
      'french mustard',
      'american mustard',
      'yellow mustard',
    ],
    hiddenIngredients: [],
    substitutions: [
      'horseradish',
      'wasabi',
      'herbs and spices depending on recipe',
    ],
    prohibitedPhrases: [
      'mustard',
    ],
  },

  // ── SHELLFISH ────────────────────────────────────────────────────────────────
  //
  // Covers crustaceans and molluscs together, as UK labelling law treats them
  // as a combined major allergen category. Oyster sauce is a common hidden source.
  {
    id: 'shellfish',
    displayName: 'Shellfish',
    tier: 'major_allergen',
    aliases: [
      'shellfish',
      'shellfish-free',
      'crustacean',
      'crustaceans',
      'mollusc',
      'molluscs',
      'mollusk',
      'mollusks',
      'shellfish allergy',
    ],
    derivedIngredients: [
      'prawn',
      'prawns',
      'shrimp',
      'crab',
      'lobster',
      'mussel',
      'mussels',
      'clam',
      'clams',
      'scallop',
      'scallops',
      'oyster',
      'oysters',
      'langoustine',
      'langoustines',
      'crayfish',
      'squid',
      'calamari',
      'octopus',
    ],
    hiddenIngredients: [
      'oyster sauce',
      'prawn crackers',
      'seafood sauce',
    ],
    substitutions: [
      'chicken',
      'mushrooms',
      'white fish (check fish restriction)',
      'tofu (check soy restriction)',
    ],
    prohibitedPhrases: [
      'prawn',
      'shrimp',
      'crab',
      'lobster',
      'shellfish',
      'mussel',
      'clam',
      'scallop',
      'oyster',
    ],
  },

  // ── EGGS ────────────────────────────────────────────────────────────────────
  //
  // Covers hen's egg allergy. Eggs appear in many forms in baking and sauces.
  // Aquafaba (chickpea water) is the most reliable allergen-safe binder substitute.
  {
    id: 'eggs',
    displayName: 'Eggs',
    tier: 'major_allergen',
    aliases: [
      'egg',
      'eggs',
      'egg free',
      'egg-free',
      'egg allergy',
    ],
    derivedIngredients: [
      'mayonnaise',
      'egg wash',
      'meringue',
      'omelette',
      'frittata',
      'hollandaise',
      'quiche',
      'aioli',
    ],
    hiddenIngredients: [
      'brioche',
      'caesar dressing',
      'fresh pasta',
    ],
    substitutions: [
      'aquafaba',
      'flax egg (1 tbsp ground flaxseed + 3 tbsp water)',
      'chia egg (1 tbsp chia seeds + 3 tbsp water)',
      'yoghurt (check dairy restriction)',
      'mashed banana for baking',
    ],
    prohibitedPhrases: [
      'egg',
      'mayonnaise',
      'egg wash',
      'meringue',
    ],
    excludedCompounds: [
      // Egg-free products and vegan binders (SURF1B4). Note "eggplant" is NOT here:
      // the alias match is whole-word and cannot reach it, and an unnecessary
      // excludedCompound is a fail-open path, not a free safety net.
      'egg free',
      'egg-free',
      'eggless',
      'vegan egg',
      'egg substitute',
      'egg replacer',
      'egg replacement',
      'flax egg',
      'chia egg',
      'vegan mayonnaise',
      'vegan mayo',
      'egg free mayonnaise',
      'vegan meringue',
      'vegan omelette',
      'vegan frittata',
      'vegan quiche',
      'vegan aioli',
    ],
  },

  // ── COCONUT ─────────────────────────────────────────────────────────────────
  //
  // Not a UK major allergen but a common additional restriction.
  // Coconut allergy is distinct from tree nut allergy, though some allergists
  // recommend caution for tree-nut-allergic individuals.
  // Tier: additional_restriction (not a statutory major allergen in UK law).
  {
    id: 'coconut',
    displayName: 'Coconut',
    tier: 'additional_restriction',
    aliases: [
      'coconut',
      'coconut free',
      'coconut-free',
      'coconut allergy',
    ],
    derivedIngredients: [
      'coconut milk',
      'coconut cream',
      'coconut oil',
      'desiccated coconut',
      'coconut yoghurt',
      'coconut flakes',
      'coconut flour',
      'coconut water',
      'coconut butter',
      'coconut sugar',
      'coconut aminos',
    ],
    hiddenIngredients: [],
    substitutions: [
      'oat cream (check gluten restriction)',
      'dairy cream (check dairy restriction)',
      'almond milk (check tree nut restriction)',
      'oat milk (check gluten restriction)',
    ],
    prohibitedPhrases: [
      'coconut',
    ],
  },

  // ── FISH ────────────────────────────────────────────────────────────────────
  //
  // UK/EU statutory major allergen (finned fish). Added in Phase 4 (SURF1B2):
  // `fish` was an accepted, stored hard restriction with no definition here, so it
  // was enforced only by a conservative substring fallback that caught "fish pie"
  // and not "salmon".
  //
  // BOUNDARY — fish is NOT shellfish. They are separate allergens in law and in
  // medicine: a fish-allergic person is not necessarily shellfish-allergic, and
  // vice versa. `shellfish` above is the canonical owner of crustaceans and
  // molluscs, and this definition must never claim them. The word-boundary alias
  // match already keeps "fish" from matching "shellfish"; note that "shellfish"
  // is deliberately NOT an excludedCompound here, because an excludedCompound is
  // an unconditional early exit and would make "shellfish and cod chowder" miss
  // the cod.
  //
  // The most valuable knowledge in this entry is `hiddenIngredients`. Anchovy is
  // the reason Worcestershire sauce, Caesar dressing and puttanesca are unsafe,
  // and none of them says "fish" anywhere in the name.
  {
    id: 'fish',
    displayName: 'Fish',
    tier: 'major_allergen',
    aliases: [
      'fish',
      'fish free',
      'fish-free',
      'fish allergy',
      'finfish',
      'white fish',
      'oily fish',
      // Short fish names — whole-word only. As derivedIngredients these would be
      // substring-matched and "cod" would match nothing safely.
      'cod',
      'hake',
      'sole',
      'bass',
      'carp',
      'eel',
      'roe',
    ],
    derivedIngredients: [
      'salmon',
      'smoked salmon',
      'tuna',
      'haddock',
      'smoked haddock',
      'halibut',
      'trout',
      'mackerel',
      'sardine',
      'sardines',
      'anchovy',
      'anchovies',
      'pilchard',
      'herring',
      'kipper',
      'whitebait',
      'tilapia',
      'snapper',
      'monkfish',
      'swordfish',
      'pollock',
      'pollack',
      'plaice',
      'seabream',
      'sea bream',
      'sea bass',
      'turbot',
      'coley',
      'catfish',
      'barramundi',
      'lemon sole',
      'dover sole',
      // Products
      'fish sauce',
      'fish stock',
      'fish finger',
      'fish fingers',
      'fishcake',
      'fishcakes',
      'fish cake',
      'fish cakes',
      'fish pie',
      'seafood',
      'caviar',
      'bottarga',
      'gravlax',
      'surimi',
    ],
    hiddenIngredients: [
      // Anchovy is the hidden fish in every one of these.
      'worcestershire sauce',
      'caesar dressing',
      'caesar salad',
      'puttanesca',
      'gentlemans relish',
      "gentleman's relish",
      'nam pla',
      'nuoc mam',
      'kedgeree',
      'bouillabaisse',
      'taramasalata',
    ],
    substitutions: [
      'chicken (check meat restriction)',
      'tofu (check soy restriction)',
      'jackfruit',
      'hearts of palm',
      'tamari or coconut aminos in place of fish sauce',
    ],
    prohibitedPhrases: [
      'fish',
      'salmon',
      'tuna',
      'cod',
      'anchovy',
      'anchovies',
      'fish sauce',
      'worcestershire sauce',
    ],
    excludedCompounds: [
      // Plant-based analogues and explicitly fish-free products. Without these,
      // "vegan fish fingers" would be excluded from a fish-allergic household.
      'fish free',
      'fish-free',
      'vegan fish',
      'vegetarian fish',
      'plant based fish',
      'plant-based fish',
      'fishless',
      'tofish',
      'mock fish',
      'vegan tuna',
      'vegan salmon',
      'vegan caviar',
    ],
  },

  // ── MEAT ────────────────────────────────────────────────────────────────────
  //
  // Not an allergen — an ethical, religious or dietary restriction. Added in
  // Phase 4 (SURF1B2): live households declare `meat` as a hard restriction and it
  // resolved to nothing, so the substring fallback caught "meatball" and not "beef".
  //
  // BOUNDARY — `meat` is the flesh of LAND animals, and deliberately does NOT
  // include fish or shellfish. THA's own data declares them separately (households
  // 181–184 carry `{meat, fish, dairy, eggs, honey}`), and folding fish into meat
  // would silently break pescatarians, a diet THA offers. A household that eats
  // neither declares both — and both now resolve.
  //
  // Tier is `additional_restriction`, not `major_allergen`: this is a choice, not
  // an anaphylaxis risk. It is enforced exactly as hard as an allergen — the tier
  // describes what the restriction IS, not how strictly it binds.
  //
  // OWNERSHIP — this is now the ONLY definition of "what is meat" in THA. Until
  // SURF1B4, `shared/dietRules.ts` held a rival MEAT_KEYWORDS list serving the Vegan
  // and Vegetarian *patterns*, and it did not know `prosciutto`, `pancetta`,
  // `gammon`, `mutton`, `gelatine`, `bone broth` or `foie gras` — so a vegan
  // household could be recommended a prosciutto dish while a household declaring the
  // `meat` restriction could not. That list is **deleted**, both patterns resolve
  // here, and a test fails if a meat keyword ever reappears in `dietRules`.
  {
    id: 'meat',
    displayName: 'Meat',
    tier: 'additional_restriction',
    aliases: [
      'meat',
      'meat free',
      'meat-free',
      'no meat',
      'red meat',
      'white meat',
      // Short animal names — whole-word only. "ham" as a derivedIngredient would
      // substring-match "chamomile"; "lamb" would match "lambrusco".
      'beef',
      'pork',
      'lamb',
      'ham',
      'veal',
      'duck',
      'goat',
      'goose',
      'quail',
      'hare',
      'boar',
      'mutton',
      'gammon',
      'offal',
      'tripe',
      'mince',
      'rib',
      'ribs',
      'steak',
      'liver',
      'kidney',
      'lard',
      'suet',
      'aspic',
      'rennet',
      'pate',
      'poultry',
    ],
    derivedIngredients: [
      // Distinctive words — substring matching is safe and handles plurals.
      'chicken',
      'turkey',
      'venison',
      'rabbit',
      'pheasant',
      'partridge',
      'bacon',
      'lardon',
      'sausage',
      'salami',
      'chorizo',
      'pepperoni',
      'prosciutto',
      'pancetta',
      'bresaola',
      'guanciale',
      'pastrami',
      'corned beef',
      'meatball',
      'meatloaf',
      'brisket',
      'sirloin',
      'ribeye',
      'rib eye',
      'tenderloin',
      'drumstick',
      'oxtail',
      'hamburger',
      'pulled pork',
      'liverwurst',
      'haggis',
      'black pudding',
      'white pudding',
      'foie gras',
      'pâté',
      'jerky',
      'biltong',
      'gelatin',
      'gelatine',
      'dripping',
      'schmaltz',
      'bone broth',
      'beef stock',
      'chicken stock',
      'beef broth',
      'chicken broth',
      'meat stock',
      'chicken fat',
      'duck fat',
      'goose fat',
    ],
    hiddenIngredients: [
      // Animal-derived and not obvious from the name.
      'worcestershire sauce',
      'caesar dressing',
      'parmesan',
      'pepsin',
      'carmine',
      'cochineal',
      // Dish names that imply meat even when no ingredient list exists at all —
      // the case of a title-only external candidate. Moved here from
      // `dietRules.DISH_NAME_MEAT_OR_SEAFOOD` (SURF1B4), which was the second owner
      // of this fact and reachable only from the Vegan and Vegetarian patterns.
      // A household declaring the `meat` RESTRICTION was offered a carbonara.
      // "ragu" catches "ragù" via the resolver's diacritic folding.
      'carbonara',   // pancetta or bacon (and eggs, and parmesan)
      'bolognese',   // beef and pork mince
      'ragu',        // an Italian meat sauce
      'birria',      // braised beef or goat
      'ossobuco',    // braised veal shank
      'osso buco',
    ],
    substitutions: [
      'tofu (check soy restriction)',
      'tempeh (check soy restriction)',
      'jackfruit',
      'lentils',
      'chickpeas',
      'mushrooms',
      'vegetable stock in place of meat stock',
      'agar in place of gelatine',
    ],
    prohibitedPhrases: [
      'meat',
      'beef',
      'pork',
      'chicken',
      'lamb',
      'bacon',
      'sausage',
      'gelatine',
    ],
    excludedCompounds: [
      // ── Non-meat foods that share a word with a meat term. Without these the
      //    definition excludes staples that contain no animal at all.
      'kidney bean',      // "kidney" — a vegan staple
      'kidney beans',
      'beef tomato',      // "beef" — a tomato variety
      'beef tomatoes',
      'lambs lettuce',    // "lamb" — a salad leaf
      "lamb's lettuce",
      'lamb lettuce',
      'goat cheese',      // "goat" — dairy, not meat
      'goats cheese',
      "goat's cheese",
      'goat milk',
      'goats milk',
      "goat's milk",
      'goat yoghurt',
      'goat yogurt',
      'goats curd',
      'duck egg',         // "duck" — an egg, not meat
      'duck eggs',
      'quail egg',        // "quail" — an egg, not meat
      'quail eggs',
      'mince pie',        // "mince" — fruit mincemeat, not meat
      'mince pies',
      'mincemeat',
      'chicken of the woods',  // a mushroom
      'coconut meat',     // "meat" — the flesh of a coconut
      'nut meat',
      'hamburger bun',    // "hamburger" — the bun is bread; it carries no meat
      'burger bun',
      'vegetable suet',   // "suet" — vegetarian suet is real and common
      'vegetarian suet',
      'vegan suet',
      'vegetarian rennet',  // "rennet" — microbial rennet is not animal-derived
      'microbial rennet',
      'vegetable rennet',
      'vegan rennet',
      'cauliflower steak',  // "steak" — a vegetable
      'mushroom steak',
      'aubergine steak',
      'tofu steak',
      'vegetarian parmesan',
      'vegan parmesan',

      // ── Plant-based analogues. A meat-free product must never be excluded from
      //    a household that is avoiding meat — that is the whole point of it.
      'meat free',
      'meat-free',
      'meatless',
      'meat substitute',
      'meat alternative',
      'quorn',
      'jackfruit',
      'beyond meat',
      'beyond burger',
      'impossible burger',
      'vegan sausage',
      'vegetarian sausage',
      'veggie sausage',
      'plant based sausage',
      'plant-based sausage',
      'vegan bacon',
      'vegetarian bacon',
      'tempeh bacon',
      'coconut bacon',
      'mushroom bacon',
      'facon',
      'vegan chicken',
      'vegetarian chicken',
      'plant based chicken',
      'plant-based chicken',
      'mock chicken',
      'vegan beef',
      'plant based beef',
      'plant-based beef',
      'vegan duck',
      'mock duck',
      'vegan mince',
      'vegetarian mince',
      'veggie mince',
      'plant based mince',
      'plant-based mince',
      'soy mince',
      'soya mince',
      'vegan meatball',
      'vegetarian meatball',
      'plant based meatball',
      'plant-based meatball',
      'vegan chorizo',
      'vegan pepperoni',
      'vegan salami',
      'vegan ham',
      'vegetarian ham',
      'vegan steak',
      'plant based steak',
      'plant-based steak',
      'vegan pate',
      'vegetarian pate',
      'mushroom pate',
      'lentil pate',
      'vegan haggis',
      'vegetarian haggis',
      'vegan gelatin',
      'vegetarian gelatine',
      'vegan pastrami',

      // Meat-free versions of the dish names above (SURF1B4). A lentil bolognese
      // and a mushroom ragu are staples of the households this definition protects.
      'vegan bolognese',
      'vegetarian bolognese',
      'lentil bolognese',
      'mushroom bolognese',
      'vegan ragu',
      'vegetarian ragu',
      'lentil ragu',
      'mushroom ragu',
      'vegan carbonara',
      'vegetarian carbonara',
    ],
  },

  // ── HONEY ───────────────────────────────────────────────────────────────────
  //
  // Not an allergen — an ethical restriction (honey is an animal product and is
  // excluded by veganism) and, separately, an infant safety rule: honey must not be
  // given to children under 12 months because of the botulism risk. Added in Phase 4
  // (SURF1B2): live households declare it and it resolved to nothing.
  //
  // Note the excludedCompounds are SHORT. "honeydew" and "honeysuckle" are NOT
  // listed, because the whole-word alias match already cannot match them — and an
  // unnecessary excludedCompound is a fail-open path, not a free safety net.
  {
    id: 'honey',
    displayName: 'Honey',
    tier: 'additional_restriction',
    aliases: [
      'honey',
      'honey free',
      'honey-free',
      'no honey',
      'bee product',
      'bee products',
      // Whole-word: as a derivedIngredient, "mead" would substring-match "meadow".
      'mead',
    ],
    derivedIngredients: [
      'runny honey',
      'clear honey',
      'set honey',
      'raw honey',
      'creamed honey',
      'manuka honey',
      'acacia honey',
      'heather honey',
      'wildflower honey',
      'hot honey',
      'honey syrup',
      'honey glaze',
      'honey mustard',
      'honeycomb',
      'royal jelly',
      'bee pollen',
      'propolis',
      'beeswax',
    ],
    hiddenIngredients: [
      // Traditionally honey-sweetened and rarely labelled as such.
      'baklava',
      'nougat',
      'halva',
      'flapjack',
    ],
    substitutions: [
      'maple syrup',
      'agave nectar',
      'date syrup',
      'golden syrup',
      'brown rice syrup',
    ],
    prohibitedPhrases: [
      'honey',
      'royal jelly',
      'beeswax',
    ],
    excludedCompounds: [
      'honey free',
      'honey-free',
      'vegan honey',
      'honey substitute',
      'bee free',
    ],
  },

];
