/**
 * restriction-types.ts
 * ====================
 * Strongly-typed structures for the canonical restriction library and resolver.
 * Pure types — no runtime logic.
 *
 * Design principles:
 * - RestrictionTier separates mandatory allergen handling from other restrictions.
 * - RestrictionSourceType records the basis for every match, enabling the
 *   future analyser to explain decisions without AI reasoning.
 * - All structures are deterministic: same input always yields same output.
 * - Designed for future expansion — do not add unused fields.
 */

// ─── Tiers ───────────────────────────────────────────────────────────────────

/**
 * major_allergen   — The 14 UK/EU major allergens and equivalent categories.
 *                    Always treated as hard restrictions; never soft preferences.
 * additional_restriction — Other dietary, religious, ethical, or medical
 *                    restrictions that must also be respected.
 */
export type RestrictionTier = 'major_allergen' | 'additional_restriction';

// ─── Source types ─────────────────────────────────────────────────────────────

/**
 * Records the mechanism by which a restriction match was established.
 * Required on every RestrictionMatch so the analyser can explain decisions.
 *
 * alias              — Matched via the restriction's id or a known alias.
 *                      e.g. "coeliac" → gluten, "dairy-free" → dairy.
 * derived_ingredient — Matched via a known product derived from the allergen.
 *                      e.g. "tahini" → sesame (Phase 3), "yoghurt" → dairy.
 * hidden_ingredient  — Matched via an ingredient that contains the allergen
 *                      without it being obvious from the name alone.
 *                      e.g. "soy sauce" → gluten (hidden wheat starch).
 */
export type RestrictionSourceType =
  | 'alias'
  | 'derived_ingredient'
  | 'hidden_ingredient';

// ─── Restriction definition ───────────────────────────────────────────────────

/**
 * A single canonical restriction entry in the library.
 * Human-authored and reviewed — never generated by AI or the database.
 */
export interface RestrictionDefinition {
  /**
   * Stable machine identifier. Snake_case. Never changes once published.
   * Used as the primary key in resolver lookups.
   */
  id: string;

  /** Human-readable name for use in UI and reports. */
  displayName: string;

  /** Whether this is a major allergen or an additional restriction. */
  tier: RestrictionTier;

  /**
   * All strings that, when found in a household's hardRestrictions array,
   * should map to this definition.
   * Includes common spellings, hyphenated forms, and lay terms.
   * Case-insensitive at match time. Hyphens and underscores normalised to spaces.
   * Examples: ["gluten", "gluten-free", "coeliac", "celiac", "wheat"]
   */
  aliases: string[];

  /**
   * Food or ingredient names produced from the restricted substance.
   * Used when the allergen is present but the ingredient name does not
   * contain the allergen keyword.
   * Examples for dairy: ["butter", "yoghurt", "cream", "ghee"]
   * Examples for sesame (Phase 3): ["tahini", "tahini dressing"]
   */
  derivedIngredients: string[];

  /**
   * Ingredients where the allergen is present but not indicated by the name.
   * Often present due to manufacturing or recipe conventions.
   * Examples for gluten: ["soy sauce", "malt vinegar", "worcestershire sauce"]
   */
  hiddenIngredients: string[];

  /**
   * Safe ingredient substitutes for this restriction.
   * For display and future recommendation logic only.
   * Not used in matching.
   */
  substitutions: string[];

  /**
   * Phrases that must not appear in generated content for households
   * with this restriction. For use in future post-generation validation.
   * Not used in matching.
   */
  prohibitedPhrases: string[];
}

// ─── Match result ─────────────────────────────────────────────────────────────

/**
 * A confirmed restriction match with full provenance.
 * Contains enough information for the future analyser to explain the
 * decision without performing any additional reasoning.
 */
export interface RestrictionMatch {
  /** The canonical restriction definition that was matched. */
  restriction: RestrictionDefinition;

  /**
   * The raw input string that triggered the match.
   * For alias lookups: the household restriction string (e.g. "coeliac").
   * For ingredient resolution: the ingredient name (e.g. "tahini dressing").
   */
  matchedTerm: string;

  /** How the match was established. */
  sourceType: RestrictionSourceType;

  /**
   * The specific value in the library entry that produced the match.
   * For alias: the matching alias string or the definition id.
   * For derived_ingredient: the derivedIngredients entry that matched.
   * For hidden_ingredient: the hiddenIngredients entry that matched.
   */
  sourceValue: string;
}
