/**
 * THA Additives — Complete Seed
 *
 * Single source of truth for all additive data used in apple scoring.
 * Covers all common UK supermarket food additives.
 *
 * Fields:
 *   name        — E-number (e.g. "E282"). Used as unique key.
 *   type        — category string used in ADDITIVE_TYPE_RISK lookup
 *   risk_level  — "low" | "moderate" | "high"
 *   description — "Common Name - brief note". First segment (before " - ")
 *                 is used for text-based name matching in detectAdditives().
 *
 * NOTE: Soft UPF terms (natural flavouring, yeast extract, maltodextrin, etc.)
 * are handled in code (upf-analysis-service.ts) — do NOT add them here.
 */

export interface AdditiveSeedRow {
  name: string;
  type: string;
  riskLevel: string;
  description: string;
  /** Marks additives that are present due to a legal/regulatory requirement
   *  rather than a discretionary manufacturing choice (e.g. UK flour
   *  fortification).  Still counted in THA apple scoring. */
  isRegulatory?: boolean;
}

export const ADDITIVES_SEED: AdditiveSeedRow[] = [

  // ─── COLOURINGS ────────────────────────────────────────────────────────────
  { name: "E100",  type: "colouring", riskLevel: "low",      description: "Curcumin - natural yellow colouring from turmeric" },
  { name: "E101",  type: "colouring", riskLevel: "low",      description: "Riboflavin - yellow colouring (Vitamin B2)" },
  { name: "E102",  type: "colouring", riskLevel: "high",     description: "Tartrazine - synthetic yellow dye, linked to hyperactivity" },
  { name: "E104",  type: "colouring", riskLevel: "high",     description: "Quinoline Yellow - synthetic dye" },
  { name: "E110",  type: "colouring", riskLevel: "high",     description: "Sunset Yellow FCF - synthetic orange dye, linked to hyperactivity" },
  { name: "E120",  type: "colouring", riskLevel: "moderate", description: "Cochineal - red colouring from insects" },
  { name: "E122",  type: "colouring", riskLevel: "high",     description: "Carmoisine - synthetic red dye" },
  { name: "E123",  type: "colouring", riskLevel: "high",     description: "Amaranth - synthetic red dye" },
  { name: "E124",  type: "colouring", riskLevel: "high",     description: "Ponceau 4R - synthetic red dye, linked to hyperactivity" },
  { name: "E127",  type: "colouring", riskLevel: "high",     description: "Erythrosine - synthetic red dye" },
  { name: "E128",  type: "colouring", riskLevel: "high",     description: "Red 2G - synthetic red dye" },
  { name: "E129",  type: "colouring", riskLevel: "high",     description: "Allura Red AC - synthetic red dye" },
  { name: "E131",  type: "colouring", riskLevel: "high",     description: "Patent Blue V - synthetic blue dye" },
  { name: "E132",  type: "colouring", riskLevel: "moderate", description: "Indigo Carmine - synthetic blue dye" },
  { name: "E133",  type: "colouring", riskLevel: "moderate", description: "Brilliant Blue FCF - synthetic blue dye" },
  { name: "E140",  type: "colouring", riskLevel: "low",      description: "Chlorophylls - natural green colouring" },
  { name: "E141",  type: "colouring", riskLevel: "low",      description: "Copper Complexes of Chlorophylls - green colouring" },
  { name: "E142",  type: "colouring", riskLevel: "moderate", description: "Green S - synthetic green dye" },
  { name: "E150a", type: "colouring", riskLevel: "low",      description: "Plain Caramel - natural brown colouring" },
  { name: "E150b", type: "colouring", riskLevel: "low",      description: "Caustic Sulphite Caramel - brown colouring" },
  { name: "E150c", type: "colouring", riskLevel: "moderate", description: "Ammonia Caramel - brown colouring" },
  { name: "E150d", type: "colouring", riskLevel: "moderate", description: "Sulphite Ammonia Caramel - processed brown colouring" },
  { name: "E151",  type: "colouring", riskLevel: "moderate", description: "Brilliant Black BN - synthetic black dye" },
  { name: "E153",  type: "colouring", riskLevel: "low",      description: "Vegetable Carbon - natural black colouring" },
  { name: "E155",  type: "colouring", riskLevel: "moderate", description: "Brown HT - synthetic brown dye" },
  { name: "E160a", type: "colouring", riskLevel: "low",      description: "Beta-Carotene - natural orange colouring" },
  { name: "E160b", type: "colouring", riskLevel: "low",      description: "Annatto - natural orange-red colouring" },
  { name: "E160c", type: "colouring", riskLevel: "low",      description: "Paprika Extract - natural red-orange colouring" },
  { name: "E160d", type: "colouring", riskLevel: "low",      description: "Lycopene - natural red colouring from tomatoes" },
  { name: "E161b", type: "colouring", riskLevel: "low",      description: "Lutein - natural yellow colouring" },
  { name: "E162",  type: "colouring", riskLevel: "low",      description: "Beetroot Red - natural red colouring" },
  { name: "E163",  type: "colouring", riskLevel: "low",      description: "Anthocyanins - natural red/purple colouring" },
  { name: "E170",  type: "acidity regulator", riskLevel: "low", description: "Calcium Carbonate - acidity regulator/calcium supplement", isRegulatory: true },
  { name: "E171",  type: "colouring", riskLevel: "high",     description: "Titanium Dioxide - white colouring, safety concerns" },
  { name: "E172",  type: "colouring", riskLevel: "low",      description: "Iron Oxides and Hydroxides - natural mineral colouring" },
  { name: "E174",  type: "colouring", riskLevel: "moderate", description: "Silver - metallic colouring" },
  { name: "E175",  type: "colouring", riskLevel: "moderate", description: "Gold - metallic colouring" },

  // ─── PRESERVATIVES ─────────────────────────────────────────────────────────
  { name: "E200",  type: "preservative", riskLevel: "low",      description: "Sorbic Acid - preservative" },
  { name: "E201",  type: "preservative", riskLevel: "low",      description: "Sodium Sorbate - preservative" },
  { name: "E202",  type: "preservative", riskLevel: "low",      description: "Potassium Sorbate - preservative" },
  { name: "E203",  type: "preservative", riskLevel: "low",      description: "Calcium Sorbate - preservative" },
  { name: "E210",  type: "preservative", riskLevel: "moderate", description: "Benzoic Acid - preservative" },
  { name: "E211",  type: "preservative", riskLevel: "moderate", description: "Sodium Benzoate - preservative, may form benzene" },
  { name: "E212",  type: "preservative", riskLevel: "moderate", description: "Potassium Benzoate - preservative" },
  { name: "E213",  type: "preservative", riskLevel: "moderate", description: "Calcium Benzoate - preservative" },
  { name: "E214",  type: "preservative", riskLevel: "moderate", description: "Ethyl Para-Hydroxybenzoate - preservative (paraben)" },
  { name: "E215",  type: "preservative", riskLevel: "moderate", description: "Sodium Ethyl Para-Hydroxybenzoate - preservative (paraben)" },
  { name: "E218",  type: "preservative", riskLevel: "moderate", description: "Methyl Para-Hydroxybenzoate - preservative (paraben)" },
  { name: "E219",  type: "preservative", riskLevel: "moderate", description: "Sodium Methyl Para-Hydroxybenzoate - preservative (paraben)" },
  { name: "E220",  type: "preservative", riskLevel: "moderate", description: "Sulphur Dioxide - preservative, asthma trigger" },
  { name: "E221",  type: "preservative", riskLevel: "moderate", description: "Sodium Sulphite - preservative" },
  { name: "E222",  type: "preservative", riskLevel: "moderate", description: "Sodium Hydrogen Sulphite - preservative" },
  { name: "E223",  type: "preservative", riskLevel: "moderate", description: "Sodium Metabisulphite - preservative" },
  { name: "E224",  type: "preservative", riskLevel: "moderate", description: "Potassium Metabisulphite - preservative" },
  { name: "E225",  type: "preservative", riskLevel: "moderate", description: "Potassium Sulphite - preservative" },
  { name: "E226",  type: "preservative", riskLevel: "moderate", description: "Calcium Sulphite - preservative" },
  { name: "E227",  type: "preservative", riskLevel: "moderate", description: "Calcium Hydrogen Sulphite - preservative" },
  { name: "E228",  type: "preservative", riskLevel: "moderate", description: "Potassium Hydrogen Sulphite - preservative" },
  { name: "E230",  type: "preservative", riskLevel: "moderate", description: "Biphenyl - surface preservative for citrus" },
  { name: "E231",  type: "preservative", riskLevel: "moderate", description: "Orthophenyl Phenol - surface preservative" },
  { name: "E232",  type: "preservative", riskLevel: "moderate", description: "Sodium Orthophenyl Phenol - surface preservative" },
  { name: "E234",  type: "preservative", riskLevel: "low",      description: "Nisin - natural antimicrobial preservative" },
  { name: "E235",  type: "preservative", riskLevel: "moderate", description: "Natamycin - antifungal preservative" },
  { name: "E239",  type: "preservative", riskLevel: "moderate", description: "Hexamethylene Tetramine - preservative" },
  { name: "E242",  type: "preservative", riskLevel: "low",      description: "Dimethyl Dicarbonate - preservative in soft drinks" },
  { name: "E249",  type: "preservative", riskLevel: "high",     description: "Potassium Nitrite - curing agent, linked to cancer risk" },
  { name: "E250",  type: "preservative", riskLevel: "high",     description: "Sodium Nitrite - curing agent, linked to cancer risk" },
  { name: "E251",  type: "preservative", riskLevel: "high",     description: "Sodium Nitrate - curing agent" },
  { name: "E252",  type: "preservative", riskLevel: "high",     description: "Potassium Nitrate - curing agent" },
  { name: "E260",  type: "acidity regulator", riskLevel: "low", description: "Acetic Acid - acidity regulator, used in sauces, dressings, mayonnaise" },
  { name: "E261",  type: "acidity regulator", riskLevel: "low", description: "Potassium Acetate - acidity regulator" },
  { name: "E262",  type: "acidity regulator", riskLevel: "low", description: "Sodium Diacetate - acidity regulator and preservative" },
  { name: "E263",  type: "acidity regulator", riskLevel: "low", description: "Calcium Acetate - acidity regulator" },
  { name: "E270",  type: "preservative", riskLevel: "low",      description: "Lactic Acid - natural preservative" },
  { name: "E280",  type: "preservative", riskLevel: "low",      description: "Propionic Acid - preservative" },
  { name: "E281",  type: "preservative", riskLevel: "low",      description: "Sodium Propionate - bread preservative" },
  { name: "E282",  type: "preservative", riskLevel: "moderate", description: "Calcium Propionate - bread/wrap preservative, may affect behaviour in sensitive individuals" },
  { name: "E283",  type: "preservative", riskLevel: "low",      description: "Potassium Propionate - preservative" },
  { name: "E284",  type: "preservative", riskLevel: "low",      description: "Boric Acid - preservative for caviar" },
  { name: "E285",  type: "preservative", riskLevel: "low",      description: "Sodium Tetraborate - preservative for caviar" },

  // ─── ANTIOXIDANTS ──────────────────────────────────────────────────────────
  { name: "E300",  type: "antioxidant", riskLevel: "low",      description: "Ascorbic Acid - antioxidant (Vitamin C)" },
  { name: "E301",  type: "antioxidant", riskLevel: "low",      description: "Sodium Ascorbate - antioxidant" },
  { name: "E302",  type: "antioxidant", riskLevel: "low",      description: "Calcium Ascorbate - antioxidant" },
  { name: "E304",  type: "antioxidant", riskLevel: "low",      description: "Fatty Acid Esters of Ascorbic Acid - antioxidant" },
  { name: "E306",  type: "antioxidant", riskLevel: "low",      description: "Tocopherols - natural antioxidant (Vitamin E)" },
  { name: "E307",  type: "antioxidant", riskLevel: "low",      description: "Alpha-Tocopherol - synthetic Vitamin E antioxidant" },
  { name: "E308",  type: "antioxidant", riskLevel: "low",      description: "Gamma-Tocopherol - synthetic antioxidant" },
  { name: "E309",  type: "antioxidant", riskLevel: "low",      description: "Delta-Tocopherol - synthetic antioxidant" },
  { name: "E310",  type: "antioxidant", riskLevel: "moderate", description: "Propyl Gallate - synthetic antioxidant" },
  { name: "E311",  type: "antioxidant", riskLevel: "moderate", description: "Octyl Gallate - synthetic antioxidant" },
  { name: "E312",  type: "antioxidant", riskLevel: "moderate", description: "Dodecyl Gallate - synthetic antioxidant" },
  { name: "E315",  type: "antioxidant", riskLevel: "low",      description: "Erythorbic Acid - antioxidant" },
  { name: "E316",  type: "antioxidant", riskLevel: "low",      description: "Sodium Erythorbate - antioxidant" },
  { name: "E319",  type: "antioxidant", riskLevel: "moderate", description: "Tertiary Butylhydroquinone - synthetic antioxidant (TBHQ)" },
  { name: "E320",  type: "antioxidant", riskLevel: "high",     description: "BHA - butylated hydroxyanisole, synthetic antioxidant" },
  { name: "E321",  type: "antioxidant", riskLevel: "high",     description: "BHT - butylated hydroxytoluene, synthetic antioxidant" },

  // ─── ACIDITY REGULATORS ────────────────────────────────────────────────────
  { name: "E325",  type: "acidity regulator", riskLevel: "low", description: "Sodium Lactate - acidity regulator" },
  { name: "E326",  type: "acidity regulator", riskLevel: "low", description: "Potassium Lactate - acidity regulator" },
  { name: "E327",  type: "acidity regulator", riskLevel: "low", description: "Calcium Lactate - acidity regulator" },
  { name: "E330",  type: "acidity regulator", riskLevel: "low", description: "Citric Acid - acidity regulator" },
  { name: "E331",  type: "acidity regulator", riskLevel: "low", description: "Sodium Citrate - acidity regulator" },
  { name: "E332",  type: "acidity regulator", riskLevel: "low", description: "Potassium Citrate - acidity regulator" },
  { name: "E333",  type: "acidity regulator", riskLevel: "low", description: "Calcium Citrate - acidity regulator" },
  { name: "E334",  type: "acidity regulator", riskLevel: "low", description: "Tartaric Acid - acidity regulator" },
  { name: "E335",  type: "acidity regulator", riskLevel: "low", description: "Sodium Tartrate - acidity regulator" },
  { name: "E336",  type: "acidity regulator", riskLevel: "low", description: "Potassium Tartrate - acidity regulator" },
  { name: "E337",  type: "acidity regulator", riskLevel: "low", description: "Sodium Potassium Tartrate - acidity regulator" },
  { name: "E338",  type: "acidity regulator", riskLevel: "moderate", description: "Phosphoric Acid - acidity regulator in soft drinks" },
  { name: "E339",  type: "acidity regulator", riskLevel: "moderate", description: "Sodium Phosphate - acidity regulator" },
  { name: "E340",  type: "acidity regulator", riskLevel: "moderate", description: "Potassium Phosphate - acidity regulator" },
  { name: "E341",  type: "raising agent",     riskLevel: "low",      description: "Calcium Phosphates - raising agent/acidity regulator" },
  { name: "E343",  type: "acidity regulator", riskLevel: "low",      description: "Magnesium Phosphate - acidity regulator" },
  { name: "E350",  type: "acidity regulator", riskLevel: "low",      description: "Sodium Malate - acidity regulator" },
  { name: "E351",  type: "acidity regulator", riskLevel: "low",      description: "Potassium Malate - acidity regulator" },
  { name: "E352",  type: "acidity regulator", riskLevel: "low",      description: "Calcium Malate - acidity regulator" },
  { name: "E353",  type: "acidity regulator", riskLevel: "low",      description: "Metatartaric Acid - acidity regulator in wine" },
  { name: "E355",  type: "acidity regulator", riskLevel: "low",      description: "Adipic Acid - acidity regulator" },
  { name: "E363",  type: "acidity regulator", riskLevel: "low",      description: "Succinic Acid - acidity regulator" },
  { name: "E380",  type: "acidity regulator", riskLevel: "low",      description: "Triammonium Citrate - acidity regulator" },
  { name: "E385",  type: "acidity regulator", riskLevel: "moderate", description: "Calcium Disodium EDTA - chelating agent" },

  // ─── THICKENERS / STABILISERS / GUMS ──────────────────────────────────────
  { name: "E400",  type: "thickener", riskLevel: "low",      description: "Alginic Acid - thickener from seaweed" },
  { name: "E401",  type: "thickener", riskLevel: "low",      description: "Sodium Alginate - thickener from seaweed" },
  { name: "E402",  type: "thickener", riskLevel: "low",      description: "Potassium Alginate - thickener from seaweed" },
  { name: "E403",  type: "thickener", riskLevel: "low",      description: "Ammonium Alginate - thickener from seaweed" },
  { name: "E404",  type: "thickener", riskLevel: "low",      description: "Calcium Alginate - thickener from seaweed" },
  { name: "E405",  type: "thickener", riskLevel: "low",      description: "Propylene Glycol Alginate - thickener" },
  { name: "E406",  type: "thickener", riskLevel: "low",      description: "Agar - natural gelling agent from seaweed" },
  { name: "E407",  type: "thickener", riskLevel: "moderate", description: "Carrageenan - thickener, digestive concerns" },
  { name: "E407a", type: "thickener", riskLevel: "moderate", description: "Processed Eucheuma Seaweed - thickener, digestive concerns" },
  { name: "E410",  type: "thickener", riskLevel: "low",      description: "Locust Bean Gum - natural thickener" },
  { name: "E412",  type: "thickener", riskLevel: "low",      description: "Guar Gum - natural thickener" },
  { name: "E413",  type: "thickener", riskLevel: "low",      description: "Tragacanth - natural gum thickener" },
  { name: "E414",  type: "thickener", riskLevel: "low",      description: "Gum Arabic - natural thickener" },
  { name: "E415",  type: "thickener", riskLevel: "low",      description: "Xanthan Gum - thickener (fermentation-derived)" },
  { name: "E416",  type: "thickener", riskLevel: "low",      description: "Karaya Gum - natural thickener" },
  { name: "E417",  type: "thickener", riskLevel: "low",      description: "Tara Gum - natural thickener" },
  { name: "E418",  type: "thickener", riskLevel: "low",      description: "Gellan Gum - thickener (fermentation-derived)" },
  { name: "E420",  type: "sweetener", riskLevel: "low",      description: "Sorbitol - sugar alcohol sweetener" },
  { name: "E421",  type: "sweetener", riskLevel: "low",      description: "Mannitol - sugar alcohol sweetener" },
  { name: "E422",  type: "humectant", riskLevel: "low",      description: "Glycerol - humectant" },
  { name: "E425",  type: "thickener", riskLevel: "low",      description: "Konjac - natural thickener/gelling agent" },
  { name: "E426",  type: "thickener", riskLevel: "low",      description: "Soybean Hemicellulose - thickener" },
  { name: "E427",  type: "thickener", riskLevel: "low",      description: "Cassia Gum - natural thickener" },
  { name: "E432",  type: "emulsifier", riskLevel: "moderate", description: "Polyoxyethylene Sorbitan Monolaurate - emulsifier (Polysorbate 20)" },
  { name: "E433",  type: "emulsifier", riskLevel: "moderate", description: "Polyoxyethylene Sorbitan Monooleate - emulsifier (Polysorbate 80)" },
  { name: "E434",  type: "emulsifier", riskLevel: "moderate", description: "Polyoxyethylene Sorbitan Monopalmitate - emulsifier" },
  { name: "E435",  type: "emulsifier", riskLevel: "moderate", description: "Polyoxyethylene Sorbitan Monostearate - emulsifier (Polysorbate 60)" },
  { name: "E436",  type: "emulsifier", riskLevel: "moderate", description: "Polyoxyethylene Sorbitan Tristearate - emulsifier" },
  { name: "E440",  type: "thickener", riskLevel: "low",      description: "Pectin - natural gelling agent from fruit" },
  { name: "E441",  type: "thickener", riskLevel: "low",      description: "Gelatine - gelling agent from animal collagen" },
  { name: "E442",  type: "emulsifier", riskLevel: "low",     description: "Ammonium Phosphatides - emulsifier in chocolate" },
  { name: "E444",  type: "emulsifier", riskLevel: "low",     description: "Sucrose Acetate Isobutyrate - emulsifier" },
  { name: "E445",  type: "emulsifier", riskLevel: "low",     description: "Glycerol Esters of Wood Rosins - emulsifier in drinks" },
  { name: "E450",  type: "emulsifier", riskLevel: "moderate", description: "Diphosphates - emulsifier/raising agent" },
  { name: "E451",  type: "emulsifier", riskLevel: "moderate", description: "Triphosphates - emulsifier" },
  { name: "E452",  type: "emulsifier", riskLevel: "moderate", description: "Polyphosphates - emulsifier, used to retain water in meat" },
  { name: "E459",  type: "emulsifier", riskLevel: "low",     description: "Beta-Cyclodextrin - encapsulating agent" },
  { name: "E460",  type: "anti-caking", riskLevel: "low",    description: "Cellulose - bulking agent/anti-caking" },
  { name: "E461",  type: "thickener",  riskLevel: "moderate", description: "Methylcellulose - thickener" },
  { name: "E462",  type: "thickener",  riskLevel: "low",      description: "Ethylcellulose - thickener" },
  { name: "E463",  type: "thickener",  riskLevel: "low",      description: "Hydroxypropyl Cellulose - thickener" },
  { name: "E464",  type: "thickener",  riskLevel: "low",      description: "Hydroxypropyl Methylcellulose - thickener" },
  { name: "E465",  type: "thickener",  riskLevel: "low",      description: "Methylethylcellulose - thickener" },
  { name: "E466",  type: "thickener",  riskLevel: "moderate", description: "Carboxymethylcellulose - thickener" },
  { name: "E468",  type: "thickener",  riskLevel: "low",      description: "Crosslinked Carboxymethylcellulose - thickener" },
  { name: "E469",  type: "thickener",  riskLevel: "low",      description: "Enzymatically Hydrolysed Carboxymethylcellulose - thickener" },

  // ─── EMULSIFIERS ───────────────────────────────────────────────────────────
  { name: "E322",  type: "emulsifier", riskLevel: "low",      description: "Lecithins - natural emulsifier from soy/sunflower" },
  { name: "E470a", type: "emulsifier", riskLevel: "low",      description: "Sodium, Potassium and Calcium Salts of Fatty Acids - emulsifier" },
  { name: "E470b", type: "emulsifier", riskLevel: "low",      description: "Magnesium Salts of Fatty Acids - emulsifier" },
  { name: "E471",  type: "emulsifier", riskLevel: "moderate", description: "Mono- and Diglycerides of Fatty Acids - emulsifier" },
  { name: "E472a", type: "emulsifier", riskLevel: "low",      description: "Acetic Acid Esters of Mono- and Diglycerides - emulsifier" },
  { name: "E472b", type: "emulsifier", riskLevel: "low",      description: "Lactic Acid Esters of Mono- and Diglycerides - emulsifier" },
  { name: "E472c", type: "emulsifier", riskLevel: "low",      description: "Citric Acid Esters of Mono- and Diglycerides - emulsifier" },
  { name: "E472d", type: "emulsifier", riskLevel: "low",      description: "Tartaric Acid Esters of Mono- and Diglycerides - emulsifier" },
  { name: "E472e", type: "emulsifier", riskLevel: "moderate", description: "DATEM - dough conditioner/emulsifier" },
  { name: "E472f", type: "emulsifier", riskLevel: "moderate", description: "Mixed Acetic and Tartaric Acid Esters of Mono- and Diglycerides - emulsifier" },
  { name: "E473",  type: "emulsifier", riskLevel: "low",      description: "Sucrose Esters of Fatty Acids - emulsifier" },
  { name: "E474",  type: "emulsifier", riskLevel: "low",      description: "Sucroglycerides - emulsifier" },
  { name: "E475",  type: "emulsifier", riskLevel: "low",      description: "Polyglycerol Esters of Fatty Acids - emulsifier" },
  { name: "E476",  type: "emulsifier", riskLevel: "moderate", description: "Polyglycerol Polyricinoleate - emulsifier in chocolate" },
  { name: "E477",  type: "emulsifier", riskLevel: "low",      description: "Propylene Glycol Esters of Fatty Acids - emulsifier" },
  { name: "E479b", type: "emulsifier", riskLevel: "moderate", description: "Thermally Oxidised Soya Bean Oil - emulsifier" },
  { name: "E481",  type: "emulsifier", riskLevel: "moderate", description: "Sodium Stearoyl Lactylate - emulsifier" },
  { name: "E482",  type: "emulsifier", riskLevel: "moderate", description: "Calcium Stearoyl Lactylate - emulsifier" },
  { name: "E483",  type: "emulsifier", riskLevel: "low",      description: "Stearyl Tartrate - emulsifier" },
  { name: "E491",  type: "emulsifier", riskLevel: "moderate", description: "Sorbitan Monostearate - emulsifier" },
  { name: "E492",  type: "emulsifier", riskLevel: "low",      description: "Sorbitan Tristearate - emulsifier" },
  { name: "E493",  type: "emulsifier", riskLevel: "low",      description: "Sorbitan Monolaurate - emulsifier" },
  { name: "E494",  type: "emulsifier", riskLevel: "low",      description: "Sorbitan Monooleate - emulsifier" },
  { name: "E495",  type: "emulsifier", riskLevel: "low",      description: "Sorbitan Monopalmitate - emulsifier" },

  // ─── RAISING AGENTS ────────────────────────────────────────────────────────
  { name: "E500",  type: "raising agent", riskLevel: "low", description: "Sodium Bicarbonate - baking soda/raising agent" },
  { name: "E501",  type: "raising agent", riskLevel: "low", description: "Potassium Carbonates - raising agent" },
  { name: "E503",  type: "raising agent", riskLevel: "low", description: "Ammonium Carbonates - raising agent" },
  { name: "E504",  type: "raising agent", riskLevel: "low", description: "Magnesium Carbonates - raising agent" },

  // ─── ANTI-CAKING AGENTS ────────────────────────────────────────────────────
  { name: "E509",  type: "firming agent",  riskLevel: "low", description: "Calcium Chloride - firming agent" },
  { name: "E516",  type: "firming agent",  riskLevel: "low", description: "Calcium Sulphate - firming agent/flour treatment" },
  { name: "E530",  type: "anti-caking",    riskLevel: "low", description: "Magnesium Oxide - anti-caking agent" },
  { name: "E535",  type: "anti-caking",    riskLevel: "low", description: "Sodium Ferrocyanide - anti-caking in table salt" },
  { name: "E536",  type: "anti-caking",    riskLevel: "low", description: "Potassium Ferrocyanide - anti-caking in table salt" },
  { name: "E538",  type: "anti-caking",    riskLevel: "low", description: "Calcium Ferrocyanide - anti-caking agent" },
  { name: "E541",  type: "raising agent",  riskLevel: "moderate", description: "Sodium Aluminium Phosphate - raising agent in baked goods" },
  { name: "E551",  type: "anti-caking",    riskLevel: "low", description: "Silicon Dioxide - anti-caking agent" },
  { name: "E552",  type: "anti-caking",    riskLevel: "low", description: "Calcium Silicate - anti-caking agent" },
  { name: "E553b", type: "anti-caking",    riskLevel: "low", description: "Talc - anti-caking/coating agent" },
  { name: "E554",  type: "anti-caking",    riskLevel: "low", description: "Sodium Aluminium Silicate - anti-caking agent" },
  { name: "E555",  type: "anti-caking",    riskLevel: "low", description: "Potassium Aluminium Silicate - anti-caking agent" },
  { name: "E556",  type: "anti-caking",    riskLevel: "low", description: "Calcium Aluminium Silicate - anti-caking agent" },
  { name: "E558",  type: "anti-caking",    riskLevel: "low", description: "Bentonite - anti-caking agent" },
  { name: "E559",  type: "anti-caking",    riskLevel: "low", description: "Aluminium Silicate - anti-caking agent" },
  { name: "E570",  type: "anti-caking",    riskLevel: "low", description: "Fatty Acids - anti-caking/glazing agent" },
  { name: "E574",  type: "acidity regulator", riskLevel: "low", description: "Gluconic Acid - acidity regulator" },
  { name: "E575",  type: "acidity regulator", riskLevel: "low", description: "Glucono Delta-Lactone - acidity regulator" },
  { name: "E576",  type: "anti-caking",    riskLevel: "low", description: "Sodium Gluconate - anti-caking/sequestrant" },
  { name: "E577",  type: "anti-caking",    riskLevel: "low", description: "Potassium Gluconate - sequestrant" },
  { name: "E578",  type: "anti-caking",    riskLevel: "low", description: "Calcium Gluconate - firming agent" },
  { name: "E579",  type: "anti-caking",    riskLevel: "low", description: "Ferrous Gluconate - colour stabiliser in olives" },

  // ─── FLAVOUR ENHANCERS ─────────────────────────────────────────────────────
  { name: "E620",  type: "flavour enhancer", riskLevel: "moderate", description: "Glutamic Acid - flavour enhancer" },
  { name: "E621",  type: "flavour enhancer", riskLevel: "moderate", description: "Monosodium Glutamate - flavour enhancer (MSG)" },
  { name: "E622",  type: "flavour enhancer", riskLevel: "moderate", description: "Monopotassium Glutamate - flavour enhancer" },
  { name: "E623",  type: "flavour enhancer", riskLevel: "moderate", description: "Calcium Diglutamate - flavour enhancer" },
  { name: "E624",  type: "flavour enhancer", riskLevel: "moderate", description: "Monoammonium Glutamate - flavour enhancer" },
  { name: "E625",  type: "flavour enhancer", riskLevel: "moderate", description: "Magnesium Diglutamate - flavour enhancer" },
  { name: "E626",  type: "flavour enhancer", riskLevel: "moderate", description: "Guanylic Acid - flavour enhancer" },
  { name: "E627",  type: "flavour enhancer", riskLevel: "moderate", description: "Disodium Guanylate - flavour enhancer" },
  { name: "E628",  type: "flavour enhancer", riskLevel: "moderate", description: "Dipotassium Guanylate - flavour enhancer" },
  { name: "E629",  type: "flavour enhancer", riskLevel: "moderate", description: "Calcium Guanylate - flavour enhancer" },
  { name: "E630",  type: "flavour enhancer", riskLevel: "moderate", description: "Inosinic Acid - flavour enhancer" },
  { name: "E631",  type: "flavour enhancer", riskLevel: "moderate", description: "Disodium Inosinate - flavour enhancer" },
  { name: "E632",  type: "flavour enhancer", riskLevel: "moderate", description: "Dipotassium Inosinate - flavour enhancer" },
  { name: "E633",  type: "flavour enhancer", riskLevel: "moderate", description: "Calcium Inosinate - flavour enhancer" },
  { name: "E634",  type: "flavour enhancer", riskLevel: "moderate", description: "Calcium Ribonucleotides - flavour enhancer" },
  { name: "E635",  type: "flavour enhancer", riskLevel: "moderate", description: "Disodium Ribonucleotides - flavour enhancer" },
  { name: "E640",  type: "flavour enhancer", riskLevel: "low",      description: "Glycine and its Sodium Salt - flavour modifier" },
  { name: "E650",  type: "flavour enhancer", riskLevel: "low",      description: "Zinc Acetate - flavour enhancer" },

  // ─── SWEETENERS ────────────────────────────────────────────────────────────
  { name: "E950",  type: "sweetener", riskLevel: "moderate", description: "Acesulfame K - artificial sweetener" },
  { name: "E951",  type: "sweetener", riskLevel: "high",     description: "Aspartame - artificial sweetener, controversial safety profile" },
  { name: "E952",  type: "sweetener", riskLevel: "high",     description: "Cyclamates - artificial sweetener, banned in some countries" },
  { name: "E953",  type: "sweetener", riskLevel: "low",      description: "Isomalt - sugar alcohol sweetener" },
  { name: "E954",  type: "sweetener", riskLevel: "moderate", description: "Saccharin - artificial sweetener" },
  { name: "E955",  type: "sweetener", riskLevel: "moderate", description: "Sucralose - artificial sweetener" },
  { name: "E957",  type: "sweetener", riskLevel: "low",      description: "Thaumatin - natural protein sweetener" },
  { name: "E959",  type: "sweetener", riskLevel: "low",      description: "Neohesperidine DC - sweetener" },
  { name: "E960",  type: "sweetener", riskLevel: "low",      description: "Steviol Glycosides - natural sweetener from stevia" },
  { name: "E961",  type: "sweetener", riskLevel: "moderate", description: "Neotame - artificial sweetener" },
  { name: "E962",  type: "sweetener", riskLevel: "moderate", description: "Salt of Aspartame-Acesulfame - artificial sweetener" },
  { name: "E964",  type: "sweetener", riskLevel: "low",      description: "Polyglycitol Syrup - sugar alcohol sweetener" },
  { name: "E965",  type: "sweetener", riskLevel: "low",      description: "Maltitol - sugar alcohol sweetener" },
  { name: "E966",  type: "sweetener", riskLevel: "low",      description: "Lactitol - sugar alcohol sweetener" },
  { name: "E967",  type: "sweetener", riskLevel: "low",      description: "Xylitol - sugar alcohol sweetener" },
  { name: "E968",  type: "sweetener", riskLevel: "low",      description: "Erythritol - sugar alcohol sweetener" },

  // ─── GLAZING / HUMECTANTS / MISC ───────────────────────────────────────────
  { name: "E900",  type: "anti-foaming",  riskLevel: "moderate", description: "Dimethylpolysiloxane - anti-foaming/glazing agent" },
  { name: "E901",  type: "humectant",     riskLevel: "low",      description: "Beeswax - glazing agent" },
  { name: "E902",  type: "humectant",     riskLevel: "low",      description: "Candelilla Wax - glazing agent" },
  { name: "E903",  type: "humectant",     riskLevel: "low",      description: "Carnauba Wax - glazing agent" },
  { name: "E904",  type: "humectant",     riskLevel: "low",      description: "Shellac - glazing agent" },
  { name: "E905",  type: "humectant",     riskLevel: "low",      description: "Microcrystalline Wax - glazing agent" },
  { name: "E907",  type: "humectant",     riskLevel: "low",      description: "Refined Microcrystalline Wax - glazing agent" },
  { name: "E912",  type: "humectant",     riskLevel: "low",      description: "Montanic Acid Esters - glazing agent" },
  { name: "E914",  type: "humectant",     riskLevel: "low",      description: "Oxidised Polyethylene Wax - glazing agent" },
  { name: "E920",  type: "flour treatment agent", riskLevel: "low",      description: "L-Cysteine - flour treatment agent, speeds dough processing" },
  { name: "E921",  type: "flour treatment agent", riskLevel: "low",      description: "L-Cystine - flour treatment agent" },
  { name: "E924",  type: "flour treatment agent", riskLevel: "moderate", description: "Potassium Bromate - flour improver, banned in EU but present in some imports" },
  { name: "E925",  type: "flour treatment agent", riskLevel: "moderate", description: "Chlorine - flour treatment agent" },
  { name: "E926",  type: "flour treatment agent", riskLevel: "moderate", description: "Chlorine Dioxide - flour treatment agent" },
  { name: "E927b", type: "flour treatment agent", riskLevel: "low",      description: "Carbamide - flour treatment agent" },
  { name: "E928",  type: "flour treatment agent", riskLevel: "low",      description: "Benzoyl Peroxide - flour treatment agent" },
  { name: "E938",  type: "humectant",     riskLevel: "low",      description: "Argon - packaging gas" },
  { name: "E939",  type: "humectant",     riskLevel: "low",      description: "Helium - packaging gas" },
  { name: "E941",  type: "humectant",     riskLevel: "low",      description: "Nitrogen - packaging gas" },
  { name: "E942",  type: "humectant",     riskLevel: "low",      description: "Nitrous Oxide - propellant in cream dispensers" },
  { name: "E943a", type: "humectant",     riskLevel: "low",      description: "Butane - propellant" },
  { name: "E943b", type: "humectant",     riskLevel: "low",      description: "Isobutane - propellant" },
  { name: "E944",  type: "humectant",     riskLevel: "low",      description: "Propane - propellant" },
  { name: "E948",  type: "humectant",     riskLevel: "low",      description: "Oxygen - packaging gas" },
  { name: "E949",  type: "humectant",     riskLevel: "low",      description: "Hydrogen - packaging gas" },
  { name: "E999",  type: "anti-foaming",  riskLevel: "low",      description: "Quillaia Extract - foaming agent in drinks" },
  { name: "E1200", type: "thickener",     riskLevel: "low",      description: "Polydextrose - bulking agent/prebiotic fibre" },
  { name: "E1201", type: "thickener",     riskLevel: "low",      description: "Polyvinylpyrrolidone - stabiliser" },
  { name: "E1202", type: "thickener",     riskLevel: "low",      description: "Polyvinyl Polypyrrolidone - stabiliser" },
  { name: "E1404", type: "modified starch", riskLevel: "moderate", description: "Oxidised Starch - modified starch" },
  { name: "E1410", type: "modified starch", riskLevel: "moderate", description: "Monostarch Phosphate - modified starch" },
  { name: "E1412", type: "modified starch", riskLevel: "moderate", description: "Distarch Phosphate - modified starch" },
  { name: "E1413", type: "modified starch", riskLevel: "moderate", description: "Phosphated Distarch Phosphate - modified starch" },
  { name: "E1414", type: "modified starch", riskLevel: "moderate", description: "Acetylated Distarch Phosphate - modified starch" },
  { name: "E1420", type: "modified starch", riskLevel: "moderate", description: "Acetylated Starch - modified starch" },
  { name: "E1422", type: "modified starch", riskLevel: "moderate", description: "Acetylated Distarch Adipate - modified starch" },
  { name: "E1440", type: "modified starch", riskLevel: "moderate", description: "Hydroxypropyl Starch - modified starch" },
  { name: "E1442", type: "modified starch", riskLevel: "moderate", description: "Hydroxypropyl Distarch Phosphate - modified starch" },
  { name: "E1450", type: "modified starch", riskLevel: "moderate", description: "Starch Sodium Octenyl Succinate - modified starch" },
  { name: "E1451", type: "modified starch", riskLevel: "moderate", description: "Acetylated Oxidised Starch - modified starch" },
  { name: "E1452", type: "modified starch", riskLevel: "moderate", description: "Starch Aluminium Octenyl Succinate - modified starch" },
  { name: "E1505", type: "acidity regulator", riskLevel: "low",    description: "Triethyl Citrate - acidity regulator/stabiliser" },
  { name: "E1516", type: "humectant",     riskLevel: "low",      description: "Glyceryl Monoacetate - humectant" },
  { name: "E1518", type: "humectant",     riskLevel: "low",      description: "Glyceryl Triacetate - humectant" },
  { name: "E1519", type: "humectant",     riskLevel: "low",      description: "Benzyl Alcohol - humectant/solvent" },
  { name: "E1520", type: "humectant",     riskLevel: "low",      description: "Propylene Glycol - humectant/solvent" },

  // ─── DEXTRIN / EARLY MODIFIED STARCH ─────────────────────────────────────
  { name: "E1400", type: "modified starch", riskLevel: "moderate", description: "Dextrin - modified starch (roasted)" },
  { name: "E1401", type: "modified starch", riskLevel: "moderate", description: "Acid-Treated Starch - modified starch" },
  { name: "E1402", type: "modified starch", riskLevel: "moderate", description: "Alkaline-Treated Starch - modified starch" },
  { name: "E1403", type: "modified starch", riskLevel: "moderate", description: "Bleached Starch - modified starch" },
];
