export interface ReadyMealSeed {
  name: string;
  category: string;
  dietTypes: string[];
  audience?: string;
  isDrink?: boolean;
  drinkType?: string;
  isFreezerEligible?: boolean;
}

export const READY_MEALS: ReadyMealSeed[] = [
  { name: "Beef Lasagne", category: "Dinner", dietTypes: [] },
  { name: "Chicken Korma", category: "Dinner", dietTypes: [] },
  { name: "Chicken Tikka Masala", category: "Dinner", dietTypes: [] },
  { name: "Spaghetti Bolognese", category: "Dinner", dietTypes: [] },
  { name: "Macaroni Cheese", category: "Dinner", dietTypes: ["vegetarian"] },
  { name: "Shepherd's Pie", category: "Dinner", dietTypes: [] },
  { name: "Cottage Pie", category: "Dinner", dietTypes: [] },
  { name: "Fish Pie", category: "Dinner", dietTypes: [] },
  { name: "Chicken & Mushroom Pie", category: "Dinner", dietTypes: [] },
  { name: "Steak & Kidney Pie", category: "Dinner", dietTypes: [] },
  { name: "Sweet & Sour Chicken", category: "Dinner", dietTypes: [] },
  { name: "Chicken Chow Mein", category: "Dinner", dietTypes: [] },
  { name: "Beef Chow Mein", category: "Dinner", dietTypes: [] },
  { name: "Chicken Fried Rice", category: "Dinner", dietTypes: [] },
  { name: "Egg Fried Rice", category: "Dinner", dietTypes: ["vegetarian"] },
  { name: "Vegetable Stir Fry", category: "Dinner", dietTypes: ["vegetarian", "vegan"] },
  { name: "Chicken Jalfrezi", category: "Dinner", dietTypes: [] },
  { name: "Lamb Rogan Josh", category: "Dinner", dietTypes: [] },
  { name: "Prawn Madras", category: "Dinner", dietTypes: [] },
  { name: "Vegetable Curry", category: "Dinner", dietTypes: ["vegetarian", "vegan"] },
  { name: "Chicken Biryani", category: "Dinner", dietTypes: [] },
  { name: "Lamb Biryani", category: "Dinner", dietTypes: [] },
  { name: "Chicken Pad Thai", category: "Dinner", dietTypes: [] },
  { name: "Thai Green Curry", category: "Dinner", dietTypes: [] },
  { name: "Thai Red Curry", category: "Dinner", dietTypes: [] },
  { name: "Chicken Katsu Curry", category: "Dinner", dietTypes: [] },
  { name: "Beef Stroganoff", category: "Dinner", dietTypes: [] },
  { name: "Chicken Kiev", category: "Dinner", dietTypes: [] },
  { name: "Fish & Chips", category: "Dinner", dietTypes: [] },
  { name: "Battered Cod", category: "Dinner", dietTypes: [] },
  { name: "Fish Fingers", category: "Dinner", dietTypes: [] },
  { name: "Chicken Nuggets", category: "Dinner", dietTypes: [] },
  { name: "Southern Fried Chicken", category: "Dinner", dietTypes: [] },
  { name: "Chicken Goujons", category: "Dinner", dietTypes: [] },
  { name: "Beef Burgers", category: "Dinner", dietTypes: [] },
  { name: "Chicken Burgers", category: "Dinner", dietTypes: [] },
  { name: "Veggie Burgers", category: "Dinner", dietTypes: ["vegetarian"] },
  { name: "Sausage & Mash", category: "Dinner", dietTypes: [] },
  { name: "Bangers & Mash", category: "Dinner", dietTypes: [] },
  { name: "Toad in the Hole", category: "Dinner", dietTypes: [] },
  { name: "Roast Chicken Dinner", category: "Dinner", dietTypes: [] },
  { name: "Roast Beef Dinner", category: "Dinner", dietTypes: [] },
  { name: "Sunday Roast Pork", category: "Dinner", dietTypes: [] },
  { name: "Chicken Casserole", category: "Dinner", dietTypes: [] },
  { name: "Beef Casserole", category: "Dinner", dietTypes: [] },
  { name: "Lamb Hotpot", category: "Dinner", dietTypes: [] },
  { name: "Chilli Con Carne", category: "Dinner", dietTypes: [] },
  { name: "Vegetable Chilli", category: "Dinner", dietTypes: ["vegetarian", "vegan"] },
  { name: "Chicken Fajitas", category: "Dinner", dietTypes: [] },
  { name: "Beef Fajitas", category: "Dinner", dietTypes: [] },
  { name: "Cheese & Tomato Pizza", category: "Dinner", dietTypes: ["vegetarian"] },
  { name: "Pepperoni Pizza", category: "Dinner", dietTypes: [] },
  { name: "Margherita Pizza", category: "Dinner", dietTypes: ["vegetarian"] },
  { name: "BBQ Chicken Pizza", category: "Dinner", dietTypes: [] },
  { name: "Ham & Pineapple Pizza", category: "Dinner", dietTypes: [] },
  { name: "Meat Feast Pizza", category: "Dinner", dietTypes: [] },
  { name: "Vegetable Pizza", category: "Dinner", dietTypes: ["vegetarian"] },
  { name: "Chicken & Bacon Pasta", category: "Dinner", dietTypes: [] },
  { name: "Penne Arrabbiata", category: "Dinner", dietTypes: ["vegetarian", "vegan"] },
  { name: "Carbonara", category: "Dinner", dietTypes: [] },
  { name: "Mushroom Risotto", category: "Dinner", dietTypes: ["vegetarian"] },
  { name: "Chicken Risotto", category: "Dinner", dietTypes: [] },
  { name: "Salmon & Broccoli Bake", category: "Dinner", dietTypes: [] },
  { name: "Tuna Pasta Bake", category: "Dinner", dietTypes: [] },
  { name: "Chicken Pasta Bake", category: "Dinner", dietTypes: [] },
  { name: "Moussaka", category: "Dinner", dietTypes: [] },
  { name: "Vegetable Moussaka", category: "Dinner", dietTypes: ["vegetarian"] },
  { name: "Beef Enchiladas", category: "Dinner", dietTypes: [] },
  { name: "Chicken Enchiladas", category: "Dinner", dietTypes: [] },
  { name: "Bean Enchiladas", category: "Dinner", dietTypes: ["vegetarian", "vegan"] },
  { name: "Chicken Noodles", category: "Dinner", dietTypes: [] },
  { name: "Singapore Noodles", category: "Dinner", dietTypes: [] },
  { name: "Prawn Stir Fry", category: "Dinner", dietTypes: [] },
  { name: "Teriyaki Chicken", category: "Dinner", dietTypes: [] },
  { name: "Sweet Chilli Chicken", category: "Dinner", dietTypes: [] },
  { name: "Honey & Mustard Chicken", category: "Dinner", dietTypes: [] },
  { name: "Chicken Tikka", category: "Dinner", dietTypes: [] },
  { name: "Tandoori Chicken", category: "Dinner", dietTypes: [] },
  { name: "Lamb Kofta", category: "Dinner", dietTypes: [] },
  { name: "Chicken Shawarma", category: "Dinner", dietTypes: [] },
  { name: "Falafel Wrap", category: "Lunch", dietTypes: ["vegetarian", "vegan"] },
  { name: "Chicken Caesar Wrap", category: "Lunch", dietTypes: [] },
  { name: "BLT Sandwich", category: "Lunch", dietTypes: [] },
  { name: "Chicken & Stuffing Sandwich", category: "Lunch", dietTypes: [] },
  { name: "Egg Mayo Sandwich", category: "Lunch", dietTypes: ["vegetarian"] },
  { name: "Tuna Mayo Sandwich", category: "Lunch", dietTypes: [] },
  { name: "Ham & Cheese Sandwich", category: "Lunch", dietTypes: [] },
  { name: "Prawn Mayo Sandwich", category: "Lunch", dietTypes: [] },
  { name: "Ploughman's Sandwich", category: "Lunch", dietTypes: ["vegetarian"] },
  { name: "Cheese & Pickle Sandwich", category: "Lunch", dietTypes: ["vegetarian"] },
  { name: "Chicken Salad", category: "Lunch", dietTypes: [] },
  { name: "Prawn Cocktail", category: "Lunch", dietTypes: [] },
  { name: "Caesar Salad", category: "Lunch", dietTypes: [] },
  { name: "Greek Salad", category: "Lunch", dietTypes: ["vegetarian"] },
  { name: "Pasta Salad", category: "Lunch", dietTypes: ["vegetarian"] },
  { name: "Couscous Salad", category: "Lunch", dietTypes: ["vegetarian"] },
  { name: "Tomato Soup", category: "Lunch", dietTypes: ["vegetarian", "vegan"] },
  { name: "Chicken Soup", category: "Lunch", dietTypes: [] },
  { name: "Minestrone Soup", category: "Lunch", dietTypes: ["vegetarian", "vegan"] },
  { name: "Leek & Potato Soup", category: "Lunch", dietTypes: ["vegetarian"] },
  { name: "Pea & Ham Soup", category: "Lunch", dietTypes: [] },
  { name: "Mushroom Soup", category: "Lunch", dietTypes: ["vegetarian"] },
  { name: "Broccoli & Stilton Soup", category: "Lunch", dietTypes: ["vegetarian"] },
  { name: "Lentil Soup", category: "Lunch", dietTypes: ["vegetarian", "vegan"] },
  { name: "Scotch Egg", category: "Snack", dietTypes: [] },
  { name: "Sausage Roll", category: "Snack", dietTypes: [] },
  { name: "Pork Pie", category: "Snack", dietTypes: [] },
  { name: "Cornish Pasty", category: "Snack", dietTypes: [] },
  { name: "Cheese & Onion Pasty", category: "Snack", dietTypes: ["vegetarian"] },
  { name: "Chicken & Mushroom Slice", category: "Snack", dietTypes: [] },
  { name: "Vegetable Samosa", category: "Snack", dietTypes: ["vegetarian", "vegan"] },
  { name: "Onion Bhaji", category: "Snack", dietTypes: ["vegetarian", "vegan"] },
  { name: "Spring Rolls", category: "Snack", dietTypes: ["vegetarian", "vegan"] },
  { name: "Chicken Spring Rolls", category: "Snack", dietTypes: [] },
  { name: "Prawn Toast", category: "Snack", dietTypes: [] },
  { name: "Chicken Satay Skewers", category: "Snack", dietTypes: [] },
  { name: "Garlic Bread", category: "Snack", dietTypes: ["vegetarian"] },
  { name: "Cheesy Garlic Bread", category: "Snack", dietTypes: ["vegetarian"] },
  { name: "Potato Wedges", category: "Snack", dietTypes: ["vegetarian", "vegan"] },
  { name: "Chips", category: "Snack", dietTypes: ["vegetarian", "vegan"] },
  { name: "Curly Fries", category: "Snack", dietTypes: ["vegetarian", "vegan"] },
  { name: "Hash Browns", category: "Snack", dietTypes: ["vegetarian", "vegan"] },
  { name: "Mozzarella Sticks", category: "Snack", dietTypes: ["vegetarian"] },
  { name: "Chicken Wings", category: "Snack", dietTypes: [] },
  { name: "BBQ Ribs", category: "Snack", dietTypes: [] },
  { name: "Hummus & Pitta", category: "Snack", dietTypes: ["vegetarian", "vegan"] },
  { name: "Guacamole & Tortilla Chips", category: "Snack", dietTypes: ["vegetarian", "vegan"] },
  { name: "Porridge Pot", category: "Breakfast", dietTypes: ["vegetarian"] },
  { name: "Granola Pot", category: "Breakfast", dietTypes: ["vegetarian"] },
  { name: "Fruit & Yogurt Pot", category: "Breakfast", dietTypes: ["vegetarian"] },
  { name: "Bircher Muesli", category: "Breakfast", dietTypes: ["vegetarian"] },
  { name: "Bacon & Egg Muffin", category: "Breakfast", dietTypes: [] },
  { name: "Sausage & Egg Muffin", category: "Breakfast", dietTypes: [] },
  { name: "Full English Breakfast", category: "Breakfast", dietTypes: [] },
  { name: "Vegetarian Breakfast", category: "Breakfast", dietTypes: ["vegetarian"] },
  { name: "Pancakes", category: "Breakfast", dietTypes: ["vegetarian"] },
  { name: "Croissant", category: "Breakfast", dietTypes: ["vegetarian"] },
  { name: "Pain au Chocolat", category: "Breakfast", dietTypes: ["vegetarian"] },
  { name: "Egg & Cress Sandwich", category: "Breakfast", dietTypes: ["vegetarian"] },
  { name: "Smoked Salmon & Cream Cheese Bagel", category: "Breakfast", dietTypes: [] },
  { name: "Avocado on Toast", category: "Breakfast", dietTypes: ["vegetarian", "vegan"] },
  { name: "Overnight Oats", category: "Breakfast", dietTypes: ["vegetarian"] },
  { name: "Scrambled Eggs on Toast", category: "Breakfast", dietTypes: ["vegetarian"] },
  { name: "Breakfast Burrito", category: "Breakfast", dietTypes: [] },
  { name: "Eggs Benedict", category: "Breakfast", dietTypes: ["vegetarian"] },
  { name: "French Toast", category: "Breakfast", dietTypes: ["vegetarian"] },
  { name: "Breakfast Wrap", category: "Breakfast", dietTypes: [] },
  { name: "Hash Browns", category: "Breakfast", dietTypes: ["vegetarian", "vegan"] },
  { name: "Waffles", category: "Breakfast", dietTypes: ["vegetarian"] },
  { name: "Cinnamon Roll", category: "Breakfast", dietTypes: ["vegetarian"] },
  { name: "Acai Bowl", category: "Breakfast", dietTypes: ["vegetarian", "vegan"] },
  { name: "Omelette", category: "Breakfast", dietTypes: ["vegetarian"] },
  { name: "Chocolate Brownie", category: "Dessert", dietTypes: ["vegetarian"] },
  { name: "Sticky Toffee Pudding", category: "Dessert", dietTypes: ["vegetarian"] },
  { name: "Chocolate Fudge Cake", category: "Dessert", dietTypes: ["vegetarian"] },
  { name: "Victoria Sponge Cake", category: "Dessert", dietTypes: ["vegetarian"] },
  { name: "Carrot Cake", category: "Dessert", dietTypes: ["vegetarian"] },
  { name: "Cheesecake", category: "Dessert", dietTypes: ["vegetarian"] },
  { name: "Chocolate Cheesecake", category: "Dessert", dietTypes: ["vegetarian"] },
  { name: "Tiramisu", category: "Dessert", dietTypes: ["vegetarian"] },
  { name: "Apple Pie", category: "Dessert", dietTypes: ["vegetarian"] },
  { name: "Treacle Tart", category: "Dessert", dietTypes: ["vegetarian"] },
  { name: "Bread & Butter Pudding", category: "Dessert", dietTypes: ["vegetarian"] },
  { name: "Rice Pudding", category: "Dessert", dietTypes: ["vegetarian"] },
  { name: "Crème Brûlée", category: "Dessert", dietTypes: ["vegetarian"] },
  { name: "Panna Cotta", category: "Dessert", dietTypes: ["vegetarian"] },
  { name: "Chocolate Mousse", category: "Dessert", dietTypes: ["vegetarian"] },
  { name: "Profiteroles", category: "Dessert", dietTypes: ["vegetarian"] },
  { name: "Trifle", category: "Dessert", dietTypes: ["vegetarian"] },
  { name: "Eton Mess", category: "Dessert", dietTypes: ["vegetarian"] },
  { name: "Fruit Salad", category: "Dessert", dietTypes: ["vegetarian", "vegan"] },
  { name: "Jelly", category: "Dessert", dietTypes: ["vegetarian"] },
  { name: "Chicken Dippers", category: "Dinner", dietTypes: [] },
  { name: "Turkey Dinosaurs", category: "Dinner", dietTypes: [] },
  { name: "Birdseye Waffles", category: "Dinner", dietTypes: ["vegetarian"] },
  { name: "Quorn Nuggets", category: "Dinner", dietTypes: ["vegetarian"] },
  { name: "Vegetable Fingers", category: "Dinner", dietTypes: ["vegetarian", "vegan"] },
  { name: "Veggie Sausages", category: "Dinner", dietTypes: ["vegetarian"] },
  { name: "Plant-Based Mince", category: "Dinner", dietTypes: ["vegetarian", "vegan"] },
  { name: "Vegan Lasagne", category: "Dinner", dietTypes: ["vegetarian", "vegan"] },
  { name: "Vegan Shepherd's Pie", category: "Dinner", dietTypes: ["vegetarian", "vegan"] },
  { name: "Vegan Thai Curry", category: "Dinner", dietTypes: ["vegetarian", "vegan"] },
  { name: "Tofu Stir Fry", category: "Dinner", dietTypes: ["vegetarian", "vegan"] },
  { name: "Jackfruit Curry", category: "Dinner", dietTypes: ["vegetarian", "vegan"] },
  { name: "Cauliflower Cheese", category: "Dinner", dietTypes: ["vegetarian"] },
  { name: "Vegetable Gratin", category: "Dinner", dietTypes: ["vegetarian"] },
  { name: "Spinach & Ricotta Cannelloni", category: "Dinner", dietTypes: ["vegetarian"] },
  { name: "Cheese & Spinach Quiche", category: "Lunch", dietTypes: ["vegetarian"] },
  { name: "Quiche Lorraine", category: "Lunch", dietTypes: [] },
  { name: "Ham & Cheese Panini", category: "Lunch", dietTypes: [] },
  { name: "Chicken & Bacon Panini", category: "Lunch", dietTypes: [] },
  { name: "Cheese & Onion Quiche", category: "Lunch", dietTypes: ["vegetarian"] },
  { name: "Prawn Fried Rice", category: "Dinner", dietTypes: [] },
  { name: "Duck Spring Rolls", category: "Snack", dietTypes: [] },
  { name: "Crispy Duck Pancakes", category: "Dinner", dietTypes: [] },
  { name: "Chicken Chilli", category: "Dinner", dietTypes: [] },
  { name: "Lamb Tagine", category: "Dinner", dietTypes: [] },
  { name: "Moroccan Chicken", category: "Dinner", dietTypes: [] },
  { name: "Butter Chicken", category: "Dinner", dietTypes: [] },
  { name: "Paneer Tikka Masala", category: "Dinner", dietTypes: ["vegetarian"] },
  { name: "Saag Paneer", category: "Dinner", dietTypes: ["vegetarian"] },
  { name: "Dhal", category: "Dinner", dietTypes: ["vegetarian", "vegan"] },
  { name: "Chicken Bhuna", category: "Dinner", dietTypes: [] },
  { name: "King Prawn Stir Fry", category: "Dinner", dietTypes: [] },
  { name: "Beef & Broccoli", category: "Dinner", dietTypes: [] },
  { name: "Sweet & Sour Pork", category: "Dinner", dietTypes: [] },
  { name: "Char Siu Pork", category: "Dinner", dietTypes: [] },
  { name: "Kung Pao Chicken", category: "Dinner", dietTypes: [] },
  { name: "General Tso's Chicken", category: "Dinner", dietTypes: [] },
  { name: "Yakisoba Noodles", category: "Dinner", dietTypes: [] },
  { name: "Katsu Curry", category: "Dinner", dietTypes: [] },
  { name: "Miso Soup", category: "Lunch", dietTypes: ["vegetarian", "vegan"] },
  { name: "Wonton Soup", category: "Lunch", dietTypes: [] },
  { name: "Tom Yum Soup", category: "Lunch", dietTypes: [] },
  { name: "Chicken Quesadilla", category: "Lunch", dietTypes: [] },
  { name: "Cheese Quesadilla", category: "Lunch", dietTypes: ["vegetarian"] },
  { name: "Vegetable Wrap", category: "Lunch", dietTypes: ["vegetarian", "vegan"] },
  { name: "Chicken Tikka Wrap", category: "Lunch", dietTypes: [] },
  { name: "Fish Cakes", category: "Dinner", dietTypes: [] },
  { name: "Salmon Fish Cakes", category: "Dinner", dietTypes: [] },
  { name: "Scampi", category: "Dinner", dietTypes: [] },
  { name: "Breaded Plaice", category: "Dinner", dietTypes: [] },
  { name: "Chicken Escalope", category: "Dinner", dietTypes: [] },
  { name: "Pork Schnitzel", category: "Dinner", dietTypes: [] },
  { name: "Beef Meatballs", category: "Dinner", dietTypes: [] },
  { name: "Spaghetti & Meatballs", category: "Dinner", dietTypes: [] },

  { name: "Coca-Cola", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "soft-drink" },
  { name: "Diet Coke", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "soft-drink" },
  { name: "Coke Zero", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "soft-drink" },
  { name: "Pepsi", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "soft-drink" },
  { name: "Pepsi Max", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "soft-drink" },
  { name: "Fanta Orange", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "soft-drink" },
  { name: "Sprite", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "soft-drink" },
  { name: "7UP", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "soft-drink" },
  { name: "Lemonade", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "soft-drink" },
  { name: "Irn-Bru", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "soft-drink" },
  { name: "Dr Pepper", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "soft-drink" },
  { name: "Lucozade Original", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "soft-drink" },
  { name: "Lucozade Sport", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "soft-drink" },
  { name: "Ribena", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "soft-drink" },
  { name: "Vimto", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "soft-drink" },
  { name: "Robinsons Squash", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "squash" },
  { name: "Orange Juice", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "juice" },
  { name: "Apple Juice", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "juice" },
  { name: "Cranberry Juice", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "juice" },
  { name: "Tropicana", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "juice" },
  { name: "Innocent Smoothie", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "smoothie" },
  { name: "Whole Milk", category: "Drink", dietTypes: ["vegetarian"], isDrink: true, drinkType: "milk" },
  { name: "Semi-Skimmed Milk", category: "Drink", dietTypes: ["vegetarian"], isDrink: true, drinkType: "milk" },
  { name: "Skimmed Milk", category: "Drink", dietTypes: ["vegetarian"], isDrink: true, drinkType: "milk" },
  { name: "Oat Milk", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "milk" },
  { name: "Almond Milk", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "milk" },
  { name: "Soya Milk", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "milk" },
  { name: "Coconut Milk", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "milk" },
  { name: "Water", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "water" },
  { name: "Sparkling Water", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "water" },
  { name: "Tonic Water", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "water" },
  { name: "Tea", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "hot-drink" },
  { name: "Coffee", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "hot-drink" },
  { name: "Hot Chocolate", category: "Drink", dietTypes: ["vegetarian"], isDrink: true, drinkType: "hot-drink" },
  { name: "Cappuccino", category: "Drink", dietTypes: ["vegetarian"], isDrink: true, drinkType: "hot-drink" },
  { name: "Latte", category: "Drink", dietTypes: ["vegetarian"], isDrink: true, drinkType: "hot-drink" },
  { name: "Green Tea", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "hot-drink" },
  { name: "Herbal Tea", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "hot-drink" },
  { name: "Monster Energy", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "energy-drink" },
  { name: "Red Bull", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "energy-drink" },
  { name: "Boost Energy", category: "Drink", dietTypes: ["vegan"], isDrink: true, drinkType: "energy-drink" },
  { name: "Protein Shake", category: "Drink", dietTypes: [], isDrink: true, drinkType: "protein" },
  { name: "Yakult", category: "Drink", dietTypes: ["vegetarian"], isDrink: true, drinkType: "probiotic" },
  { name: "Actimel", category: "Drink", dietTypes: ["vegetarian"], isDrink: true, drinkType: "probiotic" },

  { name: "Ella's Kitchen Pouches", category: "Baby Meal", dietTypes: ["vegetarian"], audience: "baby" },
  { name: "Cow & Gate Baby Food", category: "Baby Meal", dietTypes: [], audience: "baby" },
  { name: "Heinz Baby Food", category: "Baby Meal", dietTypes: [], audience: "baby" },
  { name: "Hipp Organic Baby Food", category: "Baby Meal", dietTypes: ["vegetarian"], audience: "baby" },
  { name: "Aptamil Baby Rice", category: "Baby Meal", dietTypes: [], audience: "baby" },
  { name: "Baby Porridge", category: "Baby Meal", dietTypes: ["vegetarian"], audience: "baby" },
  { name: "Baby Fruit Puree", category: "Baby Meal", dietTypes: ["vegan"], audience: "baby" },
  { name: "Baby Vegetable Puree", category: "Baby Meal", dietTypes: ["vegan"], audience: "baby" },
  { name: "Baby Chicken Dinner", category: "Baby Meal", dietTypes: [], audience: "baby" },
  { name: "Baby Pasta Stars", category: "Baby Meal", dietTypes: ["vegetarian"], audience: "baby" },
  { name: "Baby Rice Cakes", category: "Baby Meal", dietTypes: ["vegan"], audience: "baby" },
  { name: "Baby Yogurt Drops", category: "Baby Meal", dietTypes: ["vegetarian"], audience: "baby" },
  { name: "Baby Banana Snacks", category: "Baby Meal", dietTypes: ["vegan"], audience: "baby" },
  { name: "Baby Rusk", category: "Baby Meal", dietTypes: ["vegetarian"], audience: "baby" },
  { name: "Baby Cereal", category: "Baby Meal", dietTypes: ["vegetarian"], audience: "baby" },
  { name: "Baby Beef Casserole", category: "Baby Meal", dietTypes: [], audience: "baby" },
  { name: "Baby Fish Pie", category: "Baby Meal", dietTypes: [], audience: "baby" },
  { name: "Baby Mac & Cheese", category: "Baby Meal", dietTypes: ["vegetarian"], audience: "baby" },
  { name: "Baby Sweet Potato Mash", category: "Baby Meal", dietTypes: ["vegan"], audience: "baby" },
  { name: "Baby Apple & Pear Puree", category: "Baby Meal", dietTypes: ["vegan"], audience: "baby" },

  { name: "Fish Fingers & Chips", category: "Kids Meal", dietTypes: [], audience: "child" },
  { name: "Chicken Nuggets & Chips", category: "Kids Meal", dietTypes: [], audience: "child" },
  { name: "Spaghetti Hoops", category: "Kids Meal", dietTypes: ["vegetarian"], audience: "child" },
  { name: "Beans on Toast", category: "Kids Meal", dietTypes: ["vegetarian", "vegan"], audience: "child" },
  { name: "Cheese on Toast", category: "Kids Meal", dietTypes: ["vegetarian"], audience: "child" },
  { name: "Alphabet Spaghetti", category: "Kids Meal", dietTypes: ["vegetarian"], audience: "child" },
  { name: "Mini Pizza", category: "Kids Meal", dietTypes: ["vegetarian"], audience: "child" },
  { name: "Potato Smiley Faces", category: "Kids Meal", dietTypes: ["vegetarian", "vegan"], audience: "child" },
  { name: "Pom-Bear Crisps", category: "Kids Meal", dietTypes: ["vegetarian"], audience: "child" },
  { name: "Kids Pasta Bake", category: "Kids Meal", dietTypes: ["vegetarian"], audience: "child" },
  { name: "Mini Sausage Rolls", category: "Kids Meal", dietTypes: [], audience: "child" },
  { name: "Cheese Strings", category: "Kids Meal", dietTypes: ["vegetarian"], audience: "child" },
  { name: "Frubes", category: "Kids Meal", dietTypes: ["vegetarian"], audience: "child" },
  { name: "Petit Filous", category: "Kids Meal", dietTypes: ["vegetarian"], audience: "child" },
  { name: "Bear Paws", category: "Kids Meal", dietTypes: ["vegetarian"], audience: "child" },
  { name: "Organix Snacks", category: "Kids Meal", dietTypes: ["vegetarian"], audience: "child" },
  { name: "Goodies Oaty Bars", category: "Kids Meal", dietTypes: ["vegetarian"], audience: "child" },
  { name: "Mini Cheddars", category: "Kids Meal", dietTypes: ["vegetarian"], audience: "child" },
  { name: "Kids Fruit Pouch", category: "Kids Meal", dietTypes: ["vegan"], audience: "child" },
  { name: "Ham Sandwich", category: "Kids Meal", dietTypes: [], audience: "child" },
];
