// WS11 — Seasonal Stories Engine: worked examples + trust validation.
// Run: tsx server/tests/test-seasonal-stories-engine.ts
//
// Produces the four worked households the brief requires (Mediterranean across
// all four seasons; family with children; vegetarian; household discovering
// legumes), demonstrates all five blocks, exercises the silence contract, and
// enforces the trust gate (no ranking/scorecard/season-comparison language) as
// a hard gate. Writes a JSON report to data/seasonal/ for preservation.
//
// Every block is generated by composing WS10 Stories and WS8 Discovery — this
// test also proves the reuse: the same history fed to stories() and to
// seasonalStories() yields consistent memories.

import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import {
  seasonalStories,
  formatSeasonalStory,
  assertTrustworthy,
} from "../../shared/seasonal";
import type { SeasonalStory } from "../../shared/seasonal";
import type { MealEntry } from "../../shared/stories";

const line = "=".repeat(64);
let failures = 0;
const NOW = new Date("2026-06-22");

function allCards(s: SeasonalStory) {
  return s.blocks.flatMap((b) => b.cards);
}

function checkTrust(label: string, s: SeasonalStory) {
  try {
    assertTrustworthy(allCards(s));
    console.log(`  ✓ trust check passed (${allCards(s).length} cards)`);
  } catch (e) {
    failures++;
    console.log(`  ✗ ${label}: ${(e as Error).message}`);
  }
}

function expect(label: string, cond: boolean) {
  if (cond) {
    console.log(`  ✓ ${label}`);
  } else {
    failures++;
    console.log(`  ✗ FAILED: ${label}`);
  }
}

function d(iso: string): Date {
  return new Date(iso);
}

function repeat(entry: Omit<MealEntry, "date">, dates: string[]): MealEntry[] {
  return dates.map((iso) => ({ ...entry, date: d(iso) }));
}

function blockTypes(s: SeasonalStory) {
  return s.blocks.map((b) => b.type);
}

const report: Record<string, unknown> = {};

// ════════════════════════════════════════════════════════════════════════════
// 1. MEDITERRANEAN HOUSEHOLD — across all four seasons
// ════════════════════════════════════════════════════════════════════════════
//
// A two-year Mediterranean kitchen: tomatoes, olive oil and feta the backbone;
// basil and courgette in summer; squash and kale in autumn; legumes building
// through the cold months. We tell four seasonal stories from the SAME history,
// proving the engine frames one history into distinct seasons.

console.log("WS11 — Seasonal Stories Engine\n");
console.log(line);
console.log("1. MEDITERRANEAN HOUSEHOLD — four seasons from one history\n");

const mediterHistory: MealEntry[] = [
  // ── Tomato — the cornerstone, year-round, peaking in summer ──
  ...repeat(
    { food: "tomato", foodName: "Tomato", mealName: "Greek Salad", mealSlot: "dinner", source: "planned" },
    ["2025-06-06", "2025-06-20", "2025-07-04", "2025-07-18", "2025-08-01", "2025-08-15", "2025-08-29",
     "2025-09-12", "2025-10-03", "2025-11-07",
     "2025-12-05", "2026-01-09", "2026-02-13",
     "2026-03-06", "2026-03-20", "2026-04-10", "2026-04-24", "2026-05-08", "2026-05-22"],
  ),
  // ── Extra virgin olive oil — almost everything ──
  ...repeat(
    { food: "extra-virgin-olive-oil", foodName: "Extra Virgin Olive Oil", mealName: "Greek Salad", mealSlot: "dinner", source: "planned" },
    ["2025-06-06", "2025-07-04", "2025-08-01", "2025-08-29",
     "2025-09-12", "2025-10-03", "2025-11-07",
     "2025-12-05", "2026-01-09", "2026-02-13",
     "2026-03-06", "2026-04-10", "2026-05-08", "2026-05-22"],
  ),
  // ── Feta — the Greek-salad partner ──
  ...repeat(
    { food: "feta", foodName: "Feta", mealName: "Greek Salad", mealSlot: "dinner", source: "planned" },
    ["2025-06-20", "2025-07-18", "2025-08-15",
     "2025-09-12", "2025-10-17", "2025-11-21",
     "2026-03-13", "2026-04-17", "2026-05-15"],
  ),
  // ── Basil — a summer herb (summer habit) ──
  ...repeat(
    { food: "basil", foodName: "Basil", mealName: "Pasta Sauce", mealSlot: "dinner", source: "planned" },
    ["2025-06-13", "2025-06-27", "2025-07-11", "2025-07-25", "2025-08-08", "2025-08-22"],
  ),
  // ── Courgette — summer vegetable ──
  ...repeat(
    { food: "courgette", foodName: "Courgette", mealName: "Ratatouille", mealSlot: "dinner", source: "planned" },
    ["2025-06-10", "2025-07-08", "2025-07-22", "2025-08-05", "2025-08-19"],
  ),
  // ── Aubergine — first met in autumn 2025 (autumn discovery), then kept ──
  ...repeat(
    { food: "aubergine", foodName: "Aubergine", mealName: "Moussaka", mealSlot: "dinner", source: "planned" },
    ["2025-09-06", "2025-09-27", "2025-10-18", "2025-11-15", "2026-03-28", "2026-05-02"],
  ),
  // ── Butternut squash — autumn habit, first met autumn 2025 ──
  ...repeat(
    { food: "butternut-squash", foodName: "Butternut Squash", mealName: "Roasted Squash", mealSlot: "dinner", source: "planned" },
    ["2025-09-13", "2025-10-04", "2025-10-25", "2025-11-08", "2025-11-22"],
  ),
  // ── Kale — autumn/winter green ──
  ...repeat(
    { food: "kale", foodName: "Kale", mealName: "Greens", mealSlot: "dinner", source: "planned" },
    ["2025-10-11", "2025-11-01", "2025-11-29", "2025-12-13", "2026-01-17", "2026-02-07"],
  ),
  // ── Butter beans — winter stews, first met winter 2026 (Dec 2025) ──
  ...repeat(
    { food: "butter-beans", foodName: "Butter Beans", mealName: "Butter Bean Stew", mealSlot: "dinner", source: "planned" },
    ["2025-12-06", "2025-12-20", "2026-01-10", "2026-01-24", "2026-02-14"],
  ),
  // ── Leek — winter ──
  ...repeat(
    { food: "leek", foodName: "Leek", mealName: "Leek Soup", mealSlot: "dinner", source: "planned" },
    ["2025-12-12", "2026-01-16", "2026-02-06", "2026-02-20"],
  ),
  // ── Fennel — a spring 2026 discovery ──
  ...repeat(
    { food: "fennel", foodName: "Fennel", mealName: "Fennel Salad", mealSlot: "lunch", source: "planned" },
    ["2026-03-14", "2026-04-11", "2026-05-09"],
  ),
  // ── Asparagus — a spring 2026 discovery ──
  ...repeat(
    { food: "asparagus", foodName: "Asparagus", mealName: "Spring Plate", mealSlot: "dinner", source: "planned" },
    ["2026-04-04", "2026-04-25", "2026-05-16"],
  ),
];

const mediterSeasons: Array<{ key: string; season: "spring" | "summer" | "autumn" | "winter"; year: number }> = [
  { key: "spring-2026", season: "spring", year: 2026 },
  { key: "summer-2025", season: "summer", year: 2025 },
  { key: "autumn-2025", season: "autumn", year: 2025 },
  { key: "winter-2026", season: "winter", year: 2026 },
];

for (const s of mediterSeasons) {
  const story = seasonalStories({
    household: { entries: mediterHistory },
    season: { season: s.season, year: s.year },
    now: NOW,
  });
  console.log(formatSeasonalStory(story));
  checkTrust(`mediterranean ${s.key}`, story);
  report[`mediterranean-${s.key}`] = story;
  console.log();
}

// Targeted assertions on specific seasons
const medSummer = seasonalStories({
  household: { entries: mediterHistory },
  season: { season: "summer", year: 2025 },
  now: NOW,
});
expect("med summer: season summary present", blockTypes(medSummer).includes("season_summary"));
expect("med summer: seasonal habits present", blockTypes(medSummer).includes("seasonal_habits"));
expect(
  "med summer: looking ahead points to autumn foods",
  medSummer.blocks
    .find((b) => b.type === "looking_ahead")
    ?.cards.some((c) => c.headline.toLowerCase().includes("autumn")) ?? false,
);

const medSpring = seasonalStories({
  household: { entries: mediterHistory },
  season: { season: "spring", year: 2026 },
  now: NOW,
});
expect(
  "med spring: fennel/asparagus surfaced as discoveries",
  medSpring.blocks
    .find((b) => b.type === "discoveries")
    ?.cards.some((c) =>
      /fennel|asparagus/i.test(c.headline + JSON.stringify(c.facts)),
    ) ?? false,
);

const medAutumn = seasonalStories({
  household: { entries: mediterHistory },
  season: { season: "autumn", year: 2025 },
  now: NOW,
});
expect("med autumn: season summary present", blockTypes(medAutumn).includes("season_summary"));

// ════════════════════════════════════════════════════════════════════════════
// 2. FAMILY WITH CHILDREN — summer 2025
// ════════════════════════════════════════════════════════════════════════════
//
// Friendly, repeatable family meals: Friday pizza (a tradition), pasta, plenty
// of strawberries and a summer of breakfast bowls. Children's entries are
// "planned" only (no diary) — the engine never claims they "ate", only that
// foods "featured". The story should read as a warm family summer.

console.log(line);
console.log("2. FAMILY WITH CHILDREN — summer 2025 (Friday pizza, breakfast bowls)\n");

const FRIDAYS_SUMMER_2025 = [
  "2025-06-06", "2025-06-13", "2025-06-20", "2025-06-27",
  "2025-07-04", "2025-07-11", "2025-07-18", "2025-07-25",
  "2025-08-01", "2025-08-08", "2025-08-15",
];

const familyHistory: MealEntry[] = [
  // Friday pizza night — a family tradition
  ...FRIDAYS_SUMMER_2025.map((iso) => ({
    food: "tomato", foodName: "Tomato", mealName: "Pizza", mealSlot: "dinner" as const, source: "planned" as const, date: d(iso),
  })),
  // Pasta — a weekday regular
  ...repeat(
    { food: "pasta", foodName: "Pasta", mealName: "Pasta Bake", mealSlot: "dinner", source: "planned" },
    ["2025-06-09", "2025-06-16", "2025-06-23", "2025-07-07", "2025-07-21", "2025-08-04", "2025-08-18"],
  ),
  // Strawberries — summer breakfast bowls (children love them)
  ...repeat(
    { food: "strawberry", foodName: "Strawberry", mealName: "Breakfast Bowl", mealSlot: "breakfast", source: "planned" },
    ["2025-06-07", "2025-06-21", "2025-07-05", "2025-07-19", "2025-08-02", "2025-08-16"],
  ),
  // Greek yoghurt — breakfast bowl partner
  ...repeat(
    { food: "greek-yoghurt", foodName: "Greek Yoghurt", mealName: "Breakfast Bowl", mealSlot: "breakfast", source: "planned" },
    ["2025-06-07", "2025-06-21", "2025-07-05", "2025-07-19", "2025-08-02", "2025-08-16"],
  ),
  // Cucumber — first met this summer (a discovery), used a few times
  ...repeat(
    { food: "cucumber", foodName: "Cucumber", mealName: "Snack Plate", mealSlot: "snack", source: "planned" },
    ["2025-07-02", "2025-07-16", "2025-08-06"],
  ),
];

const familyStory = seasonalStories({
  household: { entries: familyHistory },
  season: { season: "summer", year: 2025 },
  now: NOW,
});
console.log(formatSeasonalStory(familyStory));
checkTrust("family", familyStory);
report["family-summer-2025"] = familyStory;

expect("family: season summary present", blockTypes(familyStory).includes("season_summary"));
expect(
  "family: Friday pizza tradition surfaced as a favourite moment",
  familyStory.blocks
    .find((b) => b.type === "favourite_moments")
    ?.cards.some(
      (c) =>
        c.headline.toLowerCase().includes("friday") &&
        c.headline.toLowerCase().includes("pizza"),
    ) ?? false,
);
console.log();

// ════════════════════════════════════════════════════════════════════════════
// 3. VEGETARIAN HOUSEHOLD — autumn 2025
// ════════════════════════════════════════════════════════════════════════════
//
// Plant-forward autumn: squash, mushrooms, lentils, kale. No meat anywhere; the
// story celebrates the produce of the season without ever implying a "should".

console.log(line);
console.log("3. VEGETARIAN HOUSEHOLD — autumn 2025 (squash, mushrooms, lentils)\n");

const vegHistory: MealEntry[] = [
  ...repeat(
    { food: "butternut-squash", foodName: "Butternut Squash", mealName: "Squash Risotto", mealSlot: "dinner", source: "planned" },
    ["2025-09-05", "2025-09-19", "2025-10-03", "2025-10-17", "2025-10-31", "2025-11-14", "2025-11-28"],
  ),
  ...repeat(
    { food: "mushroom", foodName: "Mushroom", mealName: "Mushroom Stroganoff", mealSlot: "dinner", source: "planned" },
    ["2025-09-08", "2025-09-22", "2025-10-06", "2025-10-20", "2025-11-03", "2025-11-17"],
  ),
  ...repeat(
    { food: "lentils", foodName: "Lentils", mealName: "Lentil Soup", mealSlot: "dinner", source: "planned" },
    ["2025-09-12", "2025-09-26", "2025-10-10", "2025-10-24", "2025-11-07", "2025-11-21"],
  ),
  ...repeat(
    { food: "kale", foodName: "Kale", mealName: "Greens", mealSlot: "dinner", source: "planned" },
    ["2025-09-15", "2025-10-13", "2025-11-10"],
  ),
  // Beetroot — first met this autumn (a discovery)
  ...repeat(
    { food: "beetroot", foodName: "Beetroot", mealName: "Roasted Beets", mealSlot: "dinner", source: "planned" },
    ["2025-10-08", "2025-10-29", "2025-11-19"],
  ),
];

const vegStory = seasonalStories({
  household: { entries: vegHistory },
  season: { season: "autumn", year: 2025 },
  now: NOW,
});
console.log(formatSeasonalStory(vegStory));
checkTrust("vegetarian", vegStory);
report["vegetarian-autumn-2025"] = vegStory;

expect("vegetarian: season summary present", blockTypes(vegStory).includes("season_summary"));
expect("vegetarian: seasonal habits present (autumn shape)", blockTypes(vegStory).includes("seasonal_habits"));
expect(
  "vegetarian: looking ahead points to winter foods",
  vegStory.blocks
    .find((b) => b.type === "looking_ahead")
    ?.cards.some((c) => c.headline.toLowerCase().includes("winter")) ?? false,
);
console.log();

// ════════════════════════════════════════════════════════════════════════════
// 4. HOUSEHOLD DISCOVERING LEGUMES — winter 2026
// ════════════════════════════════════════════════════════════════════════════
//
// A household leaning into legumes for the first time over the cold months:
// chickpeas, then butter beans, then cannellini beans. Winter spans Dec 2025 –
// Feb 2026 — the story should recognise the legumes met and made regular this
// winter, without ever framing it as "improvement".

console.log(line);
console.log("4. HOUSEHOLD DISCOVERING LEGUMES — winter 2026 (Dec 2025 – Feb 2026)\n");

const legumeHistory: MealEntry[] = [
  // Chickpeas — the entry point, met early winter, made regular
  ...repeat(
    { food: "chickpeas", foodName: "Chickpeas", mealName: "Chickpea Curry", mealSlot: "dinner", source: "planned" },
    ["2025-12-03", "2025-12-17", "2026-01-07", "2026-01-21", "2026-02-04", "2026-02-18"],
  ),
  // Butter beans — met mid-winter
  ...repeat(
    { food: "butter-beans", foodName: "Butter Beans", mealName: "Butter Bean Stew", mealSlot: "dinner", source: "planned" },
    ["2025-12-10", "2026-01-14", "2026-02-11"],
  ),
  // Cannellini beans — met late winter
  ...repeat(
    { food: "cannellini-beans", foodName: "Cannellini Beans", mealName: "Bean Soup", mealSlot: "dinner", source: "planned" },
    ["2026-01-28", "2026-02-25"],
  ),
  // Some non-legume staples so the season isn't only legumes
  ...repeat(
    { food: "leek", foodName: "Leek", mealName: "Leek & Potato Soup", mealSlot: "dinner", source: "planned" },
    ["2025-12-05", "2026-01-09", "2026-02-06"],
  ),
  ...repeat(
    { food: "potato", foodName: "Potato", mealName: "Roast Veg", mealSlot: "dinner", source: "planned" },
    ["2025-12-19", "2026-01-23", "2026-02-13"],
  ),
];

const legumeStory = seasonalStories({
  household: { entries: legumeHistory },
  season: { season: "winter", year: 2026 },
  now: NOW,
});
console.log(formatSeasonalStory(legumeStory));
checkTrust("legumes", legumeStory);
report["legumes-winter-2026"] = legumeStory;

expect("legumes: season summary present", blockTypes(legumeStory).includes("season_summary"));
expect(
  "legumes: chickpeas/butter beans/cannellini surfaced as discoveries",
  legumeStory.blocks
    .find((b) => b.type === "discoveries")
    ?.cards.some((c) =>
      /chickpea|butter bean|cannellini/i.test(c.headline + JSON.stringify(c.facts)),
    ) ?? false,
);
expect(
  "legumes: looking ahead points to spring foods",
  legumeStory.blocks
    .find((b) => b.type === "looking_ahead")
    ?.cards.some((c) => c.headline.toLowerCase().includes("spring")) ?? false,
);
console.log();

// ════════════════════════════════════════════════════════════════════════════
// 5. SILENCE CONTRACT — a barely-cooked season stays silent
// ════════════════════════════════════════════════════════════════════════════

console.log(line);
console.log("5. SILENCE CONTRACT — sparse season stays silent\n");

const sparseStory = seasonalStories({
  household: {
    entries: [
      { food: "tomato", foodName: "Tomato", date: d("2026-04-02"), source: "planned" },
      { food: "carrot", foodName: "Carrot", date: d("2026-05-10"), source: "planned" },
    ],
  },
  season: { season: "spring", year: 2026 },
  now: NOW,
});
console.log(formatSeasonalStory(sparseStory));
expect(
  "sparse season: no season summary (below 3-meal threshold)",
  !blockTypes(sparseStory).includes("season_summary"),
);
expect(
  "sparse season: no favourite moments, no habits",
  !blockTypes(sparseStory).includes("favourite_moments") &&
    !blockTypes(sparseStory).includes("seasonal_habits"),
);

const emptyStory = seasonalStories({
  household: { entries: [] },
  season: { season: "spring", year: 2026 },
  now: NOW,
});
expect("empty season: looking-ahead may still appear, no memory blocks",
  emptyStory.blocks.every((b) => b.type === "looking_ahead"));
console.log();

// ════════════════════════════════════════════════════════════════════════════
// 6. BLOCK NARROWING + DEFAULT SEASON
// ════════════════════════════════════════════════════════════════════════════

console.log(line);
console.log("6. BLOCK NARROWING + default season from now\n");

const narrowed = seasonalStories({
  household: { entries: mediterHistory },
  season: { season: "summer", year: 2025 },
  now: NOW,
  blocks: ["season_summary"],
});
expect(
  "block narrowing: only season_summary returned",
  narrowed.blocks.length > 0 && narrowed.blocks.every((b) => b.type === "season_summary"),
);

const defaulted = seasonalStories({
  household: { entries: mediterHistory },
  now: NOW, // 2026-06-22 → summer 2026
});
expect(
  "default season: derived from now (summer 2026)",
  defaulted.season === "summer" && defaulted.year === 2026,
);
console.log();

// ════════════════════════════════════════════════════════════════════════════
// 7. TRUST GATE — all authored text across all examples
// ════════════════════════════════════════════════════════════════════════════

console.log(line);
console.log("7. TRUST GATE — all seasonal text across all examples\n");

const allStories: SeasonalStory[] = [
  medSummer, medSpring, medAutumn,
  familyStory, vegStory, legumeStory,
];
let totalCards = 0;
let trustFailures = 0;
for (const s of allStories) {
  totalCards += allCards(s).length;
  try {
    assertTrustworthy(allCards(s));
  } catch (e) {
    trustFailures++;
    failures++;
    console.log(`  ✗ Trust violation: ${(e as Error).message}`);
  }
}
expect(
  `all ${totalCards} seasonal cards across all examples pass the trust gate`,
  trustFailures === 0,
);
console.log();

// ── Persist report ──────────────────────────────────────────────────────────

const outDir = join(process.cwd(), "data", "seasonal");
mkdirSync(outDir, { recursive: true });
const outPath = join(outDir, "ws11-seasonal-stories-report.json");
writeFileSync(
  outPath,
  JSON.stringify(
    {
      workstream: "WS11 — Seasonal Stories Engine",
      generatedAt: new Date().toISOString(),
      totalCards,
      examples: report,
    },
    null,
    2,
  ),
);
console.log(`Report written: ${outPath}`);

// ── Summary ───────────────────────────────────────────────────────────────────

console.log(`\n${line}`);
if (failures === 0) {
  console.log("✓ WS11 — all worked examples, gates and trust checks passed.");
} else {
  console.log(`✗ WS11 — ${failures} check(s) failed.`);
  process.exit(1);
}
